binary-com/deriv-com

- src/pages/markets/synthetic/_digital-options.js
- src/pages/markets/synthetic/_margin.js
- src/pages/markets/synthetic/_multipliers.js
Fix layout in synthetic indices market page
Changes:
-   Increase width for synthetic indices market page for margin and multipliers
> fix layout in synthetic indices  market page for margin and multipliers

- src/pages/trade-types/margin/_policies.js
- src/pages/trader-tools/_style.js
- src/pages/trader-tools/_swap-calculator.js
- src/themes/variables.js
Summary
Changes:
-   css webkit for scroll styling
-  swap calculator `learn more button` to target anchor hash on to margin - swap
> Kevin/feat: update calculator scroll and anchor hash link

- src/components/graphql/fragments.js
Summary
- Fixed low quality image in career location hero banner.
Changes:
- By default, if unspecified, Gatsby will set an image quality of 50%. Increased to 90% with a max width of double (2048 px).
> yashim/fix: Image quality of hero banner in career location pages

- src/common/utility.js
- src/common/websocket/socket_base.js
Summary
- getLanguage() was returning wrong language codes (kebab-case) 
Changes:
-   ...
> Yashim/fix: getLanguage() returning invalid language codes

- src/components/elements/carousel/carousel-style.js
- src/components/elements/carousel/carousel.js
- src/pages/dmt5/_margin_calculator.js
- src/pages/home/_trade-types-mobile.js
Summary
- Fixed trade type card margins and added navigation dot to trade type card slider in main page
Changes:
- Refactored styledDot to accept `--color ` variables directly instead of remapping strings to color variables
> yashim/fix: trade types card in main page

- src/pages/trade-types/components/_side-tab.js
- src/pages/trade-types/multiplier/_what-are-multipliers.js
Fix viewport in '/trade-types/multiplier' under 350px devices
> Abdalla/Fix: trade-types -> multiplier viewport under 350px

- src/common/utility.js
- src/components/hooks/use-active-link-state.js
- src/components/layout/nav-careers.js
- src/components/layout/nav.js
- src/components/localization/localized-link.js
Summary
- Added hook to check active link by comparing current url to a page map.
Changes:
- Fixed active link style (Add red underline)
- Navigation will now be active when dropdown selected and when the current url pathname belongs to the navigation
> yashim/feat: add hook to check active link at navigation bar.

- src/common/utility.js
- src/components/hooks/gtm-data-hooks.js
- src/components/hooks/use-livechat.js
- src/components/layout/layout.js
We need to sent `loggedIn` and `language` properties along with `event` on every event triggered.
This PR
* Created new hooks that sent out `gtm_data` and `setGTMData`
* `gtm_data` contains an object that is currently of shape `{ event: eventName }`
* Final object to sent out `{ event: eventName, loggedIn: is_logged_in, language: language }`
* Note: `eventName: string` - `loggedIn: boolean` - `language: string`
> Abdalla/Add: LoggedIn and language to GTMData

- src/components/layout/nav.js
Changes:
-   Change device sizing from 992px to 991px for desktop nav component (NavLeft,NavCenter and NavRight)
> Fix:Issue on navbar went missing on 992px width

- src/pages/p2p/components/_numbers.js
Changes:
-   Add 'USD' in front of 2M in numbers component for p2p v1 and v2 page.
-   [X] Translation to crowdin
> Nuri/udpate: add USD currency in front of 2M in p2p v1 and v2 page

- src/components/custom/signup.js
- src/components/hooks/use-marketing-data.js
- src/store/index.js
Changes:
-   Add hook to extract marketing data either from url params or cookies
-   Handle marketing data globally in deriv store
-   Pull affiliate token in signup page from store 
> Sean / feat(marketing): add marketing data from url or cookies into deriv store

- src/pages/responsible/_trading-limits.js
Changes:
-   Removed paragraph containing support phone numbers and show the numbers only for UK.
-  also add params for isUK function
> Nuri/fix: Remove phone number for responsible trading page

- src/components/layout/layout.js
Changes:
-   Fix: overflowing text for some languages (FR, PL, ID, IT) in CFD banner
> Sean / fix: overflowing text for some languages in CFD banner

- src/pages/trader-tools/common/_style.js
- src/pages/trader-tools/margin-calculator/_margin-calculator.js
- src/pages/trader-tools/swap-calculator/_swap-calculator.js
Changes:
-   Fix: footer links not hover-able for calculator pages
> Sean/fix: footer links not hover-able for calculator pages

- src/pages/trader-tools/swap-calculator/_swap-calculator.js
> Sean/fix: footer links not hoverable for financial swap calculator page

- .circleci/config.yml
Switch to blue/green Deployment as a default release strategy on staging & production workflows
Before removing the old resources on default k8s namespace we need to Merge this
Changes:
-   ...
> Remove the old release and use Blue/Green deployment as default

- .github/workflows/staging.yml
Because we don't use tag for releasing staging
Changes:
-   ...
> Using $GITHUB_SHA instead of $GIT_TAG_NAME

- src/pages/besquare/components/sections/_what-is_besquare.js
- src/pages/besquare/static/style/_hero.js
Changes:
-   the 1st image's top padding was decreased
- "why besquare?" column : changes of style  for good view  on screen with width 320-330px
-   [ x ] Style only
> nikolai.berestevich Bug #21338 ***fix*** besquare page 1st img and "why besquare "column text margin/padding were changed 

- src/pages/trader-tools/common/_utility.js
- src/pages/trader-tools/common/_validation.js
- src/pages/trader-tools/margin-calculator/_margin-calculator.js
- src/pages/trader-tools/pip-calculator/_pip-calculator.js
- src/pages/trader-tools/pnl-for-margin/_pnl-for-margin.js
- src/pages/trader-tools/pnl-for-multipliers/_pnl-for-multipliers.js
- src/pages/trader-tools/swap-calculator/_swap-calculator.js
Changes:
-  getMaxLength function was created and  added to the trader-tools/calculators 
-   [ x ] New feature
> nikolai.berestevich/fix/trader-tools-calculators: point is not a digit 30154

- src/components/layout/footer/common/style.js
Changes:
-   homepage: 
Mobile: Copyright text change : now it is left aligned
-   [ x ] Style only
> nikolai.berestevich/style/copyright to left #35694

- src/pages/trader-tools/_tools.js
Changes:
-   change alt tags to '' on Resources's pages excluding /blog
> nikolai.berestevich/refactor/delete-alt-tags-resourses

- src/pages/derivx/_accounts.js
- src/pages/dmt5/_flexibility.js
- src/pages/dmt5/_why-trader.js
- src/pages/trade-types/margin/_available-markets.js
- src/pages/trade-types/margin/_why-trade-margin.js
- src/pages/trade-types/multiplier/_available-trades.js
- src/pages/trade-types/multiplier/_how-multiplier-works.js
- src/pages/trade-types/multiplier/_markets-available.js
- src/pages/trade-types/multiplier/_what-are-multipliers.js
- src/pages/trade-types/options/_how-options-works.js
- src/pages/trade-types/options/_markets-available.js
- src/pages/trade-types/options/_what-are-options.js
Changes:
- alt tags were changed to empty for images from /trader-types block
> nikolai.berestevich/refactor/change-alt-tags-tradetypes-39868

- src/pages/academy/_recent-featured-posts.js
Changes:
-   Fix expanded height of tags when title is one line long
> fix: expanded height of tags when title is one line long

- src/components/custom/_dbanner.js
Changes:
-   Footer banner from https://deriv.com/dtrader/ in 1351px - 1385 between logo and text add @media margin 
> "Footer banner from https://deriv.com/dtrader/ in 1366px between logo and text" - fixed

- src/pages/markets/instruments/_market-symbols.js
Changes:
-   Move CHF/JPY from exotic pairs to minor pairs
> KolesnikN/move CHF/JPY from exotic to minor pairs

- .eslintrc
- src/components/elements/checkbox.tsx
- src/components/elements/query-image.tsx
- src/components/elements/video-player.tsx
- src/pages/404.tsx
- src/pages/careers/besquare/components/sections/_highlights.tsx
- src/pages/check-email/_icon-grid.tsx
- src/pages/derivx/_accounts.tsx
- src/pages/derivx/_hero.tsx
- src/pages/derivx/_selling-points.tsx
- src/pages/derivx/_start-derivx.tsx
- src/pages/derivx/_what-is-derivx.tsx
- src/pages/derivx/_why-trade-derivx.tsx
- src/pages/derivx/index.tsx
- src/pages/home/_trade-the-way-you-like.tsx
- src/pages/why-choose-us/_icon-grid.tsx
- src/pages/why-choose-us/index.tsx
- src/store/index.tsx
Changes:
-   Update eslint config to allow no explicit declaration of return type for React components
> chore: update eslint config to allow no explicit return type

- src/pages/home/_hero.js
Changes:
loading="eager" attribute missed in the homepage hero that cause the gatsby image extension to load the image lazily.
is_eager removed and loading attr added instead 
-   ...
> Ako/ remove is_eager and use loading attribute instead

- src/pages/404.tsx
To reduce LCP we should load image eagerly
> Ako/ load 404 first fold image eagerly

- src/templates/article.js
Changes:
Added passive option to scroll event listener since it's a best practice to have a smooth scrolling 
> Ako/ add `passive:true` to scroll event listener of article component

- src/components/elements/query-image.tsx
Changes:
- By default, Gatsby Images will use the fade-in animation for image load
- Animations on appear like this impacts, LCP. This PR removes fade in animation on eager loaded images
> yashim/fix: LCP for eager loading Images

- gatsby-browser.js
- src/components/layout/layout.js
Changes:
-  Added a delay to fire `page_view` events 
-  Added an onload listener to trigger `allow_tracking` events only after the window is loaded
> GTM event delay

- src/pages/markets/instruments/_market-symbols.js
Changes:
- only ETH and Bitcoin on trade-types/multiplier/
> nikolai.berestevich/fix/crypto-icons

- src/pages/markets/components/markets/_synthetic-indices.js
Changes:
-   fix: missing options tab in synthetics market page
> fix: missing options tab in synthetics market page

- src/components/layout/besquare/style/footer.js
Changes:
-   Adjusted _FooterSection_ padding to fix the cropped icons in responsive mode for EU region
> fiona/ resize footer section for besquare in responsive mode

- src/pages/help-centre/index.tsx
Changes:
-  Deriv P2P section in help-centre page is hidden for EU clients
> Aswathy/ Deriv P2P section in help-centre page is hidden for EU clients

- src/common/validation.js
Changes:
-   Allow email validation to accept hyphens after the alias
> Allow email validation to accept hyphens after the alias

- src/components/custom/signup.js
Changes:
-   Removed the affiliate token from cookies during signup without affiliate token
> Aswathy/fix: removal of affiliate token from cookies

- src/pages/partners/affiliate-ib/_dmt5-cards.tsx
Changes:
Fixed Alignment issue in Volatility Indices list under Deriv MT5 Synthetics(About us-->Partnership Programmes-->Affiliates and IBs-->Deriv MT5 Synthetics-->Volatility indices) in Mobile devices
-   ...
> Meenu/fix: alignment fix in about us page

- src/pages/home/_markets_fold.tsx
Changes:
Localize text "Markets" in homepage
> Meenu/ fix: localize the text markets in homepage

- .github/workflows/production.yml
- .github/workflows/staging.yml
Changes:
-   Use v3 of actions/setup-node and its native caching capability
> tib/chore: setup node v3 with cache

- deriv.com.conf
- gatsby-node.js
Changes:
- since we added redirects in nginx conf, these should be removed
- changes on this PR won't be testable on vercel test link, and it's only testable on staging deployment.
1. cd into root of the project.
2. build the docker image like so:
```
docker build -t deriv-redirect . 
```
3. run the docker container like so: 
```
docker run -p 80:80 deriv-redirect
```
4. open up localhost on browser.
5. go to [localhost/markets](localhost/markets) ===> it should redirect you to [localhost/markets/forex/](localhost/markets/forex/)
6. go to [localhost/pt/markets](localhost/pt/markets) ===> it should redirect you to [localhost/pt/markets/forex/](localhost/pt/markets/forex/)
7. go to [localhost/pt/markets/stock](localhost/pt/markets/stock) ===> it should redirect you to …
> Mohsen / removed gatsby markets redirect

- .dockerignore
Changes:
- right now when building the docker image, docker has to copy ~5GB of
content to build context, with this it will be around ~900mb so it will
help with faster build times on staging and production
Steps:
- checkout the project
- run `docker build -t test-deriv-com .`
- the build context will be ~900 MB, currently its around ~5GB.
> chore: added .dockerignore file

- .eslintrc
- src/components/containers/box.tsx
- src/components/localization/localize.tsx
- tsconfig.json
- types/react-i18next.d.ts
Changes:
-  Fixed the type eslint issue with `i18next-react` issue, this is related to `tsconfig.json` and `eslintrc`
> Mohsen / : fixed i18next-react Trans import type error

- src/pages/markets/static/content/_digital-options.tsx
- src/pages/markets/static/content/_market-symbols.tsx
> Mitra/change `silver/eur` to `silver/usd` in commodities option tab

- src/components/elements/query-image.tsx
Changes:
-   removed unused code in ImageWrapper (never changes `disable_transition` props value to `true`, always uses default `disable_transition` props value, `loading` value changes due to `[data-main-image]`. Both conditions must be met, but this behavior will never happen)
-   [ X ] Refactor code
> Eduard / Attribute loading not allowed on element div (loading isn't an attribute, it's a props)

- gatsby-config.js
Changes:
-   remove strategy option from gatsby-google-gtm
-   [ X ] Bug fix
> remove strategy option from gatsby-google-gtm

- .github/workflows/lighthouse.yml
Changes:
-   Give back some permission to GITHUB_TOKEN
> Specify GITHUB_TOKEN permissions in lighthouse.yml

- gatsby-config.js
Changes:
-   sessionSampleRate used instead of sampleRate because sampleRate is deprecated
> Ako/ change sampleRate key to sessionSampleRate

- .github/workflows/stale.yml
Changes:
-  add stale label to PRs after 60 days of inactivity
-  close stale PRs after 5 days 
> chore: added stale PR github action

- .github/workflows/production.yml
- .github/workflows/staging.yml
- Seems like we waste build time by doing `checkout`, `npm ci` then `npm test` one first time then in main job again. Removing the job dependency
> Optimize build no dependency on lint for nothing

- i18n-config.js
- src/common/constants.ts
- src/features/components/molecules/language-switcher/useLangSwitcher.tsx
- src/pages/landing/ebooks/crypto.tsx
- src/pages/regulatory/_document_accordion.tsx
- src/pages/terms-and-conditions/_business-grid.tsx
Changes:
-   Disable all `portuguse` related contents: language-switcher, pdfs, marketing materials
> yashim/chore: disable portugese content

- src/pages/markets/components/helper/_available-trades_desktop.tsx
Changes:
Customers coming from DerivGo shouldn't see header/footer, yet, when switching between CFDs/Multipliers/Options tabs, header/footer is reappering. Fixed by ensuring param platform=derivgo is passed across tabs navigation.
There are chances that the same bug happens in other places when derivgo customers navigate through pages, as "platform=derivgo" parameter is not universally handled across pages and links (which makes sense). I lack historical context, but it seems that original implementation of features required to support derivgo is reaching the limits of its scalability. If the same bug happens in other places, we might need to switch to different solution / extract separate versions for DerivGo / refactor pages a bit.
-   [X ] Bug fix
-   [ ] Update …
> DERC-1304: fixed navigation between tabs when navigating from derivgo

- src/components/custom/other-platforms.tsx
- src/components/elements/off-canvas-menu.tsx
- src/features/components/templates/footer/data.ts
- src/features/components/templates/navigation/main-nav/content/platform/index.ts
- src/features/pages/home/trade-types/data.tsx
Changes:
🔥 🔥 
We have an issue in gatsby-node.js file for `zh-cn` and `zh-tw` that redirection doesn’t apply correctly when on these languages. 
As a workaround I updated all the old urls which for now it works fine , but we need another fix for the gatsby-node.js issue for redirection 
> fix: :fire: fix redirection issue

- .babelrc
Changes:
-  The Babel preset for Gatsby `babel-preset-gatsby` was not used since the `stage` option for `build-javascript` stage was not passed in, thus resulting in the chunks being bundled into a big, single chunk.
Once the preset argument has been passed, the chunks are splitted accordingly:
Refer to issue https://github.com/gatsbyjs/gatsby/issues/35731 for more information.
> Adrienne & Jim /  Fixed an issue where stage option is not passed to the gatsby babel preset

- src/features/components/molecules/timeline-item/style.module.scss
Changes:
-  Fixing Trade > Options page :: "Start trading options on Deriv" section doesn’t show the dotted lines to show the flow
> Hasan/fix: timeline dot line issue

- src/components/elements/dropdown-search.tsx
Changes:
- Fixing the issue where we have two labels for the symbol field in the margin calculator
> fix: :bug: having two label for symbol field

- src/pages/payment-methods/index.tsx
Changes:
This was the regression bug. I have added `payment-list` ID again. 
-   ...
> fix: added id for payment method section

- src/features/components/templates/navigation/template/mobile-menu/mobile-menu.module.scss
Changes:
Updated  `inset-inline-start` css value from `-100vh` to `-100%` fix the side navigation adjustment.
> Hasan/fix: side navigation adjustment

- .github/workflows/generate-preview-link.yml
Changes:
Seems like there is an issue with cf-pages branch chars limit.
https://translation-1174-revert-live-pricing.deriv-com-preview-links.pages.dev/ - This doesn't work
https://translation-11741111.deriv-com-preview-links.pages.dev/ - This works
> Bala/Fix cf-pages chars limit issue

- .github/workflows/beta.yml
- .github/workflows/production.yml
- .github/workflows/staging.yml
Changes:
-   Updated the cloudfare wrangler from pages publish to pages deploy
> Aswathy/feat: updated the cloudfare wrangler

- src/pages/trading-specification/data/_commodities_specification.ts
Changes:
add the SWF  tag next to all the instruments (similar to the `SWF` tag on `Forex` [trading specs](https://deriv.com/trading-specification/))
> Konstantinos / [ROW] Addition of SWF tag on all commodities on trading specs page 

- .github/workflows/generate-preview-link.yml
No longer call the tests via API. 
Now we're pulling the test code and running via Cypress Cloud.
Changes:
-   ...
-   [x ] Script configuration
> Modified e2e smoke test section

- src/pages/markets/instruments/_drift_switch_indices.tsx
> Konstantinos / Remove 'Demo' tag on DSI page

- src/features/components/organisms/navigation/nav-card-items/index.tsx
- src/features/components/organisms/navigation/nav-sections-container/section-column.tsx
- src/features/components/templates/footer/index.tsx
- src/features/components/templates/navigation/template/nav-drop-items/index.tsx
- src/features/components/templates/navigation/template/nav-single-item/index.tsx
- src/features/components/templates/trade-platform/what-have/index.tsx
- src/features/pages/check-email/check-email.steps.tsx
- src/features/pages/deriv-ez/what-have/index.tsx
- src/pages/home/_vertical-carousel.tsx
- src/pages/landing/jump-indices/_leverages.tsx
- src/pages/markets/components/sections/_other-markets.tsx
- src/pages/markets/components/sub-markets/_digital-options.tsx
- src/pages/trade-types/accumulators/_what-are-accumulators.tsx
- src/themes/plugin/index.ts
Changes:
to fix the track js issue (Cannot read properties of null (reading 'content'))
so added some extra checks over 'content' word.
> fix: track js issue

- crowdin/messages.json
- src/features/pages/markets/etf/trades-available/data.tsx
> fix: fix eu etf

- src/pages/partners/affiliate-ib/_dmt5-cards.tsx
Changes:
Scroll to top of the card when the back button is clicked:
> Konstantinos / Clicking back button should keep me on the card #5766

- .eslintrc
Changes:
-   Importing the Layout component before the other child component order rule is set in eslint.
> Aswathy/fix: eslint error to import layout component first

- src/features/pages/markets/etf/trades-available/data.tsx
Changes:
-  hiding mention of Ctrader for eu in etf page
> mitra/ hide cTrader for eu

- src/pages/regulatory/_document_accordion.tsx
- src/pages/regulatory/data/_kid_data.tsx
Changes:
-  ETF key information document shows 404 for few languages, fixing as it only has eng version ( for all other PDFs the 4 languages is supported) 
> Fix etf kid for non eng language

- .github/workflows/generate-preview-link.yml
Changes:
Add env variables in the build step to fix growth book issue in test links.
> Add env variables in build step

- src/features/components/atoms/tab/tab-switcher/index.tsx
- src/features/components/templates/banners/deriv-products-hero/products-logo-and-text.tsx
- src/features/components/templates/banners/deriv-products-hero/types.ts
- src/features/pages/deriv-ctrader/hero-banner/data.tsx
Changes:
Add real account button back in cTrader and remove the Demo icon
> feat: remove demo and add real button back

- src/features/pages/home/hero/content/hero-features.carousel.tsx
Changes:
Add test ID for auto typing issue
-   ...
> Fasih/: added test id

- crowdin/messages.json
- src/components/layout/layout-overlay.tsx
- src/features/components/molecules/layout-overlay/index.tsx
- src/pages/help-centre/components/_didnt-find-answer.tsx
> chore: disable whatsapp

- .github/workflows/generate-preview-link.yml
- .github/workflows/lighthouse.yml
- .github/workflows/smoketests.yml
Changes:
-   Capture cf pages preview URL to run lighthouse and smoke test
> Bala/capture cf pages preview URL to run lighthouse and smoke test

- .github/workflows/translation-sync.yml
> Prince/Update translation-sync.yml

- src/features/hooks/use-signup-form/index.tsx
- src/features/pages/signup/form-container/form-social-buttons.tsx
Changes:
This pull request fixing the event track issue, when user trying to signup. We have to provide `signup_provider` data properly. To resolve this, some options were changed
> [CRO] signup_provider is null in BigQuery for some 'started' action

- src/features/hooks/use-signup-form/index.tsx
- src/pages/signup-success/index.tsx
Changes:
Using cookie in order to store the email instead of showing it to the URL after signing up.
> Konstantinos / Prevent Email Exposure in Signup Success Page URL

- .github/workflows/staging.yml
Changes:
Since the github_ref_name is not valid, i'm using SHA on staging workflow.
> Ako/ use SHA on staging workflow

- src/components/hooks/use-livechat.tsx
Changes:
Remove the type="text/partytown" from partytown as it's causing TrackJS logs on Cannot read properties of undefined (reading 'on') .
> Konstantinos/FEQ-1007/Cannot read properties of undefined (reading 'on')

- gatsby-browser.js
Changes:
-   Set datadog session replay to 0
> chore: remove datadog sessionreplay

- src/features/pages/home/hero/index.tsx
- src/features/pages/home/hero/styles.module.scss
- src/features/pages/home/navigation/nav.buttons.tsx
- src/features/pages/home/years/data.tsx
- src/features/pages/home/years/index.tsx
> chore: fixed designers suggestions for hero content

- src/features/components/templates/footer/banner-and-awards.tsx
> fix: hide IIP-gold award in footer

- .github/workflows/production.yml
Changes:
-   Separated Docker and Kubernetes Status notification from Cloudflare Pages deployment slack notification in deriv-com repo
-   [X] Release
> [FEQ]/Yaswanth/FEQ-1089/To separate docker and k8s notification

- src/common/constants.ts
- src/common/country-base.ts
- src/features/components/templates/footer/download.tsx
Changes:
- Hide app gallery and app store option in footer for deriv go for countries which is not supported
> Mitra/DERC-2411/hide app gallery and app store if it is not supported 

- src/pages/trading-specification/components/_elements.tsx
Changes:
Fix tooltip arrow in trading specification page being a bit out of the position.
> Konstantinos/DPROD-2987/Tooltip arrow in trading specification page is a bit out of the position.

- gatsby-node.js
Changes:
-   Bundle-seperation for node_modules and other tsx/ts/js files
> habib/DPROD-3504/Bundle-seperation for node_modules

- .github/workflows/generate-preview-link-eu.yml
- .github/workflows/generate-preview-link-row.yml
Changes:
-   Multiple build base don branch name
> chore: update multiple build action yml

- .github/workflows/smoketests-eu.yml
- .github/workflows/smoketests-row.yml
**Changes:**
- Updated smoke test workflows to meet the requirements for https://github.com/actions/download-artifact action.
- Passing the workflow token as it is needed because we are fetching artifacts from another workflow run. [REF](https://github.com/actions/download-artifact#:~:text=current%20workflow%20run.-,github%2Dtoken%3A,-%23%20The%20repository)
> Updated smoketest workflows

- .github/workflows/production-eu.yml
- .github/workflows/production-row.yml
- .github/workflows/staging-eu.yml
- .github/workflows/staging-row.yml
Changes:
-   Fixing vulnerable usage of `env.` variable in github action workflows - `${{ env.CA_CRT }}`
- .github/workflows/production-eu.yml
- .github/workflows/production-row.yml
- .github/workflows/staging-eu.yml
- .github/workflows/staging-row.yml
- [WikiJS Doc](https://wikijs.deriv.cloud/en/Security/product-security/github-workflow-scanner#:~:text=workflow_audit_6%20%2D%20Risky%20Contexts%20and%20Vulnerable%20ENV%20Review%20%2D%20Check%20for%20potential%20script%20injections) 
> Fix gh action vulnerable env
