binary-com/deriv-com

- crowdin/messages.json
- package-lock.json
- package.json
- src/pages/careers/_model/_locations/_locations.ts
> Prince/ updated package lock and some spacing issue

- gatsby-browser.js
Changes:
-   Check for browser compatibility
> yashim/feat: add browser check before collecting performance parameters

- .github/workflows/translation-push.yml
> Prince/ latest commit search

- .github/workflows/translation-push.yml
> Prince/ Print Github context

- .github/workflows/translation-push.yml
> Prince/ Extra print details

- .github/workflows/translation-push.yml
> Prince/ print workflow run alone

- .github/workflows/translation-push.yml
> Prince/ fetching latest commit 

- .github/workflows/translation-push.yml
> Prince/ fetch latest commit 

- .github/workflows/translation-push.yml
> Prince/ Fetch last commit 

- .github/workflows/translation-push.yml
> Prince/ only pull translation on demand

- .github/workflows/translation-push.yml
> Prince/ auto pull translation on demand 

- .github/workflows/translation-push.yml
> Prince/ Commit only when there's new translation data

- .github/workflows/translation-push.yml
> Prince/ Update commit rule for pulled translations

- scripts/handle-translations.js
> Prince/ Update translation pull script

- crowdin/messages.json
- package-lock.json
- package.json
- src/pages/careers/_model/_locations/_locations.ts
Reverts binary-com/deriv-com#3405
> Revert "Prince/ updated package lock and some spacing issue"

- package-lock.json
Changes:
- updated the package-lock.json to fix the issue with SSR error on
staging.
Steps:
after checking out the PR's branch:
1. please run `npx gatsby clean`.
2. please run `rm -rf node_modules`.
3. please run `npm ci`.
4. now run `npm run develop`.
> fix: fixed the staging build issue

- src/pages/academy/components/_search-banner.tsx
> MohammadH/ Close Academy topics dropdown by clicking outside

- src/pages/partners/affiliate-ib/_more-reason.tsx
- src/pages/partners/affiliate-ib/_who-can-apply.tsx
> Meenu/fix: alignment fix for more reason to join

- src/components/elements/index.ts
- src/components/elements/off-canvas-menu-career.js
- src/components/layout/nav/nav-careers.tsx
> Meenu/fix: new headers for careers page

- src/pages/dbot/index.tsx
Changes:
- fixed dbot page seo 
> Mohsen / fixed dbot page seo

- gatsby-browser.js
- gatsby-ssr.js
> Add vwo script

- src/pages/markets/static/content/_details.tsx
> Mitra/fix: hide netherland 25 description for eu

- crowdin/messages.json
- src/pages/regulatory/index.tsx
> Aswathy/ New content changes in the regulatory dbvi content

- src/components/layout/nav/nav-careers.tsx
> fix: remove navbar gap issue in career page

- src/pages/payment-methods/index.js
> Konstantinos / [FE Deriv.com squad] [EU] Remove Fiat Onramp from [Payment Method page]

- src/components/custom/signup.js
> Konstantinos / Overflows sign-up email for new users on mobile - Usability Issues

- src/pages/careers/_model/_locations/_locations.ts
> Mitra/fix: update paris location content

- src/pages/dmt5-trading-signals/_signal-steps.tsx
- src/pages/dmt5-trading-signals/_subscription.tsx
> Konstantinos / MQL5 links issues in DMT5 Signals page

- src/pages/help-centre/_help-articles.tsx
Changes:
Removed duplicate from FAQ section in Help center.
-   ...
> Meenu/fix: remove duplicates from faq

- .github/workflows/translation-push.yml
> Prince/ added link to crowdin on slack webhook

- package-lock.json
- package.json
- src/components/layout/layout.js
> MohammadH/ If Academy blog page does not exist redirect to the closest match blog page

- src/components/hooks/use-scroll.tsx
- src/components/layout/nav/nav-academy.tsx
> MohammadH/ Show Academy nav when scrolling to the top

- src/pages/partners/payment-agent/_faq-data.tsx
- src/pages/partners/payment-agent/_faq.tsx
- src/pages/partners/payment-agent/_who-can-apply.tsx
- src/pages/partners/payment-agent/index.tsx
> Mitra/fix: :bug: hide p2p banner and faq in payment agent page

- src/pages/p2p/components/_numbers.tsx
> Mitra/fix: :bug: overflow text in button

- src/components/custom/_dhero-2.js
> Konstantinos / Bug - Deriv X page - platform buttons have overflowed from its expected clickable area

- src/components/elements/dropdown.js
- src/pages/trader-tools/common/_style.ts
- src/pages/trader-tools/pnl-for-margin/_pnl-margin-calculator.tsx
- src/pages/trader-tools/pnl-for-multipliers/_pnl_multipliers_calculator.tsx
> Konstantinos / Responsive issue Tradertools

- src/pages/help-centre/dbot.tsx
> Konstantinos /  Overflow issue in deriv.com/help-centre/ (Dbot section) on Android device 

- src/pages/markets/components/sections/_other-markets.tsx
> Konstantinos/ Overlap between the text and Learn more button for other languages on the Markets page 

- src/pages/regulatory/index.tsx
> Konstantinos/ fix text alignment inside regulatory page

- Dockerfile
- deriv.com.conf
Reverts binary-com/deriv-com#3503
> Revert "onik/deriv-com_pagespeed"

- src/components/form/wizard/footer.tsx
- src/components/form/wizard/header.tsx
- src/components/form/wizard/index.tsx
- src/components/form/wizard/stepper.tsx
> MohammadH/ Update wizard

- src/pages/deriv-go/index.tsx
> MohammadH/ Stop showing deriv-go page before 404 in eu

- src/pages/markets/components/sections/_other-markets.tsx
> MohammadH/ Fix other markets overlap in polish language

- src/components/elements/off-canvas-menu.js
- src/components/layout/footer/main-links.js
- src/components/layout/nav/components/partner/nav-partner-desktop.tsx
> MohammadH/ Hide payment-agent from nav in UK

- crowdin/messages.json
- src/pages/regulatory/_document_accordion.tsx
> MohammadH/ Update financial disclosure report for non-eu

- deriv.com.conf
> Mitra/fix: too many redirection error

- src/pages/partners/_partnership-opportunities.js
> Mitra/fix: show payment agent to row only

- src/pages/p2p/components/_numbers.tsx
> MohammadH/  Fix p2p button size in mobile

- src/components/custom/_dhero.js
- src/pages/dbot/index.tsx
> MohammadH/ Show dbot-image in dbot-page instead of dtrader-image

- src/pages/partners/_about-deriv.js
> Konstantinos / Title alignment issue in partners page

- src/pages/academy/components/search_banner/_topic-items-accordion.tsx
> MohammadH/ Fix academy topic arrow issue in mobile to expand only one item

- .github/workflows/content.yml
- .github/workflows/lint.yml
- .github/workflows/production.yml
- .github/workflows/staging.yml
- .github/workflows/translation-delete.yml
- .github/workflows/translation-push.yml
- .github/workflows/translation-sync.yml
- .github/workflows/translation.yml
-   Align CircleCI node version to project node version
The error:
> Use node 16 in CircleCI

- src/pages/home/platform-carousel/_mobile-platform-carousel.tsx
> Meenu/fix: fixed google play url for dmt5

- src/common/constants.ts
> Meenu/fix: web browser url updated

- src/components/form/wizard/index.tsx
- src/components/form/wizard/stepper.tsx
- src/pages/signup-affiliates/validations/_account-details.tsx
- src/pages/signup-affiliates/wizard.tsx
> chore: change wizard according to figma

- src/components/layout/nav/nav-careers.tsx
- src/pages/careers/_model/_locations/_locations.ts
> Konstantinos / Ciudad del Este Bug Fix

- src/pages/help-centre/_help-articles.tsx
- src/pages/help-centre/dmt5.tsx
- src/pages/help-centre/dtrader.tsx
> MohammadH/ Update help centre texts regarding derived changes

- src/pages/help-centre/_help-articles.tsx
- src/pages/help-centre/dmt5.tsx
- src/pages/help-centre/dtrader.tsx
Reverts binary-com/deriv-com#3591
> Revert "MohammadH/ Update help centre texts regarding derived changes"

- .storybook/main.ts
- .storybook/preview.tsx
- storybook.d.ts
Changes:
-   Convert storybook folder to ts
> NikitK/ Convert storybook folder to ts

- src/components/layout/nav/nav-careers.tsx
- src/pages/careers/_model/_locations/_locations.ts
> Konstantinos / [FE Deriv.com squad] Minsk office change Yandex to Google map 

- src/components/elements/off-canvas-menu.js
> MohammadH/ Fix npm start not working

- src/pages/careers/locations/minsk/index.tsx
- src/pages/responsible/_trading-limits.tsx
- src/pages/responsible/_trading-responsibly.tsx
- src/pages/responsible/index.tsx
- src/pages/terms-and-conditions/_clients-grid.tsx
> Mitra/fix: show missing components

- src/components/hooks/use-handle-signup.tsx
Changes:
-   change function and sign up path for whole app
> NikitK/ Create free demo account button navigating users to a errored url

- src/components/localization/localized-link.tsx
Changes:
-   remove disabled="" on element a
-   [ X ] Refactor code
> remove disabled="" on element a (old code), we dont use it anywhere.

- gatsby-browser.js
- gatsby-config.js
- gatsby-ssr.js
- src/pages/academy/components/_utility.ts
- src/pages/home/_what-our-clients-say.tsx
Changes:
-  changed the script loading strategy. There is almost no information on this experimental technology on the Internet, perhaps I added the strategy incorrectly.
-   [ X ] Improve performance
> add gatsby main off threads

- src/components/localization/language-dropdown.tsx
> Konstantinos / Fix Removal of Flags lint error

- src/components/elements/side-tab.js
> Shayan/76250/Help center question not showing up in development 

- .husky/pre-commit
- crowdin/messages.json
Changes:
-  revert back extract translation on pre-commit
> Mohsen / fix pre-commit extract translation keys

- src/pages/who-we-are/_data.tsx
> Konstantinos / [FE Deriv.com squad] [Offices] Add new office locations on the map on [Who we are] page /Cayman & Ciudad/ 

- src/components/layout/layout.js
> yashim/fix: add check before sending allow_tracking event

- src/pages/p2p/components/_dp2p.tsx
> Konstantinos / replace p2p video

- src/components/custom/other-platforms.tsx
- src/components/elements/card.tsx
> MohammadH/ Fix is_row not exist error

- src/components/elements/side-tab.tsx
> Mitra/ hotfix question link in help centre

- gatsby-ssr.js
> chore: remove vwo script

- .github/workflows/translation-push.yml
> Prince/ update translation push workflow sequence

- crowdin/messages.json
- src/components/layout/footer/main-links.tsx
- src/pages/home/_markets_fold.tsx
> chore: add derived url fix

- crowdin/messages.json
- src/components/layout/footer/main-links.tsx
- src/pages/home/_markets_fold.tsx
Reverts binary-com/deriv-com#3699
> Revert "chore: add derived url fix"

- src/common/constants.ts
> Mitra/fix: update the percentage

- src/components/localization/config.tsx
- src/pages/partners/affiliate-ib/_deriv-affiliate-programme.tsx
> chore: fix duplicate key

- src/common/constants.ts
- src/pages/careers/_model/_locations/_locations.ts
- src/pages/careers/_model/_locations/_locations.types.ts
- src/pages/careers/locations/_location-layout-new-offices.tsx
- src/pages/careers/locations/_location-layout.tsx
> Konstantinos / [FE Deriv.com squad] Careers > Locations > Change links for 'View open positions in <Location Name>' buttons for each Location.

- src/components/custom/_dhero-dmt5.js
Changes:
-   dmt5 hero space between components
> NikitK/ [FE Deriv.com squad] Deriv MT5 > Banner should be centered relative to the screen width

- crowdin/messages.json
- i18n-config.js
Changes:
-  Enable korean language
> yashim/feat: enable korean (한국어) language

- src/components/hooks/use-social-media-url.tsx
Changes:
-    add facebook link to hook to provide him in deriv.com
> NikitK/ Update Facebook link on deriv.com/es/

- src/pages/markets/static/content/_market-symbols.tsx
> Konstantinos / [FE Deriv.com squad] Change EUR currency logo to USD currency logo for Silver/USD in commodities market page for Options in ROW 

- src/components/layout/nav/nav-careers.tsx
> Meenu/fix: fix nav space in career header

- src/components/custom/_dhero-2.tsx
- src/components/custom/_dhero-dmt5.js
- src/components/custom/_dhero.tsx
- src/pages/dbot/index.tsx
- src/pages/dtrader/index.tsx
> Meenu/fix: added go to live demo button

- gatsby-config.js
> chore: add-sitemap

- src/components/custom/_dhero-2.tsx
- src/components/custom/_signup-public.tsx
> MohammadH/ Remove verbose code and use map for redundant items

- gatsby-config.js
- src/components/containers/seo.tsx
Reverts binary-com/deriv-com#3825
> Revert "Habib/site map"

- src/pages/markets/components/sub-markets/_multipliers.tsx
> Meenu/fix: added dbot under multipliers

- src/pages/deriv-go/_other-apps.tsx
> fix: fix staging

- .github/workflows/translation-sync.yml
> Prince/ update sync translation workflow

- src/components/hooks/use-country-rule.tsx
> fix: set default is loading to true

- src/components/elements/dot-loader.ts
> fix: vertical scrolling on home page

- src/pages/markets/components/sub-markets/_cfds.tsx
> Meenu/fix: added deriv x

- src/pages/help-centre/_article-section-component.tsx
> Meenu/fix: removed dbot from help center

- src/common/websocket/api.ts
Changes:
-    reload page if ws connection closed after user idle
> NikitK/ Connection lost when idled for few minutes

- gatsby-config.js
Changes:
-    canonical tag depends on row and eu domain of website
> NikitK/ [FE Deriv.com squad] Google search console SEO errors

- i18n-config.js
Changes:
-  force pt language for conference
> NikitK/ Force change language to PT when user inside

- src/components/localization/language-dropdown.tsx
> Niloofar Sadeghi / Unable to scroll in languages list

- src/pages/help-centre/components/_didnt-find-answer.tsx
> Niloofar Sadeghi / The Help Center page is displayed incorrectly on a mobile device when the AR language is selected

- src/common/constants.ts
- src/common/utility.ts
- src/components/localization/localized-link.tsx
> Konstantinos / [FE Deriv.com squad] Allow English for unavailable languages in SmartTrader url redirects from Primary Navigation

- .github/workflows/production.yml
(I jjust changed the source branch) 
Changes:
-   Do not cache build when doing a production release
> No cache when releasing to production

- src/pages/partners/affiliate-ib/_deriv-ib-programme.tsx
> Meenu/fix: spacing issue in affiliate page

- src/pages/academy/common/_constants.ts
> MohammadH/ Remove synthetics from Acadmey

- gatsby-config.js
> MohammadH/ Fix generating page by query params

- .github/workflows/translation-delete.yml
- .github/workflows/translation-pre-delete.yml
- .github/workflows/translation-pre-push.yml
- .github/workflows/translation-push.yml
> Prince/ translation workflow security mitigation

- src/components/layout/besquare/footer.tsx
- src/components/layout/besquare/style/footer.ts
>  change the date for besquare

- src/components/hooks/use-handle-signup.tsx
> Update variable name

- .github/workflows/translation-push.yml
> chore: fix transltion push yaml file

- src/pages/dmt5/components/_side-tab.tsx
> Niloofar Sadeghi / Responsive/Desktop: How to get started with Deriv MT5 account is broken [EU, non-EU]

- src/components/custom/_signup-new.tsx
> Niloofar Sadeghi / responsive: sign up page is broken on responsive [EU and non-EU]

- src/components/elements/typography.ts
> Niloofar Sadeghi / Contact us via live chat should be bold in https://staging.deriv.com/partners/affiliate-ib

- src/pages/home/_what-our-clients-say.tsx
> Niloofar Sadeghi / Design is affected in the 'What our clients say about Deriv' section in the home page in both Desktop and Mobile

- src/pages/home/_markets_fold.tsx
> MohammadH/ Fix markets carousel autoplay

- src/common/websocket/api.ts
- src/components/hooks/use-deriv-api.tsx
- updated use-deriv-api and connected it to i18next conetxt
- updated api.ts to get the lang for connection creation
Changes:
-   ...
> fix: ws connection lagnuage

- .github/workflows/translation-pre-push.yml
> Prince/ update translation workflow security

- .github/workflows/translation-pre-push.yml
> Prince/ Translation workflow extra condition

- .github/workflows/translation-sync.yml
> Prince/ update upload source to master

- src/pages/trader-tools/swap-calculator/_swap-calculator.tsx
> Fasih/ replace active symbol hook with usews for swap calc

- src/common/constants.ts
> MohammadH/ Update cfd loss percentage to 71

- .github/workflows/translation-delete.yml
- .github/workflows/translation-push.yml
- .github/workflows/translation-sync.yml
> Prince/ use lower version of crowdin cli

- src/components/layout/besquare/footer.tsx
- src/pages/careers/besquare/components/sections/_description.tsx
- src/pages/careers/besquare/components/sections/_why-deriv.tsx
- src/pages/careers/besquare/static/content/_advantages.ts
- src/pages/careers/besquare/static/content/_faq.tsx
- src/pages/careers/besquare/static/content/_join-us.tsx
- src/pages/careers/besquare/static/content/_what-is-besquare.ts
- src/pages/careers/besquare/static/content/_what-lies-ahead.ts
- src/pages/careers/besquare/static/content/_who-can-apply.ts
> Konstantinos / [FE Deriv.com squad]  Updating the BeSquare page

- src/pages/dmt5/_dbanner.tsx
> Konstantinos / Konstantinos / [Deriv X, RU language] “X” from the name "Deriv X" is transferred to a new line

- src/pages/careers/besquare/components/sections/_hero.tsx
> Konstantinos / BeSquare Title should come in same single line on BeSquare Page

- package-lock.json
- package.json
Reverts binary-com/deriv-com#4084
> Revert "Habib/fix vercel issue rebranding"

- package-lock.json
- package.json
> habib/update package-lock

- .github/workflows/content.yml
- .github/workflows/lint.yml
- .github/workflows/translation-delete.yml
- .github/workflows/translation-pre-delete.yml
- .github/workflows/translation-pre-push.yml
- .github/workflows/translation-push.yml
- .github/workflows/translation-sync.yml
- src/components/hooks/use-academy-data.tsx
> Prince/ update workflow permissions

- src/pages/help-centre/data/_deposits-and-withdrawals.ts
> Konstantinos / contact us via live chat hyperlink is taking user to wrong page

- src/pages/endpoint/index.tsx
- src/store/website-status-context.tsx
> Fasih/ removed legacy way to fetch data and used useWS to fetch data

- src/components/containers/number-section.tsx
- src/pages/dmt5/_numbers.tsx
> Konstantinos / Reusable component for number section  

- src/components/elements/common-header-section.tsx
- src/components/elements/full-width-multicolumn.tsx
- src/components/elements/stepper-view.tsx
- src/pages/home/live-pricing/components/_live_market_table.tsx
> Fix type and API issues

- src/pages/careers/_model/_locations/_contact-details.ts
- src/pages/careers/_model/_locations/_locations.ts
- src/pages/careers/_model/_locations/_locations.types.ts
- src/pages/careers/locations/_location-layout-new-offices.tsx
Changes:
-   ...
-   [ X ] Dependency update
> change locations text

- src/components/custom/_agreement-label.tsx
- src/components/custom/_signup-new.tsx
Changes:
-   Open Terms in new tab
> terms and condition in new tab

- src/pages/home/_hero.tsx
- src/pages/home/live-pricing/_types.ts
- src/pages/home/live-pricing/components/_live_market_table.tsx
- src/pages/trade-types/components/_style.ts
> Add error check on live market table and removal of black background

- .github/workflows/translation-delete.yml
- .github/workflows/translation-pre-delete.yml
- .github/workflows/translation-pre-push.yml
- .github/workflows/translation-push.yml
> Temp: Habib add translation support rebranding

- src/components/elements/full-width-multicolumn.tsx
> chore: update gap

- .github/workflows/translation-delete.yml
- .github/workflows/translation-pre-delete.yml
- .github/workflows/translation-pre-push.yml
- .github/workflows/translation-push.yml
Reverts binary-com/deriv-com#4179
> Revert "Temp: Habib add translation support rebranding"

- src/pages/signup-affiliates/components/_address-details.tsx
- src/pages/signup-affiliates/components/_personal-details.tsx
- src/pages/signup-affiliates/index.tsx
> MohammadH/ Cellxperts v2 fix store

- src/pages/trade-types/cfds/index.tsx
- src/pages/trader-tools/pnl-for-margin/_pnl-margin-calculator.tsx
Reverts binary-com/deriv-com#4154
> Revert "Yaswanth/87208/pnl margin bugfix"

- src/pages/trader-tools/pnl-for-margin/_pnl-margin-calculator.tsx
> refactor: to fix pnl margin calculator issue

- src/pages/dmt5/index.tsx
- src/pages/trader-tools/common/_utility.tsx
Reverts binary-com/deriv-com#4173
> Revert "Yaswanth/88385/pnl calculator console warning fix"

- src/pages/careers/_model/_locations/_locations.ts
> Konstantinos / [FE Deriv.com squad] Content changes need to be done on Locations pages.

- src/common/constants.ts
- src/common/utility.ts
- src/components/hooks/use-client-country.tsx
- src/components/layout/layout.tsx
- src/components/layout/location-context.tsx
- src/store/region-context.tsx
- src/store/website-status-context.tsx
> yashim/fix: speed up country checks

- src/pages/markets/components/helper/_symbol.tsx
> 89077 NikitK/ Switching on Market tabs breaks the page 

- src/common/utility.ts
> refactor: cleanup after academy movement

- src/components/layout/layout.tsx
- src/pages/endpoint/index.tsx
> Fix IP cookie issue loop for login

- src/components/elements/stepper-view.tsx
- src/pages/trade-types/components/_learn-more.tsx
- src/pages/trade-types/components/_style.ts
> Konstantinos / CFDs subtasks

- src/components/custom/_simple-steps.tsx
- src/pages/markets/components/sections/_other-markets.tsx
> Konstantinos / Commodities Subtasks

- crowdin/messages.json
- src/pages/markets/components/helper/_available-platforms.tsx
- src/pages/markets/components/sections/_hero_derived_fx.tsx
- src/pages/markets/components/sub-markets/_multipliers.tsx
> Konstantinos / Cryptocurrencies subtasks

- src/components/custom/_dhero.tsx
- src/components/custom/_hero-shape.tsx
- src/components/custom/_stepper_view.tsx
- src/components/custom/carousel/_markets-carousel.tsx
- src/components/custom/carousel/_platforms-carousel.tsx
- src/components/elements/carousel/carousel-style.ts
- src/pages/dtrader/_our-platforms.tsx
Reverts binary-com/deriv-com#4211
> Revert "Fasih /Pr 86506 rebrand dtrader page"

- crowdin/messages.json
- src/components/layout/footer/disclaimer.tsx
> Konstantinos / [EU] Footer content is displayed twice for EU clients

- src/pages/markets/components/sections/_nav-tab.tsx
- src/pages/markets/components/sections/_why-trade.tsx
Changes:
-    make TabList on market page responsive
> 89196 NikitK/The first letter of the word Synthetics and the last letter of the word Derived FX  are cut in responsive

- src/components/layout/layout.tsx
> yashim/fix: client country redirect check

- src/common/utility.ts
> Fix staging redirect

- src/components/layout/layout.tsx
Reverts binary-com/deriv-com#4258
> Revert "yashim/fix: client country redirect check"

- src/components/layout/layout.tsx
Reverts binary-com/deriv-com#4253
> Revert "yashim/fix: re-added eu redirection with updated logic"

- crowdin/messages.json
- src/components/custom/_signup-flat.tsx
- src/pages/markets/components/sections/_hero_derived_fx.tsx
> Konstantinos / Derived Subtasks part 2

- src/components/containers/box.tsx
- src/components/elements/full-width-multicolumn.tsx
- src/components/localization/localized-link.tsx
- src/pages/markets/components/markets/_forex.tsx
- src/pages/markets/components/sections/_hero_derived_fx.tsx
- src/pages/markets/components/sections/_other-markets.tsx
- src/pages/markets/static/style/_markets-style.tsx
> Konstantinos / Forex subtasks

- src/pages/markets/components/sections/_hero_derived_fx.tsx
> Konstantinos / Commodities subtasks part 2

- src/components/elements/full-width-multicolumn.tsx
- src/pages/markets/components/sections/_other-markets.tsx
> Konstantinos / Multipliers subtasks part 3

- src/components/layout/nav/components/partner/main-nav.tsx
- src/components/layout/nav/components/partner/nav-partner-mobile.tsx
> meenu/fix: fixed padding issue

- package-lock.json
- package.json
> refactor: update plugin

- gatsby-config.js
> GCM User ID issue fixed

- crowdin/messages.json
- scripts/extract-translations.js
- src/components/localization/config.tsx
- src/pages/404.tsx
- src/pages/index.tsx
- src/pages/our-principles/_data.tsx
- src/pages/our-principles/index.tsx
- preventing old approach to include new approach in extracted keys
Changes:
-   ...
> fix: updated translation key extraction

- src/store/region-context.tsx
> Mitra/ rely on eu domain to show eu content

- src/store/region-context.tsx
Reverts binary-com/deriv-com#4302
> Revert "Mitra/ rely on eu domain to show eu content"

- src/common/utility.ts
- src/components/layout/layout.tsx
Reverts binary-com/deriv-com#4226
> Revert "Mitra/ Remove redirection from client side"

- src/components/hooks/use-handle-login.tsx
> Remove EU popup

- src/components/hooks/use-handle-login.tsx
> chore: add logic

- src/components/hooks/use-auth-check.tsx
- src/pages/home/_hero.tsx
> Farhan Ahmad Nurzi / When logged in client goes to deriv.com page there is a glitch in the CTA button Get trading 

- src/common/utility.ts
- src/components/hooks/use-platform-query-param.tsx
- src/components/layout/nav/nav-markets.tsx
- src/pages/markets/components/sections/_hero_derived_fx.tsx
- src/pages/markets/components/sections/_nav-tab.tsx
> Farhan Ahmad Nurzi / Header is floating for all the markets page in deriv.com

- src/pages/payment-methods/_mobile-expanded-list.tsx
> Farhan Ahmad Nurzi / Bug - Responsive: Remove reference if no reference doc is available in payment methods

- src/components/custom/_signup-public.tsx
- src/components/elements/full-width-multicolumn.tsx
- src/components/form/input.tsx
- src/pages/markets/components/sections/_hero_derived_fx.tsx
- src/pages/trade-types/components/_markets-carousel.tsx
- src/pages/trade-types/components/_style.ts
- src/pages/trade-types/options/_how-options-works.tsx
> Konstantinos / Final rebranding fixes 2

- gatsby-browser.js
- src/common/utility.ts
- src/components/localization/language-switcher.tsx
> Konstantinos / Translation Rebrand Conflict

- gatsby-browser.js
Reverts binary-com/deriv-com#4349
> Revert "Test UTM"

- gatsby-browser.js
This reverts commit e5e5bb6fad12b7717edc6d566569a03165287ee5.
Changes:
-   ...
> Revert "MohammadH/ Test UTM (#4403)"

- src/pages/help-centre/data/_trading.ts
> Konstantinos /  Duplicate question

- deriv.com.conf
> Konstantinos / fix redirection

- gatsby-config.js
- package-lock.json
- package.json
Changes:
-   Enabled datadog in repository
-   Added datadog cred to github repository env vars
> Ako / datadog integration

- .github/workflows/production.yml
- .github/workflows/staging.yml
- Make the environment variables for Datadog RUM visible to gatsby build
> build: Pass Datadog Real User Monitoring Application ID and Client Token to gatsby build

- gatsby-config.js
Changes:
-   Just updated datadog env value to `production`
> Ako/ update Datadog env value

- gatsby-config.js
> Ako/ change replaySampleRate key to sessionReplaySampleRate

- src/common/utility.ts
- src/components/localization/language-switcher.tsx
> feat: storing selected language in cookies

- src/store/region-context.tsx
> MohammadH/ Remove is-eu-country

- gatsby-config.js
> Ako/ add clickmap experimental feature to gatsby

- gatsby-config.js
> Datadog update data from env

- gatsby-config.js
> chore: add frustration signals

- src/features/pages/home/our-platforms/sliders/platform-images/platform-image.item.tsx
- src/features/pages/home/our-platforms/sliders/platform-images/platform-images.module.scss
> fix: fixed font color of platform slider's image caption

- crowdin/messages.json
- src/features/components/molecules/nav-card/nav-card.module.scss
- src/features/components/templates/footer/data.ts
- src/features/components/templates/navigation/main-nav/content/market/index.ts
- src/features/pages/home/index.tsx
> Mitra/ fix subtasks for homepage

- crowdin/messages.json
- src/pages/payment-methods/_payment-data.tsx
> fix: payment-method-min-max was doubled for paysafecard

- src/features/styles/theme/flex.scss
> fix: flex css typos

- src/components/containers/box.tsx
- src/pages/help-centre/components/_search-section.tsx
Changes:
-   ...
-   [ X ] Refactor code
> reduce empty arrays

- .github/workflows/beta.yml
> chore: update memory allocation size github action

- .github/workflows/beta.yml
- src/components/layout/layout.tsx
- src/components/localization/locale-context.tsx
- src/features/components/templates/navigation/main-nav/content/market/index.ts
- src/features/styles/app.scss
- src/pages/markets/components/sections/_hero_derived_fx.tsx
- src/themes/global-style.ts
- src/themes/reset.ts
> chore: update styled component layout

- .github/workflows/beta.yml
> chore: update beta github action

- .github/workflows/lighthouse.yml
> Ako/ update lighthouse ci action to v9

- .github/workflows/lighthouse.yml
> Ako: update `runs` config on lighthouse

- .github/workflows/beta.yml
> chore: update github action

- src/features/pages/home/client-testimonial/index.tsx
- src/features/pages/home/client-testimonial/styles.module.scss
- src/features/pages/home/client-testimonial/trustpiolot-container/index.tsx
> fix: testimonial alignment

- src/common/constants.ts
> feat: update loose percentage

- gatsby-config.js
- package-lock.json
- package.json
> feat: gatsby-plugin-csp integration

- src/pages/partners/_deriv-numbers.tsx
> feat: PT partners deriv number box height

- gatsby-config.js
- package-lock.json
- package.json
Reverts binary-com/deriv-com#4500
> Revert "feat: gatsby-plugin-csp integration"

- gatsby-browser.js
- gatsby-config.js
- package-lock.json
- package.json
Changes:
Remove Gatsby Datadog Plugin, added native implementation
> Update plugin datadog

- gatsby-browser.js
- gatsby-config.js
- package-lock.json
- package.json
Reverts binary-com/deriv-com#4570
> Revert "Update plugin datadog"

- gatsby-browser.js
- gatsby-config.js
- package-lock.json
- package.json
Reverts binary-com/deriv-com#4579
> Revert "Habib/gatsby update original plugin 2"

- src/features/components/templates/navigation/bug-bounty-nav/bug-bounty-nav.module.scss
- src/features/components/templates/navigation/bug-bounty-nav/index.tsx
- src/features/components/templates/navigation/career-nav/career-nav.module.scss
- src/features/components/templates/navigation/career-nav/index.tsx
- src/features/components/templates/navigation/main-nav/index.tsx
- src/features/components/templates/navigation/main-nav/main-nav.module.scss
- src/features/components/templates/navigation/market-nav/index.tsx
- src/features/components/templates/navigation/market-nav/market-nav.module.scss
- src/features/components/templates/navigation/payment-agent-nav/index.tsx
- src/features/components/templates/navigation/payment-agent-nav/payment-agent-nav.module.scss
- src/features/components/templates/navigation/static-nav/index.tsx
- src/features/components/templates/navigation/static-nav/static-nav.module.scss
- src/features/components/templates/navigation/template/index.tsx
- src/features/components/templates/navigation/template/mobile-menu/index.tsx
- src/features/components/templates/navigation/template/mobile-menu/mobile-menu.module.scss
> chore: fix navigations logo size

- gatsby-ssr.js
- src/components/hooks/use-auth-check.tsx
- src/features/components/molecules/layout-overlay/index.tsx
- src/features/components/molecules/layout-overlay/live-chat-button/index.tsx
- src/features/components/molecules/layout-overlay/whats-app-button/index.tsx
- src/features/components/templates/layout/index.tsx
- src/features/pages/home/client-testimonial/trustpiolot-container/index.tsx
> chore: test new script loading

- gatsby-browser.js
> Update on client entry

- src/components/custom/_dnumbers.tsx
> fix: market stats alignment

- src/components/custom/_button.tsx
- src/components/custom/_dhero.tsx
> fix: hero button alignment in viI lang

- src/pages/dtrader/_steps_section.tsx
- src/translations/pl.json
> fix: easy steps broken btn in pl lang

- src/features/pages/home/our-platforms/sliders/platform-images/platform-images.module.scss
> chore: test px for iphones

- src/features/components/templates/signup/with-banner/index.tsx
- src/features/pages/home/client-testimonial/index.tsx
- src/features/pages/home/our-platforms/index.tsx
- src/features/pages/home/our-platforms/sliders/index.tsx
> chore: updated spacing

- src/features/components/molecules/nav-card/nav-card.module.scss
- src/features/components/templates/hero-banners/product/product-hero.module.scss
- src/features/components/templates/navigation/main-nav/main-nav-buttons/index.tsx
- src/features/components/templates/navigation/main-nav/main-nav.module.scss
- src/features/pages/home/hero/index.tsx
- src/features/pages/home/hero/slider/slider.module.scss
> chore: update homepage hero images

- gatsby-browser.js
> chore: update session replay

- gatsby-browser.js
Reverts binary-com/deriv-com#4604
> Revert "chore: update session replay"

- src/pages/careers/_model/_locations/_locations.ts
- src/pages/careers/besquare/components/helper/_card.tsx
- src/pages/careers/besquare/components/sections/_who-can-apply.tsx
- src/pages/careers/besquare/static/content/_advantages.ts
- src/pages/careers/besquare/static/content/_join-us.tsx
- src/pages/careers/besquare/static/content/_what-lies-ahead.ts
- src/pages/dmt5/_start-trader.tsx
- src/pages/markets/components/markets/_cryptocurrencies.tsx
> feat: missing image alts seo recommendation

- src/components/hooks/use-visible-content.tsx
- src/features/components/molecules/nav-card/nav-card.module.scss
- src/features/components/organisms/navigation/nav-sections-container/render-section-items.module.scss
- src/features/components/organisms/navigation/nav-sections-container/section-column.tsx
- src/features/components/templates/footer/disclaimer/data.tsx
- src/features/components/templates/footer/index.tsx
- src/features/components/templates/navigation/template/index.tsx
> chore: fixed footer alignment

- src/components/hooks/use-media-query.tsx
- src/features/components/atoms/link/index.tsx
- src/features/components/organisms/navigation/nav-card-items/index.tsx
- src/features/components/organisms/navigation/nav-sections-container/index.tsx
- src/features/components/organisms/navigation/nav-sections-container/section-column.tsx
- src/features/components/templates/navigation/main-nav/content/about/index.ts
- src/features/components/templates/navigation/main-nav/content/index.ts
- src/features/components/templates/navigation/main-nav/content/legal/index.ts
- src/features/components/templates/navigation/main-nav/content/market/index.ts
- src/features/components/templates/navigation/main-nav/content/partner/index.ts
- src/features/components/templates/navigation/main-nav/content/platform/index.ts
- src/features/components/templates/navigation/main-nav/content/resources/data.ts
- src/features/components/templates/navigation/payment-agent-nav/data.tsx
- src/features/components/templates/navigation/template/desktop-menu/desktop.items.tsx
- src/features/components/templates/navigation/template/desktop-menu/index.tsx
- src/features/components/templates/navigation/template/index.tsx
- src/features/components/templates/navigation/template/mobile-menu/index.tsx
- src/features/components/templates/navigation/template/mobile-menu/mobile.items.tsx
- src/features/components/templates/navigation/template/nav-context/index.tsx
- src/features/components/templates/navigation/template/nav-drop-items/index.tsx
- src/features/components/templates/navigation/template/nav-single-item/index.tsx
- src/features/components/templates/navigation/types.ts
- src/features/hooks/use-link-url/index.tsx
- src/features/pages/home/hero/content/hero-content.module.scss
- src/features/pages/home/hero/content/index.tsx
- src/themes/theme.breakpoints.ts
> chore: fix mobile menu scroll

- .github/workflows/beta.yml
- src/features/components/organisms/navigation/nav-card-items/index.tsx
- src/features/components/organisms/navigation/nav-sections-container/index.tsx
- src/features/components/templates/navigation/main-nav/content/resources/data.ts
- src/features/components/templates/navigation/template/mobile-menu/index.tsx
- src/features/components/templates/navigation/types.ts
> Update link component

- src/features/pages/home/our-platforms/data.tsx
- src/features/pages/home/our-platforms/sliders/platform-images/platform-image.item.tsx
- src/features/pages/home/our-platforms/sliders/platform-main/main-slider.item.tsx
- src/features/pages/home/trade-types/trade-type.item.tsx
> chore: updated font family

- crowdin/messages.json
- src/features/components/molecules/language-switcher/index.tsx
- src/features/components/templates/footer/disclaimer/index.tsx
- src/features/components/templates/footer/link-item/index.tsx
- src/features/components/templates/footer/links-column/index.tsx
- src/features/components/templates/navigation/career-nav/data.tsx
- src/features/pages/home/markets/index.tsx
- src/features/pages/home/markets/market-item/market-item.scss
- src/features/pages/home/markets/market-slider/index.tsx
- src/features/pages/home/markets/market-slider/market-slide.scss
- src/features/pages/home/trade-types/trade-type.item.tsx
- src/features/styles/theme/containers.scss
> chore: updated spaces and fontsizes

- src/features/components/templates/footer/footer-icons/index.tsx
- src/features/components/templates/footer/social-icons/index.tsx
- src/features/pages/home/markets/market-slider/market-slide.scss
> chore: markets carousel flex center

- crowdin/messages.json
- src/features/components/templates/footer/disclaimer/data.tsx
- src/features/components/templates/signup/with-banner/form/index.tsx
- src/features/styles/theme/buttons.scss
> Translation issue

- src/features/components/molecules/language-switcher/useLangSwitcher.tsx
> Fix lang bar issue

- package-lock.json
- package.json
> chore: added needed stylelint package

- src/components/elements/market-tab/index.tsx
- src/features/components/atoms/link/index.tsx
- src/features/components/templates/footer/disclaimer/data.tsx
- src/features/components/templates/navigation/template/desktop-menu/styles.scss
- src/features/components/templates/navigation/template/nav-single-item/index.tsx
- src/pages/trading-specification/components/_available-platform.tsx
- src/pages/trading-specification/index.tsx
> Fix partners nav

- src/common/utility.ts
- src/components/localization/language-switcher.tsx
- src/pages/landing/ebooks/components/_get-ebook.tsx
> MohammadH/ Fix 404 in non-english ebooks page

- src/components/custom/_stepper_view.tsx
- src/pages/deriv-go/_start-deriv-go.tsx
> fix: fixed spacing issues

- src/features/components/atoms/link/index.tsx
- src/features/components/atoms/link/internal.tsx
> chore: fix link issues

- src/components/hooks/use-social-media-url.tsx
> Konstantinos / Arabic Social media links

- src/pages/careers/_dept-layout-components/_department-page.tsx
- src/pages/careers/_dept-layout-components/_dept-layout.types.ts
- src/pages/careers/_dept-layout-components/_hero.tsx
> Konstantinos / Careers remove open positions

- src/common/utility.ts
- src/components/localization/language-switcher.tsx
- src/pages/landing/ebooks/components/_get-ebook.tsx
Reverts binary-com/deriv-com#4508
> Revert "MohammadH/ Fix 404 in non-english ebooks page"

- src/common/websocket/index.ts
- src/features/components/atoms/link/index.tsx
- src/features/components/atoms/link/internal.tsx
> chore: fixed websocket connection with two layouts

- src/features/components/atoms/link/external.tsx
- src/features/components/atoms/link/index.tsx
- src/features/components/atoms/link/internal.tsx
> chore: fix ssr issue on build

- src/components/layout/footer/disclaimer.tsx
- src/pages/home/_trade.tsx
- src/pages/interim/faq/_faq-data.tsx
- src/pages/markets/components/helper/_available-trades_desktop.tsx
- src/pages/regulatory/_financial_commission.tsx
- src/pages/responsible/_trading-limits.tsx
- src/pages/responsible/_trading-responsibly.tsx
- src/pages/responsible/index.tsx
- src/pages/terms-and-conditions/_clients-grid.tsx
- src/store/region-context.tsx
- src/types/generics.ts
Reverts binary-com/deriv-com#4550
> Revert "Ashraf/90799"

- gatsby-browser.js
- gatsby-config.js
Changes:
- disallow search engines indexing
- update datadog config to beta.deriv.com
> chore: update setup config

- gatsby-config.js
> fix: possibility to fetch draft statement

- gatsby-config.js
> Sync with bff-strapi-cloud branch

- src/common/websocket/config.ts
> chore: update app id to production for beta

- gatsby-config.js
Reverts binary-com/deriv-com#4688
> Revert "Sync with bff-strapi-cloud branch"

- gatsby-config.js
Reverts binary-com/deriv-com#4691
> Revert "Revert "Sync with bff-strapi-cloud branch""

- gatsby-config.js
Reverts binary-com/deriv-com#4692
> Revert "Revert "Revert "Sync with bff-strapi-cloud branch"""

- gatsby-config.js
Reverts binary-com/deriv-com#4687
> Revert "fix: possibility to fetch draft statement"

- src/features/components/molecules/layout-overlay/cfd-warning-banner/index.tsx
> Translation-beta Loss percent build issue

- src/pages/trading-specification/_use-trading-spec-columns.tsx
Reverts binary-com/deriv-com#4718
> Revert "Habib/update tootltip content"

- src/pages/trading-specification/_use-trading-spec-columns.tsx
> Update the component for tooltip

- .github/workflows/staging.yml
> chore: update node options

- crowdin/messages.json
- src/pages/dmt5/_interest_free_trading.tsx
> fix: :bug: change zero interest to zero commission

- src/features/components/templates/navigation/bug-bounty-nav/index.tsx
- src/pages/bug-bounty/_submit_a_bug_report.tsx
> update bug bounty link

- src/pages/p2p/index.tsx
> adding loader && fixing incorrect rendering

- src/pages/help-centre/index.tsx
> fix: p2p load issue in help center page

- src/features/components/templates/navigation/template/desktop-menu/desktop.items.tsx
> Hasan/fix: navigation issue on touch device

- src/features/components/templates/footer/disclaimer/index.tsx
> Hasan/fix: footer disclaimer loading issue

- src/pages/signup-success/index.tsx
> fix: signup issue

- src/features/components/templates/navigation/market-nav/index.tsx
- src/features/components/templates/navigation/template/index.tsx
- src/features/components/templates/navigation/template/nav.template.module.scss
- src/pages/markets/components/sections/_hero_derived_fx.tsx
> Konstantinos / Hotfix remove nav

- src/common/utility.ts
> Fasih/: fix career page redirection

- src/features/components/templates/footer/social-icons/index.tsx
> Fasih/ fix career page footer issue

- .github/workflows/production.yml
> Update node options for prod

- gatsby-browser.js
> chore: update config

- gatsby-config.js
- src/components/containers/seo.tsx
> yashim/fix: language filter

- .github/workflows/beta.yml
- .github/workflows/production.yml
- i18n-config.js
- src/common/websocket/config.ts
> Remove crowdin from staging

- gatsby-browser.js
> chore: update datadog version

- .github/workflows/staging.yml
> yashim/chore: temporarily disable k8s workflow

- .github/workflows/staging.yml
> yashim/chore: updated staging runner config

- .github/workflows/staging.yml
Reverts binary-com/deriv-com#4800
> Revert "yashim/chore: temporarily disable k8s workflow"

- src/features/components/templates/signup/with-banner/form/index.tsx
> Fasih/: fix cross issue on signup banner

- gatsby-config.js
> chore: allow pages for robots.txt

- src/features/components/templates/signup/with-banner/form/index.tsx
Reverts binary-com/deriv-com#4778
> Revert "Fasih/: fix cross issue on signup banner"

- src/features/components/templates/footer/social-icons/data.ts
- src/features/styles/theme/alert.scss
Reverts binary-com/deriv-com#4799
> Revert "Mitra/show eu pop for youtube and linkedin"

- src/features/components/templates/footer/social-icons/data.ts
- src/features/styles/theme/alert.scss
Reverts binary-com/deriv-com#4817
> Revert "Revert "Mitra/show eu pop for youtube and linkedin""

- src/features/components/templates/signup/with-banner/form/index.tsx
Reverts binary-com/deriv-com#4816
> Revert "Revert "Fasih/: fix cross issue on signup banner""

- .github/workflows/staging.yml
> Add ubuntu latest

- .github/workflows/staging.yml
> Increase core for staging build

- .github/workflows/staging.yml
Reverts binary-com/deriv-com#4827
> Revert "Increase core for staging build"

- .github/workflows/staging.yml
> chore: increase core for staging build

- .github/workflows/lighthouse.yml
> Lighthouse workflow update

- .github/workflows/staging.yml
> Add version file to staging workflow

- .github/workflows/lighthouse.yml
> Prince/ Update lighthouse.yml

- .github/workflows/lighthouse.yml
> Prince/Update lighthouse.yml with alerts

- .github/workflows/lighthouse.yml
> Prince/ added condition to send lighthouse automessage

- src/features/components/templates/navigation/bug-bounty-nav/index.tsx
> Konstantinos / Broken link fix

- .github/CODEOWNERS
> Add new codeowners

- .github/workflows/lighthouse.yml
> Dump lighthouse output

- .github/workflows/lighthouse.yml
> Lighthouse Alert - Full report included

- .github/workflows/lighthouse.yml
> Remove Lighthouse Dump

- .github/workflows/staging.yml
- .github/workflows/stale.yml
Reverts binary-com/deriv-com#4883
> Revert "Reorder staging build GitHub action"

- .github/workflows/staging.yml
> Split staging workflow

- .github/workflows/staging.yml
> Comment out version

- gatsby-config.js
> Cache gatsby sharp image

- .github/workflows/staging.yml
> chore: revert to old

- .github/workflows/stale.yml
> chore: decrease PR stale days and closure days

- .github/workflows/stale.yml
> chore: udpated number of operations in stale pr action

- .github/workflows/staging.yml
> Split staging deploy

- .github/workflows/staging.yml
Reverts binary-com/deriv-com#4906
> Revert "Split staging deploy"

- .github/workflows/staging.yml
Reverts binary-com/deriv-com#4907
> Revert "Revert "Split staging deploy""

- .github/workflows/staging.yml
> chore: update data

- .github/workflows/staging.yml
> Remove kubernetes

- src/pages/trade-types/cfds/_available-markets.tsx
- src/pages/trade-types/multiplier/_markets-available.tsx
- src/pages/trade-types/options/_markets-available.tsx
> fix: cfd card's height and icon

- src/components/custom/_dhero.tsx
- src/pages/dbot/_hero.tsx
> Konstantinos / Fix color hover

- src/pages/dbot/_hero.tsx
> Konstantinos/  button gap dbot fix

- .github/workflows/staging.yml
> Update runner name

- .github/workflows/staging.yml
> Add k8 deploy

- crowdin/messages.json
- src/features/components/templates/navigation/template/market-bottom-nav/data.ts
> Konstantinos/ Fix stock

- .github/workflows/production.yml
> Update cpu core for production release

- src/pages/markets/components/helper/_available-trades_desktop.tsx
> fix: space issue on staging commodities

- src/pages/markets/components/helper/_available-trades_desktop.tsx
> MohammadH/ Fix scroll to top in mobile while tab change

- .github/workflows/beta.yml
> Update beta env to production

- .github/workflows/staging.yml
> Updating staging env for strapi

- .github/workflows/staging.yml
- gatsby-config.js
- package.json
- src/features/components/molecules/layout-overlay/cfd-warning-banner/index.tsx
- src/pages/404.tsx
- src/pages/who-we-are/index.tsx
> strapi build variable and cfd banner

- .github/workflows/staging.yml
- gatsby-config.js
- package.json
- src/features/components/molecules/layout-overlay/cfd-warning-banner/index.tsx
- src/pages/404.tsx
- src/pages/who-we-are/index.tsx
Reverts binary-com/deriv-com#4948
> Revert "strapi build variable and cfd banner"

- .github/workflows/staging.yml
Reverts binary-com/deriv-com#4947
> Revert "Updating staging env for strapi"

- src/features/components/molecules/language-switcher/index.tsx
> fix: language switcher issue in android firefox

- src/pages/markets/components/sections/_hero_derived_fx.tsx
> Fasih/: fix blur shade issue on market pages

- static/security.txt
Changes:
-   ...
-   [ X ] New feature
> add hackerOne Security file

- src/features/pages/home/our-platforms/sliders/platform-images/index.tsx
> Hasan/feat: increase platform slider's autoplay time

- gatsby-config.js
Changes:
-   ...
-   [ X ] New feature
> gatsby-offline-plugin

- gatsby-browser.js
> Farhan Ahmad Nurzi / Track Js error :Cannot read properties of null (reading 'result') 

- gatsby-config.js
> Eduard deriv/test offline bff

- gatsby-config.js
Reverts binary-com/deriv-com#4978
> Revert "test"

- gatsby-config.js
Reverts binary-com/deriv-com#4853
> Revert "gatsby-offline-plugin"

- src/pages/trading-specification/components/_elements.tsx
> fix: fix icon alignment

- gatsby-browser.js
> fix: scroll on new tab

- gatsby-config.js
> Eduard deriv/test1 offline

- src/common/constants.ts
> fix: map api key updated

- .github/workflows/beta.yml
> chore: remove linter

- gatsby-browser.js
- src/common/websocket/config.ts
> chore: add service worker

- gatsby-config.js
- static/pushwoosh-service-worker.js
> chore: concat sw

- gatsby-config.js
> chore: add new pages offline support

- src/components/localization/language-switcher.tsx
Changes:
-   Disable pt from language switcher
> yashim/chore: disable pt from language switcher

- i18n-config.js
Changes:
-   Disabled pt from config file
> yashim/chore: disabled pt from config file

- gatsby-node.js
> chore: update language path

- gatsby-node.js
Reverts binary-com/deriv-com#5032
> Revert "chore: update language path"

- gatsby-node.js
- src/common/utility.ts
- src/components/localization/language-switcher.tsx
- src/features/components/molecules/language-switcher/useLangSwitcher.tsx
Reverts binary-com/deriv-com#5035
> Revert "Habib/redirection pt path"

- src/common/utility.ts
- src/components/localization/language-switcher.tsx
- src/features/components/molecules/language-switcher/useLangSwitcher.tsx
> fix: added temp fix for pt redirection

- src/components/localization/language-switcher.tsx
- src/features/components/molecules/language-switcher/useLangSwitcher.tsx
> chore: update ach array

- i18n-config.js
> chore: remove pt

- src/components/localization/language-switcher.tsx
- src/features/components/molecules/language-switcher/useLangSwitcher.tsx
> Fasih//: fix redirection issue

- i18n-config.js
Reverts binary-com/deriv-com#5038
> Revert "chore: remove pt"

- gatsby-config.js
- package-lock.json
- package.json
> Fix font issue yellowlabs

- gatsby-config.js
- package-lock.json
- package.json
Reverts binary-com/deriv-com#5045
> Revert "Fix font issue yellowlabs"

- .github/workflows/beta.yml
- static/security.txt
> Update beta workflow and security text date

- gatsby-browser.js
- gatsby-config.js
- src/common/websocket/config.ts
> Gatsby plugin service worker issue fix

- src/features/pages/home/trade-types/data.tsx
Changes:
-   ...
-   [ X ] Update feature
> fix trade types

- src/common/websocket/index.ts
- src/features/components/molecules/language-switcher/useLangSwitcher.tsx
Changes:
- on language change the websocket connection will be recreated with correct language
> fix: update websocket language

- src/features/components/templates/signup/with-banner/banner/banner.styles.scss
- src/features/components/templates/signup/with-banner/banner/index.tsx
> Fasih/: fix signup banner mobile image alignment issue

- crowdin/messages.json
- gatsby-browser.js
> Pushwoosh-fix

- crowdin/messages.json
- gatsby-browser.js
Reverts binary-com/deriv-com#5086
> Revert "Pushwoosh-fix"

- src/pushwoosh-service-worker.js
> Aadd logic for checking pushwoosh registered

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5090
> Revert "Aadd logic for checking pushwoosh registered"

- gatsby-browser.js
- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5092
> Revert "Habib/cache clean mode sw"

- src/pushwoosh-service-worker.js
> Add logic to pw sw

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5094
> Revert "Add logic to pw sw"

- src/pushwoosh-service-worker.js
> Check pw only

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5096
> Revert "Check pw only"

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5099
> Revert "Habib/check pw cache clean"

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5101
> Revert "Habib/investigate sw"

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5103
> Revert "Habib/pw sw logic change"

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5105
> Revert "Habib/sw based on state"

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5107
> Revert "Habib/sw based on state redundant"

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5109
> Revert "Habib/sw based response"

- src/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5111
> Revert "Habib/check activated worker"

- crowdin/messages.json
- src/pages/deriv-go/_footer-banner.tsx
- src/pages/derivx/_get-derivx.tsx
> Konstantinos / change text description

- crowdin/messages.json
- src/components/custom/_banner-alert.tsx
> Konstantinos / Cookies overlap widgets

- crowdin/messages.json
- src/components/hooks/use-cookie-banner.ts
> Fasih/ refactor event code

- src/features/components/templates/signup/with-banner/index.tsx
- src/features/components/templates/signup/with-banner/with_banner.module.scss
> Fasih/: fix width

- gatsby-browser.js
- gatsby-config.js
> fix: habib/pushwoosh-sw-error-fix

- gatsby-browser.js
- gatsby-config.js
Reverts binary-com/deriv-com#5159
> Revert "fix: habib/pushwoosh-sw-error-fix"

- gatsby-browser.js
- gatsby-config.js
Reverts binary-com/deriv-com#5162
> Revert "Habib/sw removal add"

- gatsby-config.js
- static/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5164
> Revert "Habib/remove removal ofsw plugin"

- gatsby-config.js
- package-lock.json
- package.json
- static/pushwoosh-service-worker.js
> fix: remove sw plugins

- gatsby-config.js
- package-lock.json
- package.json
- static/pushwoosh-service-worker.js
Reverts binary-com/deriv-com#5166
> Revert "fix: remove sw plugins"

- src/pages/404.tsx
> Hasan/fix: 404 redirection issue

- crowdin/messages.json
- src/components/elements/full-width-multicolumn.tsx
- src/features/components/organisms/markets/market-banner/banner-text.tsx
- src/features/components/organisms/markets/market-banner/market-wrapper.tsx
- src/features/components/organisms/markets/market-banner/styles.module.scss
- src/pages/markets/components/sections/_hero_derived_fx.tsx
> Konstantinos / Arabic markets pages issues

- src/common/constants.ts
> chore: :page_facing_up: update cfd loss percentage

- src/common/utility.ts
- src/store/region-context.tsx
> fix: p2p cookie issue

- src/features/styles/reset.scss
> Hasan/fix: removed smooth scroll css

- src/features/styles/theme/accordion/styles.scss
> Hasan/fix: accordion shadow css

- src/components/elements/full-width-multicolumn.tsx
> Niloofar Sadeghi / Translation Refactoring Is Breaking For Non-EN Language

- src/features/hooks/use-signup-form/index.tsx
> MohammadH/ Add gclid to signup url parameters

- src/features/hooks/use-signup-form/index.tsx
Reverts binary-com/deriv-com#4942
> Revert "MohammadH/ Add gclid to signup url parameters"

- src/pages/markets/components/helper/_available-trades_desktop.tsx
> fix: active tab issue

- .github/workflows/beta.yml
- .github/workflows/production.yml
- .github/workflows/staging.yml
- src/common/constants.ts
> Add map api key from env

- src/features/components/molecules/language-switcher/index.tsx
- src/pages/trading-specification/components/_elements.tsx
> fix: scrolling issue and repetitive style tag

- src/features/hooks/use-signup-form/index.tsx
> Add gclid to signup url parameters

- src/features/components/molecules/slide-show/index.tsx
- src/features/components/molecules/slide-show/slide-show.module.scss
- src/features/pages/home/hero/index.tsx
- src/features/pages/home/hero/slider/index.tsx
- src/features/pages/home/our-platforms/data.tsx
> Fasih/ normal JS slideShow

- src/features/pages/home/hero/content/hero-content.module.scss
- src/features/pages/home/hero/content/hero-features.carousel.tsx
> Typewriter effects in css

- src/features/pages/home/hero/content/hero-content.module.scss
- src/features/pages/home/hero/content/hero-features.carousel.tsx
Reverts binary-com/deriv-com#5238
> Revert "Typewriter effects in css"

- src/features/components/organisms/available-options/tab-items.tsx
- src/features/components/templates/navigation/tab-nav-without-border/index.tsx
- src/features/components/templates/navigation/tab-nav-without-border/styles.scss
> fix: active link

- .github/workflows/corewebvitals.yml
> Datadog core web vitals

- src/features/components/organisms/available-options/tab-items.tsx
- src/features/components/templates/navigation/tab-nav-without-border/index.tsx
> fix: small issue in tabs

- .github/workflows/staging.yml
> update node version to 18

- src/features/pages/home/hero/content/hero-features.carousel.tsx
- src/features/pages/home/hero/slider/index.tsx
- src/features/pages/home/our-platforms/data.tsx
> Fasih/: fix font family and image formate

- src/features/components/templates/start-trading/index.tsx
- src/features/components/templates/start-trading/style.module.scss
- src/features/components/templates/why-trade-options/index.tsx
- src/features/components/templates/why-trade-options/styles.module.scss
> Hasan/fix: containers width

- src/components/layout/layout.tsx
- src/pages/reset-password/index.tsx
> Fasih/: fix extra spacing

- src/common/constants.ts
> update mt5 link

- src/features/components/templates/navigation/tab-nav-without-border/index.tsx
- src/features/components/templates/navigation/tab-nav-without-border/styles.module.scss
> fix: mobile tab flickering

- src/common/constants.ts
Reverts binary-com/deriv-com#5293
> Revert "update mt5 link"

- src/components/layout/layout.tsx
- src/pages/reset-password/index.tsx
Reverts binary-com/deriv-com#5280
> Revert "Fasih/: fix extra spacing"

- .github/workflows/staging.yml
Reverts binary-com/deriv-com#5263
> Revert "update node version to 18"

- src/features/components/organisms/available-markets-platforms/available-list.tsx
> Aswathy/fix: responsive issues for the options page

- src/common/constants.ts
Reverts binary-com/deriv-com#5304
> Revert "Revert "update mt5 link""

- src/pages/help-centre/components/_talk-to-us.tsx
> Aswathy/fix: alignment issue for mobile

- src/features/components/organisms/available-markets-platforms/available-list.tsx
- src/features/components/organisms/available-markets-platforms/index.tsx
- src/features/components/organisms/available-markets-platforms/styles.module.scss
- src/features/components/templates/options-content/index.tsx
- src/features/components/templates/options-content/styles.module.scss
- src/features/components/templates/options-faq/styles.module.scss
- src/features/components/templates/start-trading/style.module.scss
> fix: aligment issue

- src/features/components/molecules/timeline-item/index.tsx
- src/features/components/molecules/timeline-item/style.module.scss
> fix: timeline img alignment fix

- src/features/components/organisms/available-markets-platforms/index.tsx
- src/features/components/templates/options-content/index.tsx
- src/features/components/templates/start-trading/index.tsx
- src/features/pages/options/accumulator/index.tsx
> fix: spacing issue

- src/features/components/templates/navigation/tab-nav-without-border/index.tsx
- src/features/components/templates/navigation/tab-nav-without-border/styles.module.scss
> Hasan/fix: swiper button issue for galaxy a12

- .github/workflows/lighthouse.yml
> Prince/ turn off lighthouse warnings

- src/features/pages/options/digital/asians/index.tsx
- src/features/pages/options/digital/digits/index.tsx
- src/features/pages/options/digital/high-low/index.tsx
- src/features/pages/options/digital/in-out/index.tsx
- src/features/pages/options/digital/lookbacks/index.tsx
- src/features/pages/options/digital/only-ups-only-downs/index.tsx
- src/features/pages/options/digital/reset-call/index.tsx
- src/features/pages/options/digital/touch-no-touch/index.tsx
- src/features/pages/options/digital/up-down/index.tsx
> fix: :bug: show 404 to eu on option page

- src/features/components/organisms/available-markets-platforms/index.tsx
- src/features/components/templates/options-faq/index.tsx
> fix: alignment issue

- crowdin/messages.json
- src/components/layout/layout.tsx
- src/features/pages/signup-success/index.tsx
- src/features/pages/signup/index.tsx
> Fasih/: :bug  added option to show footer

- src/features/components/templates/signup/with-banner/form/index.tsx
> fix: signup error message overlap

- src/components/form/input.tsx
- src/pages/reset-password/index.tsx
> Meenu reset password page email field

- README.md
> chore: empty commit

- README.md
> Test release beta

- .github/workflows/beta.yml
> downgrade node version

- .github/workflows/beta.yml
> beta: downgrade node version

- .github/workflows/beta.yml
Reverts binary-com/deriv-com#5361
> Revert "beta: downgrade node version"

- package-lock.json
> Prince/revert: package-lock accidental change

- .github/workflows/beta.yml
- package-lock.json
> Prince/ revert: package-lock accidental change

- src/features/components/templates/options-content/section-content-option.item.tsx
- src/features/components/templates/options-content/single-content-option.item.tsx
> refactor: pr comments

- README.md
> chore: test commit

- gatsby-config.js
> Add Image cache true

- gatsby-config.js
Reverts binary-com/deriv-com#5383
> Revert "Add Image cache true"

- gatsby-config.js
This reverts commit 1673c1fdd8bcfa09aa2be60e9564db69c78ac165.
Changes:
-   ...
> Revert "chore: add trace SVG (#5391)"

- gatsby-config.js
Reverts binary-com/deriv-com#5402
> Revert "Habib/trace svg images"

- gatsby-config.js
> chore: add cached file type

- gatsby-config.js
Reverts binary-com/deriv-com#5407
> Revert "chore: add cached file type"

- src/features/components/atoms/tab/tab-switcher/tab-switcher.module.scss
> chore: :bug: fix delay on making font bold in tab

- src/features/components/templates/options-faq/index.tsx
> Hasan/fix: options faq heading alignment

- crowdin/messages.json
- src/components/custom/_simple-steps.tsx
- src/pages/markets/components/markets/_synthetic-indices.tsx
- src/pages/markets/components/sections/_hero_derived_fx.tsx
> Konstantinos /  Derived page - Hide sign up CTA buttons for Deriv GO users

- src/features/styles/theme/table.scss
> Fasih/: fix table td line hight

- src/features/pages/partners/deriv-prime/why-deriv-prime/index.tsx
> Konstantinos / Box height

- src/features/pages/options/vanilla/index.tsx
> Hasan/feat: remove demo text from vanilla

- src/components/containers/seo.tsx
> seo logo update

- .github/CODEOWNERS
> Update forks setting test PR

- src/features/pages/partners/deriv-prime/browse-our-faq/_faq-schema.ts
Changes:
- we had incorrect question for one of the answers in faq schema 🐞 
> chore: :bug: add the question to faq schema

- src/features/pages/partners/deriv-prime/get-in-touch/contact-form.tsx
> fix: text change ios

- src/features/components/atoms/card/card-primary/index.tsx
> Fasih/: fixed font size issue

- src/features/components/templates/navigation/payment-agent-nav/index.tsx
> Hasan/fix: deriv prime back button

- src/features/components/molecules/layout-overlay/index.tsx
> Konstantinos / Floating disclaimer is not appearing for non-eng languages

- i18n-config.js
> Konstantinos / Add sinhalese

- .github/workflows/build-to-cloudflare-pages.yml
Changes:
-   CF pages for test build
> chore: add env to cf deploy

- .github/workflows/build-to-cloudflare-pages.yml
Reverts binary-com/deriv-com#5554
> Revert "chore: add env to cf deploy"

- .github/workflows/build-to-cloudflare-pages.yml
> Cf wrangler for build

- .github/workflows/build-to-cloudflare-pages.yml
Reverts binary-com/deriv-com#5557
> Revert "Cf wrangler for build"

- .github/workflows/beta.yml
- README.md
> Test beta build

- .github/workflows/build-to-cloudflare-pages.yml
> chore: upload cf deploy

- .github/workflows/build-to-cloudflare-pages.yml
> chore: add env

- .github/workflows/build-to-cloudflare-pages.yml
> Add permission

- .github/workflows/build-to-cloudflare-pages.yml
> Update wrangler command

- .github/workflows/build-to-cloudflare-pages.yml
> Update project name

- .github/workflows/build-to-cloudflare-pages.yml
> fix: branch

- .github/workflows/build-to-cloudflare-pages.yml
> wrangler command fix

- .github/workflows/build-to-cloudflare-pages.yml
Reverts binary-com/deriv-com#5588
> Revert "Update workflow"

- package.json
Changes:
-   Update Build command for Gatsby
> Update gatsby package cmd

- .github/workflows/build-to-cloudflare-pages.yml
Changes:
-   Update CF workdflow
> chore: update cf workflow

- package.json
Reverts binary-com/deriv-com#5591
> Revert "Update gatsby package cmd"

- src/components/elements/dropdown.tsx
- src/features/pages/ctrader-signup/ctrader-credentials-form.tsx
- src/pages/trader-tools/margin-calculator/_margin-calculator.tsx
Changes:
Fix contract size placment
-   ...
> fix: fix position of text

- src/features/components/templates/footer/data.ts
- src/features/components/templates/navigation/main-nav/content/resources/data.ts
> Hasan/fix: blog link

- src/features/hooks/analytic/use-growthbook/index.ts
> growthbook without env variable broke the app

- src/components/custom/carousel/_platforms-carousel.tsx
- src/features/components/templates/signup/with-banner/banner/index.tsx
- src/features/components/templates/signup/with-banner/social/index.tsx
- src/features/components/templates/tabs/menu/index.tsx
- src/features/pages/home/trade-types/trade-type.item.tsx
Changes:
-   Add missing Alt tags
> fix: alt tag fix

- src/pages/why-choose-us/_africa-forex-award.tsx
Changes:
-  Fix the responsive issue for the width and margin of the Forex award in https://deriv.com/why-choose-us/ page
> fix: :ambulance: fix forex award for africa issue

- README.md
Reverts binary-com/deriv-com#5659
> Revert "add space"

- .github/workflows/beta.yml
> Aswathy/fix: updated wrangler

- gatsby-browser.js
- src/common/utility.ts
Changes:
-   Add deriv-com-preview-links.pages.dev to domain check
> Add deriv-com-preview-links.pages.dev to domain check

- crowdin/messages.json
- src/pages/help-centre/data/_account.ts
Changes:
-   Change of email FAQ content for EU should be the same as deriv.com
> text: update can i change my email address for eu help center

- src/pages/who-we-are/components/_hero.tsx
- src/pages/who-we-are/index.tsx
Changes:
-  Update image section with logic for strapi, if the image is not present in Strapi, it should not show in website
> Update image section with logic for strapi

- src/pages/trade-types/cfds/_mind-when-trading.tsx
- src/pages/trade-types/cfds/_start-trading.tsx
- src/pages/trade-types/cfds/_trading-cfd-increases.tsx
- src/pages/trade-types/multiplier/_start-trading.tsx
> Konstantinos / Translations for some texts are pending

- .github/workflows/generate-preview-link.yml
Changes:
-   Fix CF branch name regex
> Bala/ CF branch name regex

- src/features/components/templates/navigation/template/desktop-menu/styles.scss
Changes:
-   fixed having issue on big screen which the menu is full height due to 100%vh set
> fix: :bug: fix full height issue for menu

- .github/workflows/generate-preview-link.yml
Changes:
-   ...
-   [ x] Script configuration
> baseurl parameter change

- .github/workflows/generate-preview-link.yml
> Add PR and Repo to Test Run Info

- .github/workflows/generate-preview-link.yml
Changes:
-   PR issue number through to Cypress Cloud
-   [ x] Script configuration
> Send PR issue number through to Cypress Cloud

- gatsby-browser.js
- src/features/components/templates/navigation/template/index.tsx
Changes:
-  Homepage's hero image flickering issue onload
> Hasan/fix: hero image flickering

- gatsby-browser.js
- src/features/components/templates/navigation/template/index.tsx
Reverts binary-com/deriv-com#5716
> Revert "Hasan/fix: hero image flickering"

- .github/workflows/generate-preview-link.yml
Changes:
To fix the incorrect CF pages branch name issue.
- Removes non alpha last character
- Removes few symbols from the branch name
> Bala/ fix incorrect branch name

- .github/workflows/generate-preview-link.yml
Changes:
-  Get rid of running the smoke tests within the Generate preview action
-   [X] Script configuration
> Remove smoke tests

- src/store/region-context.tsx
Changes:
Buttons rendered without taking into account the user's IP.
> Konstantinos / Fix IP issue on Deriv go App platforms

- src/features/components/templates/navigation/template/desktop-menu/desktop.items.tsx
- src/features/components/templates/navigation/template/desktop-menu/styles.scss
Changes:
-  nav bar hover issue fix
> fix: hover issue

- crowdin/messages.json
- src/components/layout/layout-overlay.tsx
- src/features/components/molecules/layout-overlay/index.tsx
- src/pages/help-centre/components/_didnt-find-answer.tsx
Reverts binary-com/deriv-com#5854
> Revert "Habib/disable whatsapp"

- src/features/components/atoms/link/internal.tsx
Changes:
-   fixing trackjs error 
-   [ x Bug fix
> fix: :label: fix trackjs issue

- .github/workflows/translators-sync.yml
- Added `title` on automated PRs for `translators` branch
- This will help us observe and check the workflow if it's working correctly
> Prince/fix: added title on pr create

- .github/workflows/translation-sync.yml
> Prince/ patch translation sync workflow

- .github/workflows/translation-sync.yml
> Prince/Update translation-sync.yml

- .github/translation_sync_template.md
- .github/workflows/translation-sync.yml
- Added a PR description template for a better generation of PR on translation synchronization
> Prince/clean up workflow and added PR desc template

- .github/workflows/translation-sync.yml
-   Created a Slack notification for release managers to ensure the immediate merging of the PR, preventing possible conflicts.
> Prince/ added slack hook for the enhanced workflow

- .github/workflows/translation-sync.yml
> Prince/ Update translation-sync.yml

- gatsby-config.js
- gatsby-ssr.js
- package-lock.json
- package.json
Changes:
It works by moving all the script execution to its web worker, thus freeing up the main browser thread to only deal with application code.
> add gtm to partytown url fix

- crowdin/messages.json
- src/features/pages/posts/all-posts/index.tsx
- src/pages/blog/all-posts/index.tsx
> fix: all posts initial

- .github/workflows/production.yml
- .github/workflows/staging.yml
Changes:
The provided secrets are needed for k8s step to be run successfully. they were missed previously.
> Ako/ pass the needed secrets to the step

- .github/workflows/production.yml
- .github/workflows/staging.yml
Changes:
This is to pass the secrets to env to be usable on devops-ci-scripts
> Ako/ pass K8S secrets to envs

- src/features/components/organisms/roadmap/index.tsx
- src/features/components/organisms/roadmap/styles.module.scss
Changes:
-  p2p Product board firefox issue fixed
> Hasan/fix: productboard iframe firefox issue

- .github/workflows/production.yml
- .github/workflows/staging.yml
Changes:
Added the missed env variable as the prev approach didn't work.
> Ako/ add the missed env variable

- src/features/pages/posts/all-posts/index.tsx
- src/features/pages/posts/index.tsx
> fix: align issues

- .github/workflows/production.yml
- .github/workflows/staging.yml
Changes:
1. Renamed the `DOCKHUB_ORGANISATION` to `DOCKERHUB_ORGANISATION` in order to match with other projects and places.
2. added missed secret to k8s step
> Ako/ add missing env variable

- gatsby-config.js
Changes:
Updated partytownProxiedURLs based on: (https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-script/) and testing adding livechat in it too.
> Konstantinos/DERC-2019/Updating partytownProxiedURLs 

- .github/workflows/generate-preview-link.yml
Changes:
Based on security vulnerability raised by security this change would prevent script injection to the CI flow.
> Ako/ prevent script injection vulnerability

- .github/workflows/generate-preview-link.yml
> ci: added github registry for @deriv-com packages

- gatsby-config.js
- gatsby-ssr.js
Reverts binary-com/deriv-com#6038
> Revert "Fix gtm partytown integration"

- package-lock.json
- package.json
Changes:
Removed tailwind merge 
-   ...
> chore: removed tailwind merge package

- .github/workflows/beta.yml
- .github/workflows/corewebvitals.yml
- .github/workflows/lint.yml
- .github/workflows/production.yml
- .github/workflows/staging.yml
- .github/workflows/sync-build-cache.yml
- .github/workflows/translation.yml
Changes:
-   in order to setup and install npm / github packages, we added readonly token to acitons.
> chore: added github readonly token to actions

- src/pages/trading-specification/data/_commodities_specification.ts
- src/pages/trading-specification/data/_derived_specification.ts
- src/pages/trading-specification/data/_etfs_specification.ts
- src/pages/trading-specification/data/_forex_specification.ts
- src/pages/trading-specification/data/_stocks_specification.ts
Changes:
After the DST (Daylight saving time ) the trading hours of some instruments have changed.  This information needs to be updated on the trading specification table
> Konstantinos / Update trading hours(Daylight savings) on the trading specifications table - November

- src/features/pages/home/user-platfroms/data.tsx
- src/features/pages/home/user-platfroms/index.tsx
> chore: implemented tabs for user friendly section

- package-lock.json
> chore: updated package-lock.json

- .github/workflows/production.yml
- .github/workflows/staging.yml
Changes:
-   With this change we will be able to see published app version name from browser. 
it should be `{url_endpoint}/version.txt`
> Ako/ add tag_name to public directory to be visible on server

- src/features/pages/home/navigation/data.tsx
Changes:
- updated the position of nav item for EU version
-   ...
> Fasih/: fixed item position

- package-lock.json
- package.json
- src/features/pages/home/navigation/data.tsx
- src/features/pages/home/navigation/nav.buttons.tsx
> fix: navigation subtasks

- .github/workflows/translators-sync.yml
> Prince/Update translators-sync.yml

- .github/workflows/smoketests.yml
Changes:
-   ...
-   [X] Script configuration
> Skip any smoke tests where the branch has translation.

- src/components/custom/_dhero-dmt5.tsx
- src/features/components/templates/banners/deriv-products-hero/products-signup.tsx
- src/pages/derivx/_hero.tsx
navigation changes for products trading click
-   ...
> fix: navigation for product page

- package-lock.json
- package.json
- src/features/pages/home/fast-payment/index.tsx
Changes:
Fixed the speed of carousel 
-   ...
> Fasih/: added updated changes of blocks

- gatsby-node.js
- src/features/pages/posts/all-posts/index.tsx
- src/features/pages/posts/index.tsx
- src/pages/blog/_types.ts
- src/pages/blog/all-posts/index.tsx
- src/pages/blog/index.tsx
- src/pages/blog/single-blog/index.tsx
> fix: slug change

- src/features/components/templates/footer/download.tsx
> chore: fixed footer icon for safari

- package-lock.json
- package.json
- src/features/components/quill/alert/index.tsx
- src/features/components/quill/shared-link/external.tsx
- src/features/components/quill/shared-link/index.tsx
- src/features/pages/home/footer/data.tsx
- src/features/pages/home/index.tsx
Changes:
-  Moved GatsbySharedLink component to a separate file
- Added new External link component
> Hasan/chore: fixed link component for eu

- package-lock.json
- package.json
- src/features/components/templates/footer/index.tsx
> fix: update deriv-com-libs

- .github/workflows/pre-generate-preview-link.yml
Changes:
-   this is to fix the issue of upload artifact action.
> Ako/ pass correct name to upload action

- .github/workflows/generate-preview-link.yml
> Prince/ key test run

- .github/workflows/generate-preview-link.yml
> Prince/Update generate-preview-link.yml

- package-lock.json
- package.json
- src/features/components/templates/footer/data.tsx
- src/features/components/templates/navigation/career-nav/index.tsx
- src/features/components/templates/navigation/main-nav/nav.buttons.tsx
- src/features/components/templates/navigation/partners-nav/nav.buttons.tsx
fix: social-links for EU in footer
Changes:
-   ...
> chore: update quill icons to fix traders hub icon

- src/components/layout/layout.tsx
- src/features/components/templates/footer/banner-and-awards.tsx
- src/pages/markets/basket-indices/index.tsx
- src/pages/markets/commodities/index.tsx
- src/pages/markets/cryptocurrencies/index.tsx
- src/pages/markets/derived-fx/index.tsx
- src/pages/markets/forex/index.tsx
- src/pages/markets/stock/index.tsx
- src/pages/markets/synthetic/index.tsx
> fix: hero cropping issue

- src/features/components/molecules/timeline-item/index.tsx
> fix: bullet alignment issue in options page

- src/components/elements/market-tab/index.tsx
- src/features/components/templates/hero-banners/trade/trade-hero.module.scss
- src/features/pages/deriv-ctrader/hero-banner/data.tsx
- src/features/pages/markets/etf/index.tsx
- src/features/styles/theme/alert.scss
- src/pages/markets/components/sections/_hero_derived_fx.tsx
- src/pages/trading-specification/components/_elements.tsx
Changes:
-  Modal overlay issue fixed
- Trading specifications icon alignment issue fixed
- Platform DerivGo Market page issue fixed
- ctrader logo responsive issue fixed
> Hasan/chore: fixed hotfixes

- src/components/layout/layout.tsx
- src/pages/careers/index.tsx
- src/pages/careers/locations/index.tsx
> fix: great place to work cropping issue in careers page

- package-lock.json
- package.json
> fix: navigation button alignment issue in mobile

- src/features/components/templates/navigation/partners-nav/prime-nav.tsx
> fix: update deriv prime logo

- src/features/components/templates/navigation/partners-nav/nav.buttons.tsx
- src/features/components/templates/navigation/partners-nav/prime-nav.tsx
> fix: hide longer buttons in mobile nav

- src/features/components/templates/navigation/partners-nav/prime-nav.tsx
> fix: prime redirecting issue

- package-lock.json
- package.json
> Hasan/chore: updated packages

- src/features/components/templates/footer/data.tsx
Changes:
-   CY Data for social icons
> Update data cy for social icons

- package-lock.json
- package.json
> chore: updated deriv pacakges

- src/features/components/organisms/markets/market-banner/styles.module.scss
- src/features/pages/markets/etf/index.tsx
- src/pages/markets/components/sections/_hero_derived_fx.tsx
Changes:
-   added back markets bottom navigation
> fix: added markets bottom navigation

- package-lock.json
- package.json
- src/features/components/templates/navigation/main-nav/nav.logo.tsx
Changes:
- added data-cy in logo for cypress test
> Hasan/chore: added cy id in logo

- package-lock.json
- package.json
- src/features/components/templates/navigation/main-nav/nav.buttons.tsx
- src/features/components/templates/navigation/main-nav/nav.logo.tsx
> Hasan/chore: added cy id in logo for mobile and desktop

- gatsby-ssr.js
> fix: 3 seconds

- crowdin/messages.json
- package-lock.json
- package.json
- src/features/pages/home/fast-payment/index.tsx
- src/features/pages/home/years/data.tsx
Changes:
-   updated packages
- updated 'withdrawals' spelling
> {DPRO-378}/ Translation 378 fix fast hassle block subtask

- .github/workflows/production.yml
Changes:
This is to fix the issue of Docker, K8S backup plan
> ci: upload & download artifacts between jobs

- src/features/pages/options/accumulator/index.tsx
Reverts binary-com/deriv-com#6532
> Revert "Mitra/DPROD-2207/remove demo tag from accumulator"

- src/features/components/quill/layout-overlay/cfd-warning-banner/desktop-text.tsx
- src/features/components/quill/layout-overlay/cfd-warning-banner/mobile-text.tsx
- src/features/components/quill/layout-overlay/cfd-warning-banner/styles.module.scss
- src/features/components/quill/layout-overlay/cookie-banner/index.tsx
- src/features/components/quill/layout-overlay/cookie-banner/styles.module.scss
- src/features/components/quill/layout-overlay/floating-button/index.tsx
- src/features/components/quill/layout-overlay/floating-button/styles.module.scss
- src/features/components/quill/layout-overlay/index.tsx
- src/features/components/quill/layout-overlay/styles.module.scss
Changes:
-  Moved all the responsive css to css module
> Pr 00 overlay fixes

- src/features/pages/options/accumulator/index.tsx
Reverts binary-com/deriv-com#6535
Changes:
Remove demo tag from accumulator page
> "Mitra/DPROD-2207/remove demo tag from accumulator""

- .github/workflows/production.yml
Changes:
This is to make the second job wait for the first one to complete then start.
I also reduced the retention days to 5 to reduce the storage usage.
> Ako/ wait for prev job to complete then download the artifacts

- src/features/pages/home/live-pricing-migration/cards/index.tsx
- src/features/pages/home/years/index.tsx
Changes:
- added default space between swiper slide
> Pr 00 swiper issue

- package.json
- scripts/handle-translations.js
**Updates:**
- added a new script `npm run translation:fix` - this is to resolve conflicts between `master` and `translation` branches
> Prince/ added translation-fix command for conflict fixing

- .github/workflows/generate-preview-link.yml
Changes:
Updated Generate Preview link file so if we create any PR against any branch now we can get CF preview link 
-   ...
> chore: updated preview link file

- static/css/global.css
Changes:
-   Add css in global to fix AR slider direction for EU users
> Fasih/WEBREL-2492/Add css in global to fix AR slider direction for EU users

- src/features/pages/home/start-trading-steps/data.tsx
- tailwind.config.js
Changes:
-   Rewrite default class quill-design component
> Eduard/WEBREL-2489/Rewrite default class quill-design component

- src/features/hooks/use-residence-list/index.tsx
Changes:
-  ctrader_sign_up page
> DPROD-3038/mayuran/ctrader_sign_up page

- gatsby-node.js
> Prince/ chunks on local

- src/features/pages/signup/signup.content.tsx
Changes:
-  Remove country restriction inside the codebase for A/B test
> [CRO] Amir/CRO-456/Remove country restriction inside the codebase for A/B test

- src/common/websocket/index.ts
remove console logs on ws connection.
-   ...
> fix: remove console logs

- .github/workflows/generate-preview-link.yml
We need to store a new param to GH storage, DRAFT. So that the smoketest.yml can use it to ignore a test run.
Changes:
-   ...
> Update generate-preview-link.yml - Add DRAFT param

- .github/workflows/smoketests.yml
The draft param wasn't being interpretted correctly.
Changes:
-   ...
> Update smoketests.yml - Mod to draft param

- src/features/pages/deriv-ctrader/how-to-start/data.tsx
Changes:
Resolved the issue to prevent the sign in from opening in a new tab 
-   ...
> lipika/DPROD-1852/ Sign in CTA for Ctrader opens in new tab

- package-lock.json
- package.json
Changes:
-   [Trackjs] Error: Cannot convert undefined or null to object
> Aswathy/FEQ-1843/fix: upgraded the analytics istrackjs sue

- src/pages/contact-us/_offices.tsx
Changes:
-   DPROD-3648/fixed ui contact us page (office details block)
> Prince/DPROD-3648/fixed ui contact us page (office details block) 

- .github/workflows/staging-eu.yml
- .github/workflows/staging-row.yml
> chore: updated version dir in staging workflow

- crowdin/messages.json
- themes/gatsby-theme-deriv/src/components/hooks/use-cookie-banner.ts
- themes/gatsby-theme-deriv/src/features/components/templates/footer/index.tsx
- themes/gatsby-theme-deriv/src/features/pages/home/live-pricing-migration/index.tsx
- themes/gatsby-theme-deriv/src/features/pages/options/accumulator/index.tsx
- themes/gatsby-theme-deriv/src/features/pages/p2p/_data.ts
- themes/gatsby-theme-deriv/src/features/pages/p2p/index.tsx
- themes/gatsby-theme-deriv/src/features/types/index.ts
- themes/gatsby-theme-deriv/src/pages/careers/locations/london/index.tsx
- themes/gatsby-theme-deriv/src/pages/contact-us/index.tsx
- themes/gatsby-theme-deriv/src/pages/derivx/_other-apps.tsx
- themes/gatsby-theme-deriv/src/pages/dtrader/_our-platforms.tsx
- themes/gatsby-theme-deriv/src/pages/markets/instruments/_dex-indices.tsx
- themes/gatsby-theme-deriv/src/pages/markets/instruments/_drift_switch_indices.tsx
- themes/gatsby-theme-deriv/src/pages/our-principles/index.tsx
- themes/gatsby-theme-deriv/src/pages/p2p.tsx
- themes/gatsby-theme-deriv/src/pages/trader-tools/margin-calculator/index.tsx
- themes/gatsby-theme-deriv/src/pages/trader-tools/pip-calculator/index.tsx
- themes/gatsby-theme-deriv/src/pages/trader-tools/pnl-for-margin/index.tsx
- themes/gatsby-theme-deriv/src/pages/trader-tools/pnl-for-multipliers/index.tsx
- themes/gatsby-theme-deriv/src/pages/trader-tools/swap-calculator/index.tsx
> chore: updated use cookie banner hook

- themes/gatsby-theme-deriv/src/pages/help-centre/about-deriv.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/account.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/affiliate-programme.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/complaints-procedure.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/deposits-and-withdrawals.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/deriv-trader.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/dmt5.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/fraud-prevention.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/ib-programme.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/payment-agent.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/security.tsx
- themes/gatsby-theme-deriv/src/pages/help-centre/trading.tsx
> chore: fixed help center pages

- themes/gatsby-theme-deriv/static/css/global.css
> chore: added default var

- .github/workflows/smoketests.yml
Changes:
Smoke test fix, draft commented
> Agrim/chore: smoke test

- .github/workflows/smoketests.yml
Reverts binary-com/deriv-com#7501
> Revert "Agrim/chore: smoke test"

- .github/workflows/smoketests.yml
> debug smoketests.yml

- themes/gatsby-theme-deriv/src/components/hooks/use-show-cfd-banner.ts
- themes/gatsby-theme-deriv/src/features/contexts/floating-cta/cta.provider.tsx
> Hasan/chore: fixed cta

- themes/gatsby-theme-deriv/src/common/utility.ts
- themes/gatsby-theme-deriv/src/components/custom/utils.tsx
Changes:
-   Add `redirect_from` query param
> Sergei / Add redirect_from query param

- .github/workflows/smoketests-eu.yml
- .github/workflows/smoketests-row.yml
- .github/workflows/smoketests.yml
Changes:
-   Smoke Test structure fix for multiple Build
> test smoketest fix

- .github/workflows/smoketests-row.yml
Changes:
-  Update smoke row fix
> Update smoke row fix

- .github/workflows/production-eu.yml
- .github/workflows/production-row.yml
Changes:
-   Add k8 backup and slack integration
> Add k8 backup and slack integration

- .github/workflows/production-row.yml
> chore: fix workflow

- .github/workflows/beta.yml
- .github/workflows/corewebvitals.yml
- .github/workflows/production-eu.yml
- .github/workflows/production-row.yml
- .github/workflows/staging-eu.yml
- .github/workflows/staging-row.yml
- .github/workflows/translation-sync.yml
Changes:
- Updated SHA for `8398a7/action-slack` action in all workflows
> Updated SHA for 8398a7/action-slack action

- themes/gatsby-theme-deriv/src/features/pages/signup-v2/form-container/signup-page-form.tsx
Changes:
-   fix email input label issue on iphone 12
Screenshot of the changes:
Screenshot of the issue reported:
> [CRO] Amir/ fix email input label issue on iphone 12

- .github/workflows/smoketests-eu.yml
> down to version 4.0.0

- .github/workflows/smoketests-eu.yml
- .github/workflows/smoketests-row.yml
Changes:
- Update path from `.pr` to `pr` for the smoketest workflows
> Updated path for smoketest workflow

- themes/gatsby-theme-deriv/src/features/hooks/use-signup-form/index.tsx
Changes:
sign up page , fix for timeout ws connection  to reconnect again 
> fix: timeout ws connection
