binary-com/deriv-com

README.md
src/pages/index.js

fix bad wording

---

src/themes/device.js
src/themes/global-style.js

add default font size in root element (html) tag

add font size

---

src/components/elements/carousel.js
src/images/svg/abstract.svg
src/images/svg/checklist.svg
src/pages/index.js
src/themes/variables.js

Home page carousel:
accept an array of components as props `slides`.
render the active component inside of it.
Generate ` Bullets` based on slides counts.

arash/Deriv.com Carousel component

---

gatsby-config.js
package-lock.json
package.json

- Add robots-txt plugin
- Use default policy
- Minimum options

add robots plugin

---

src/components/layout/footer.js
src/pages/about/index.js
src/pages/help-centre/index.js
src/pages/index.js
src/pages/keep-safe/index.js
src/pages/regulatory/index.js
src/pages/responsible-trading/index.js
src/pages/terms-and-conditions/index.js

Updated pages:
- Home
- About us
- Help
- Keep Safe
- Responsible trading
- Regulatory information
- Terms and conditions

update titles and descriptions

---

src/components/layout/footer.js

hide mt5 in footer
Changes:
- comment mt5 in footer
- add todo
-   [x] This change requires a documentation update

hide mt5 footer

---

src/pages/terms-and-conditions/_data-feed.js

Reverts binary-com/deriv-com#206

Revert "Sara / Changed content"

---

src/pages/home/_ticker.js

Reverts binary-com/deriv-com#284

Revert "oskar/ticker_to_synthetic"

---

src/components/containers/seo.js
src/pages/home/_ticker.js

- add new yandex id
Changes:
- new yandex id
-   [x] Release

V20191104_1

---

src/components/containers/container.js
src/components/containers/grid-container.js
src/components/custom/other-platforms.js
src/components/custom/platforms-dropdown.js
src/components/elements/card.js
src/images/svg/card-arrow.svg
src/pages/about/_our-goals.js
src/pages/dbot/index.js
src/pages/dmt5/index.js
src/pages/dtrader/index.js
src/pages/home/_trade.js
src/themes/variables.js

Changes:
Change the card component UI and add a temporary card with the old ul for the home page

arash/ Card component

---

src/components/custom/platforms-dropdown.js
src/pages/home/_trade.js

Fixed navdropdown height issue

---

src/components/layout/footer.js
src/pages/regulatory/index.js

Sara / Chnaged Vanuatu Link

---

.circleci/config.yml

fix: k8s tag base deployment instead of commit id

---

gatsby-config.js
src/common/websocket/config.js
src/components/containers/seo.js

fix ach page shouldnt appear in production
Changes:
- fix isProduction function
- add no index tag to ach pages
- remove ach from sitemap

amam/fix `ach` in production

---

.circleci/config.yml

ignore crowdin branch

---

.circleci/config.yml

V_20200410_1
- FIx CI i18n_crowdin
- Add GATSBY_ENV environment variables
-   [x] Release

V_20200410_1

---

gatsby-config.js

hotfix_update

---

src/components/layout/footer.js

* Hide language switcher in production

Hide language switcher in production

---

src/pages/markets/_available-trades.js

arash/ active tab style

---

src/pages/dmt5/index.js

hotfix update on dmt5 name change
- change localize to Localize to make translation on dmt5 working

amam/change localize to Localize

---

src/pages/dmt5/index.js

…owdin
- Localize in dev didnt reflect on crowdin

Fix crowdin branch

---

src/components/layout/footer.js
src/pages/amp/homepage/_footer.js
src/pages/regulatory/index.js

amam/Binary (SVG) Ltd to Binary (SVG) LLC

---

src/components/layout/footer.js
src/pages/markets/_available-platforms.js
src/pages/markets/_available-trades.js
src/pages/markets/_other-markets.js
src/translations/fr.json

Enable language switcher and fix miss layout on markets pages

Enable language switcher

---

package.json

Add build command to enable experimental incremental builds for gatsby

incremental_builds

---

src/components/custom/_signup-new.js

Text after login doesnt have space

Signup space

---

package.json
src/components/custom/_signup-new.js
src/pages/markets/_other-markets.js

Update dev crowdin

---

src/pages/partners/affiliate-ib/_deriv-ib-programme.js

Sara / Made the affiliate buttons aligned

---

src/components/localization/language-dropdown.js

hotfix release V20200601_0

---

src/pages/regulatory/index.js

Added Deriv regulatory note
Changes:
-   new text

add deriv note

---

src/common/country-base.js

add malta to eu countries list
Changes:
-  add mt to list of eu countries

(add) malta to eu countries array

---

src/common/country-base.js
src/components/containers/show.js

Release V20200615_1
Changes:
- add malta to eu country list
-   [x] Release

V20200615_1

---

src/components/elements/timeline.js

PR related: https://github.com/binary-com/deriv-com/pull/861
stylelint error 0 length unit

fix stylelint error staging

---

src/components/layout/footer.js
src/pages/contact-us/_contact-ways.js
src/pages/regulatory/index.js

Fix footer regulatory
Changes:
- Change to Deriv (V) and Deriv (BFX)
- Remove contact ways contact us in contact us page

hotfix_V20200708_0

---

.circleci/config.yml

Bug fix build slack version

---

.circleci/config.yml

Add new pipeling for staging

---

src/pages/contact-us/_affiliates.js
src/pages/contact-us/_contact-ways.js

Add livechat section on contact us page

V20200713_1

---

src/html.js

Changes:
- add variable gtm_id inside of the script
- remove double gtm script

amam/fix GTM

---

deriv.com.conf

Reverts binary-com/deriv-com#979

Revert "oskar/response_headers"

---

gatsby-config.js
package-lock.json
package.json
src/html.js

Rever "oskar/gtm_for_test_domain"

---

src/components/custom/_signup-default.js
src/components/custom/_signup-flat.js
src/components/custom/_signup-new.js
src/components/custom/_signup-public.js
src/components/custom/_signup-simple.js
src/components/custom/signup.js

Changes:
-  added GTM ids for email, google, and facebook

amam/add GTM IDs for signup

---

gatsby-browser.js

Sara / Added check domain function to avoid copy 

---

gatsby-browser.js

Sara / Added localhost to check domain whitelist

---

src/components/localization/language-switcher.js
src/pages/responsible-trading/_trading-limits.js

Hide polish language due to incomplete translation

amam/hide polish language + todo for CR self exclusion notes

---

gatsby-node.js
src/components/elements/card.js

unpublish homepage a/b testing page

amam/unpublish homepage a/b testing page

---

src/common/login.js

Simplified Chinese & Traditional Chinese `(zh-ch and zh-tw)` [Login Page.png]Summary
Fix bug for the chinese translation
Changes:
-   login.js

Kevin/login page translation for chinese s & t

---

src/pages/payment-methods/_payment-data.js

Sara / Changed UST to USDT

---

src/components/elements/typography.js
src/pages/dmt5/_start-trader.js
src/pages/dmt5/components/_side-tab.js
src/pages/dmt5/index.js

Sara / Fixed DMT5 bugs

---

src/pages/about/_our-history.js

Sara / Fixed issue with about us page

---

gatsby-browser.js
src/common/login.js
src/common/websocket/initial-render-socket.js
src/components/custom/signup.js

abdalla/read/write 'date_first_content' and 'signup_device' from/to cookies

---

src/pages/interim/faq/_faq.js

Sara / Updated eu interim faq page

---

src/pages/partners/affiliate-ib/_deriv-affiliate-programme.js
src/pages/partners/payment-agent/_faq-data.js

Sara / updated affiliate page

---

gatsby-node.js
src/pages/404.js

abdalla/ redirect /en to /

---

src/pages/interim/_cta-binary.js
src/pages/interim/_faq-data.js
src/pages/interim/deriv/_hero.js

Sara / Updated interim text

---

src/pages/careers/locations/rwanda/index.js

Changes:
- change SEO title from limasol to kigali

change limasol to kigali

---

package.json

fix conflict on package.json and package-lock.json
Changes:
- remove react responsive from the list

amam/remove react-responsive on package.json

---

src/pages/dmt5/_dhero.js

Fix DMT5 margin bug
Summary
Changes:
-   ...

Sean / fix: DMT5 margin bug

---

src/pages/trade-types/multiplier/_how-multiplier-works.js

Sean / fix: multiplier page card margins for mobile

---

src/components/custom/platforms-dropdown.js
src/components/layout/nav.js

Summary
Fix: about us and login button breaking into 2 rows on certain resolutions.
Changes:
-   ...

Sean/fix: about us and login button wrapping

---

src/components/custom/_dhero.js

Kevin/ hotfix: button height for 360px

---

src/pages/regulatory/_document_accordion.js

Kevin/fix: regulatory eu page

---

src/pages/careers/_our-hiring-process.js
src/pages/careers/_our-values.js
src/pages/dmt5/_download-app.js
src/pages/partners/payment-agent/_your-control.js
src/pages/trade-types/components/_style.js

abdlla/fix: images

---

src/common/utility.js
src/pages/reset-password/index.js

abdalla/add: trim spaces in email field

---

src/components/layout/nav.js
src/components/localization/language-dropdown.js

Sean / fix: affiliate button breaking

---

src/components/custom/signup.js

abdalla/fix: signup error message

---

src/components/custom/signup.js
src/pages/signup/index.js

abdalla/CLOSE: socket after recieving a response

---

src/components/elements/carousel/carousel.js
src/pages/home/_hero.js
src/pages/home/_vertical-carousel.js

abdalla/add: vertical carousel

---

src/common/login.js
src/components/custom/signup.js

abdalla/ADD: new utm fields to cookies

---

src/components/elements/accordion.js
src/pages/regulatory/_document_accordion.js
src/pages/responsible-trading/_trading-responsibly.js

Sean / fix: added KID notice

---

src/common/utility.js
src/components/elements/default-tab.js
src/components/elements/side-tab.js
src/components/hooks/use-tab-state.js
src/pages/about/index.js
src/pages/help-centre/_article.js
src/pages/markets/index.js

abdalla/UNIFY: tabs effect

---

src/pages/careers/_model/_locations/_contact-details.js
src/pages/careers/locations/_location-layout.js
src/pages/contact-us/_offices.js

Summary
Changes:
-   Update Cyprus address
-   Fixed alignment and title size

Sean / fix: design discrepancies

---

src/components/layout/layout.js
src/components/layout/nav.js
src/pages/careers/index.js
src/pages/careers/locations/index.js
src/pages/partners/affiliate-ib/index.js
src/pages/partners/index.js
src/pages/partners/payment-agent/index.js
src/pages/signup/index.js

abdalla/Fix: hero padding issue

---

README.md
documents/gtm-workflow.md

Update README and added GTM Workflow under `Other Documents`

Matin/Improvement: README with GTM workflow

---

src/pages/trade-types/components/_markets-carousel.js

abdalla/Fix: multiplier viewport

---

src/components/elements/default-tab.js
src/pages/terms-and-conditions/_business-grid.js
src/pages/terms-and-conditions/_clients-grid.js
src/pages/terms-and-conditions/_terms-conditions-style.js
src/pages/terms-and-conditions/index.js

abdalla/Align: tabs in terms and conditions

---

src/pages/home/_markets.js

abdalla/Fix: background color

---

src/pages/trade-types/components/_style.js

abdalla/Fix: box height

---

src/components/layout/nav.js
src/pages/reset-password/index.js

abdalla/Fix: layout margin issue

---

src/pages/trade-types/multiplier/_what-are-multipliers.js
src/themes/variables.js

Summary
Changes:
-  add new blue color
- fix profit color

Kevin/hotfix: trade-type-mult  profit text color

---

src/components/elements/off-canvas-menu.js

abdalla/Fix: sidebar on mobile

---

src/pages/home/_markets.js

abdalla/Fix: markets' padding issue in home page

---

src/pages/trader-tools/_swap-calculator.js

Kevin/hotfix: anchor swap policy

---

src/components/custom/_signup-new.js
src/components/elements/checkbox.js

Running E2E tests require direct access to elements to interact with, this PR addresses checkbox in signup form. 
Summary
Changes:
-   ...

Add ID selector for signup checkbox

---

src/components/custom/_simple-steps.js
src/pages/index.js

yashim/fix: Background Pattern and Sign Up Button in Main Page

---

src/pages/payment-methods/_expanded-list.js
src/pages/payment-methods/index.js

Summary
Changes:
-   add css styling for sticky first child of the table

Kevin/feat: payment-page - fixed scroll first child

---

src/components/custom/platforms-dropdown.js

yashim/fix: main page dropdown offsets not updating when resizing window

---

src/pages/dmt5-trading-signals/_how-to.js
src/pages/dmt5-trading-signals/_signal.js
src/pages/dmt5-trading-signals/_subscription.js
src/pages/dmt5-trading-signals/index.js

Changes:
-   Fixes issues 2 & 4 of translation hotfix
-   Requires new strings to be extracted

Sean/fix: Issues 2 & 4 of translation hotfix

---

src/pages/dmt5/_dbanner.js

Changes:
-   Fix banner height for PT language on DMT5 page

Sean / fix: banner height for PT language on DMT5 page

---

src/components/layout/nav.js

abdalla/Fix: Mobile Nav under 360px

---

src/components/localization/language-switcher.js

Abdalla / Refactor: language switcher

---

src/components/elements/carousel/carousel-style.js
src/pages/home/_trade-types-mobile.js

Changes:
-   Fix trade types carousel size for various languages

Sean / Fix trade types carousel size for various languages

---

src/pages/dmt5-trading-signals/index.js

Changes:
-   Fix truncated tabs for various languages

fix: truncated tabs for various languages

---

src/pages/dmt5-trading-signals/_style.js
src/pages/dmt5-trading-signals/index.js
src/pages/trade-types/multiplier/_things-in-mind.js
src/pages/trader-tools/_margin-calculator.js
src/pages/trader-tools/_swap-calculator.js
src/pages/trader-tools/index.js

Changes:
-   Fix broken tabs and broken fonts on trader tools page

Sean / fix: broken tabs and broken fonts

---

src/components/custom/_signup-public.js

Summary
Changes:
-  color and swap text

Kevin/hotfix:sign up social button on mobile screen

---

src/components/custom/signup.js

Changes:
-   Fix check mail page font size

Sean / fix: check mail page font size

---

src/pages/regulatory/index.js

Update `Deriv Investments (Europe) Limited` section in `regulatory`

Abdalla/Update: Regulatory

---

src/pages/about/_story_constant.js
src/pages/why-choose-us/_icon-grid.js
src/pages/why-choose-us/_test.js

Abdalla/Update: about - why-choose-us

---

src/components/custom/cookie-banner.js

Changes:
-   Fixed cropped cookie banner for mobile

Sean / fix: cropped cookie banner for mobile

---

src/components/custom/_signup-new.js

Changes:
-   Fix signup title size

Sean / fix: signup title size

---

src/components/custom/_signup-new.js

Changes:
-   Fix sign up page font discrepancies with design

Sean / fix: sign up page font discrepancies with design

---

src/components/layout/footer.js

Abdalla/Update: EU footer

---

src/components/layout/footer.js

Add license to EU footer

---

src/pages/trade-types/components/_markets-carousel.js
src/pages/trade-types/components/_style.js

Changes:
-   Fix trade types carousel size across all languages

Sean / fix: trade types carousel size across all languages

---

src/pages/home/_trade-types.js

Summary
- Updated trade types text as per copywriter suggestions
Changes:

yashim/fix: update trade types text

---

src/pages/payment-methods/index.js

Changes:
modify disclaimer in `/payment-methods` to be `We process all your deposits and withdrawals within 1 day. However, the processing times and limits in this page are indicative, depending on the queue or for reasons outside of our control.`

Abdalla/Edit: Disclaimer Content in payment methods page

---

src/pages/about/_our-offices.js

Changes:
-   Localise country names on map

Sean / fix: translation of country names on map

---

src/pages/help-centre/account.js

Removed france from help center

---

src/pages/p2p/components/_numbers.js

Changes:
-   Update volume numbers

Sean / update DP2P content

---

src/components/custom/_dhero.js
src/components/custom/_signup-public.js
src/components/custom/_simple-steps.js
src/components/form/button.js
src/pages/dmt5/_dhero.js
src/pages/dmt5/_flexibility.js
src/pages/home/_hero.js
src/pages/home/_trade-types-mobile.js
src/pages/home/_trade-types.js

Changes:
-   Fix button design discrepancies across homepage and market pages

Sean / fix: button design discrepancies

---

src/pages/markets/_available-trades.js

Abdalla/Fix: card wrapper overflow

---

src/components/custom/_signup-public.js
src/components/custom/_simple-steps.js
src/components/elements/default-tab.js
src/pages/markets/_available-options.js
src/pages/markets/_available-platforms.js
src/pages/markets/_other-markets.js
src/pages/markets/_why-trade.js
src/pages/markets/synthetic/_digital-options.js
src/pages/markets/synthetic/_margin.js
src/pages/markets/synthetic/_multipliers.js

Kevin/fix:multiplier synthetic design issues

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer.js
src/pages/trade-types/options/index.js

Changes:
-   Restrict options page to only non-eu users

Sean / feat: restrict options page to only non-eu

---

src/pages/reset-password/index.js

Changes:
-   Fix reset password page white spaces

Sean / fix: reset password page white spaces

---

src/pages/dmt5/_flexibility.js

Changes:
-   Fix MT5 page go to dashboard button for various languages

Sean / fix: MT5 page go to dashboard button for various languages

---

src/pages/home/_trade-types-mobile.js

Summary
- Applied updates to trade type text (mobile) missed out from PR: https://github.com/binary-com/deriv-com/pull/1291
Changes:
- Text changes

yashim/hotfix: apply trade types text update to mobile pages

---

src/components/elements/side-tab.js

Changes:
-   Removed obsolete design from help center in mobile view

remove help center questions obsolete design

---

src/components/layout/footer.js
src/components/layout/layout.js

Changed CFD risk value from 74% to 71% and changed some contents in the footer.
Changes:
- Changed CFD risk from 74% to 71%
- Changed some content in the footer
-   ...

Mahdi Aryayi / Fixed CFD risk value

---

src/components/layout/footer.js
src/components/localization/localized-link.js
src/pages/regulatory/index.js

Priojeet/update: change hyperlinked account details for del and dmx

---

gatsby-browser.js
src/common/utility.js
src/components/containers/seo.js

Kevin/add:datadog script

---

src/pages/about/_our-numbers.js
src/pages/partners/_deriv-numbers.js

Kevin/update:story and partner numbers jan 2021

---

src/pages/dmt5-trading-signals/index.js

fix:trading signal add dot

---

gatsby-browser.js
src/common/utility.js

Kevin/add: sample_rate on utility for datadog

---

src/components/custom/other-platforms.js
src/components/layout/footer.js

Summary
- As per title
Changes:
- Removed external flags from navigation links

yashim/fix: community and blog treated as external link (EU)

---

src/pages/payment-methods/_payment-data.js

This PR is to update payment processing time
- Change processing time from `working day(s)` to `day(s)`

AbdallaUpdate: payment processing time

---

src/pages/p2p/components/_availability.js
src/pages/p2p/components/_exchange-steps.js

yashim/fix: page titles in P2P page

---

src/components/layout/nav.js
src/pages/partners/affiliate-ib/_deriv-ib-programme.js
src/pages/partners/affiliate-ib/_more-reason.js

Kevin/ hotfix ib page fixes

---

src/components/layout/nav.js

yashim/hotfix: removed extra language switcher & Resources link at partner navbar

---

src/pages/trade-types/multiplier/_available-trades.js

Changes:
-   Fix tab headers breaking for certain languages

Sean / fix: tab headers breaking for certain languages

---

src/pages/partners/affiliate-ib/_hero.js

yashim/hotfix: partner-payment page mobile layout problem

---

src/components/layout/nav-careers.js
src/components/layout/nav.js
src/pages/careers/_hero.js
src/pages/regulatory/index.js

Priojeet/fix:deriv-careers-page-width-is-greater-than-viewport

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer.js
src/components/layout/layout.js
src/components/layout/nav.js
src/pages/home/_hero.js
src/pages/home/_markets.js
src/pages/home/_trade-the-way-you-like.js
src/pages/home/_trade.js
src/pages/landing/index.js

Kevin/feat:add landing page clone with adjustment

---

src/common/login.js
src/pages/home/_trade-types.js
src/pages/reset-password/index.js

Reverts binary-com/deriv-com#1284

Revert "mamali/update Reset password design with the universal flow"

---

src/pages/regulatory/index.js

Summary
Changes:
- Removed link style override causing redundant colour changing during hover

yashim/hotfix: remove link style override at regulatory page

---

src/common/utility.js
src/components/hooks/use-active-link-state.js

yashim/hotfix: added check if getLocationPathName returns undefined

---

src/pages/partners/affiliate-ib/_deriv-affiliate-programme.js
src/pages/partners/affiliate-ib/_deriv-ib-programme.js
src/pages/partners/affiliate-ib/index.js

Kevin/Hotfix: ib programme card content translation

---

src/pages/markets/static/content/_margin.js

Kevin/hotfix: synthetic indices market typo fix

---

src/pages/markets/components/sub-markets/_digital-options.js
src/pages/markets/components/sub-markets/_margin.js
src/pages/markets/components/sub-markets/_multipliers.js
src/pages/markets/static/style/_markets-style.js

Remove `margin-top` from first row in `OptionsRow`

Abdalla/Fix: options gap in markets

---

src/pages/trade-types/multiplier/_margin.js
src/pages/trade-types/multiplier/_synthetic-indices.js

Changes:
- fix build error on crowdin

Hotfix: build error on staging from crowdin

---

src/pages/partners/affiliate-ib/_deriv-ib-programme.js

Changes:
-   Fix IB info Russian text overlap

Sean / fix: IB info Russian text overlap

---

src/components/custom/_dnumbers.js

Changes:
-   Fix numbers in Dbot not aligned

Sean / fix: numbers in dbot not aligned

---

src/pages/partners/affiliate-ib/_deriv-affiliate-programme.js
src/pages/partners/affiliate-ib/_deriv-ib-programme.js

Summary
Changes:
- Styling change

yashim/hotfix: fixed text stylings in affiliate IB page

---

src/pages/p2p/components/_dp2p.js
src/pages/p2p/components/_exchange-steps.js
src/pages/p2p/components/_hero.js
src/pages/p2p/components/_numbers.js
src/pages/p2p/v2/index.js

Changes:
-   Update DP2P LP content

Sean / Update DP2P LP content

---

src/pages/dmt5/index.js

Changes:
-   Replaced useStaticQuery to StaticQuery temporarily to solve "useStaticQuery could not be fetched error"

Sean / replaced useStaticQuery to StaticQuery

---

src/components/hooks/use-livechat.js

To fix missing **chat_id** unhandled promise on
https://my.trackjs.com/details/f3b68322be99485bb74d3cbbb95c5217
Summary
Changes:
-   ...

Kevin/feat: handle missing chat_id

---

src/common/utility.js
src/components/elements/off-canvas-menu.js
src/components/layout/layout.js
src/components/layout/nav-careers.js
src/components/layout/nav.js
src/components/localization/language-dropdown.js
src/pages/careers/_hero.js

Priojeet/fix:refactor-options-and-cfd-warnings

---

src/components/layout/footer.js
src/pages/regulatory/index.js

Summary
- Text change on footer (EU) and regulatory info page
Changes

yashim/text: update footer text (EU) and regulatory info

---

deriv.com.conf

fix: revert cache strategy

---

.github/pull_request_template.md

Changes:
-   Update PR template

Sean / Update PR template

---

src/common/utility.js
src/components/layout/nav.js

priojeet/feat: show get trading button when loggedin

---

gatsby-browser.js

Kevin/Fix gatsby-browser datalayer

---

src/pages/trade-types/margin/_policies.js

Kevin/Fix trade types margin - swap calculator link

---

src/pages/markets/components/helper/_available-platforms.js

Kevin/fix:market available platform alignment

---

src/pages/partners/affiliate-ib/index.js

Changes:
-   Fix affiliate ib button breaking for mobile

Sean / fix: affiliate ib button breaking for mobile

---

src/pages/payment-methods/_payment-data.js

Changes:
-   Remove dragon pay from payment method page

Sean / remove: dragon pay from payment method page

---

src/components/custom/platforms-dropdown.js
src/components/localization/language-dropdown.js
src/pages/home/_hero.js

Changes:
-   Reduce painting from dropdown animations

Sean / perf: reduce painting from dropdown animations

---

src/common/utility.js
src/components/layout/besquare/footer.js
src/components/layout/besquare/nav.js
src/components/layout/besquare/style/nav.js
src/components/layout/nav-careers.js
src/components/localization/localized-link.js

Changes:
-   Update besquare link on career's page to direct to besquare page
-   Update besquare nav logo to redirect to homepage
-   Update besquare signup url

Sean / update: besquare link on careers page to direct to besquare page

---

src/components/custom/other-platforms.js
src/components/elements/card.js
src/components/elements/carousel/carousel-style.js
src/components/elements/off-canvas-menu.js
src/components/localization/localized-link.js

Changes:
-  Changed `button` to `div`
- Added missing `aria-label` props 

yashim/fix: accessibility score - links/buttons without discernible name

---

src/pages/besquare/static/style/_what-lies-ahead.js

Changes:
-   Fix besquare page accordion color

Sean / fix: accordion color

---

src/components/layout/nav.js
src/components/localization/language-dropdown.js
src/themes/device.js
src/themes/media.js

Changes:
-   Fix: broken `create new demo account` button for various languages on certain views

Sean / fix: broken create new demo account button for various languages on certain views

---

src/pages/besquare/components/sections/_description.js
src/pages/besquare/components/sections/_faq.js
src/pages/besquare/components/sections/_hero.js
src/pages/besquare/components/sections/_why-deriv.js
src/pages/besquare/index.js
src/pages/besquare/static/content/_advantages.js
src/pages/besquare/static/content/_application-process.js
src/pages/besquare/static/content/_faq.js
src/pages/besquare/static/content/_join-us.js
src/pages/besquare/static/content/_what-is-besquare.js
src/pages/besquare/static/content/_what-lies-ahead.js
src/pages/besquare/static/content/_who-can-apply.js

Changes:
-   translate: remove localization for besquare page

Sean / translate: remove localization for besquare page

---

src/components/layout/nav-careers.js
src/components/layout/nav-p2p.js
src/components/layout/nav.js
src/components/localization/language-dropdown.js

Changes:
-   Fix: broken partners page navbar due to the homepage navbar fix
-   TODO: Properly refactor our `Nav` component once the dropdown menu refactor PR is merged

Sean / fix: broken partners page navbar

---

src/pages/partners/payment-agent/_your-control.js

Changes:
-   Fix: cards discrepancies for screen widths >1980px

Sean / fix: cards discrepancies for screen widths >1980px

---

src/pages/home/_trade-types-mobile.js
src/pages/home/_trade-types.js

Kevin/ remove options link on EU countries

---

src/common/utility.js
src/components/custom/_signup-new.js

mitchell/Fix for t & c language fix at signup page

---

src/components/layout/nav.js

Changes:
- Added interval to check cookie changes.

yashim/fix: check for cookie changes to update navbar button

---

src/pages/besquare/static/content/_application-process.js
src/pages/besquare/static/style/_application-process.js

Sean / fix: empty space

---

src/components/custom/_signup-new.js

Changes:
-   Fix: duplicated signup header & subtitle

Sean / fix: duplicated signup header & subtitle

---

gatsby-config.js

Changes:
-   reset gatsby sharp options to default

Sean / reset gatsby sharp options to default

---

src/components/hooks/use-livechat.js

Changes:
-   Set fallback for client information before JSON.parse to avoid throwing an error

Sean / fix: unexpected token in JSON track js error

---

src/pages/help-centre/account.js

Changes:
- redirect password reset link to a new page
-   ...

fiona/ redirect password reset to a new page

---

src/components/layout/nav.js

Changes:
-  Fix react minified error by directly set callback function as param inside useOutsideClick in nav.js.
-  Removed  MemoizeNavbarDesktop and MemoizeNavbarMobile

Nuri/Fix:Minified react error

---

src/pages/home/_hero.js

Changes:
-   Refactor hero container on the homepage from a grid layout to a flex layout
-   Fix overlapping text over the CTA button for VI language

Sean / fix: overlapping text over create free demo account button

---

src/pages/trade-types/margin/_policies.js

remove hyphen from stop loss

---

src/pages/about/_our-offices.js

Kevin/feat: add Belarus (Minsk) on our story page & update office number

---

src/pages/markets/instruments/_market-symbols.js
src/pages/markets/static/content/_details.js
src/pages/markets/static/content/_margin.js

Changes:
> remove step-fx from forex
-   ...

arome/ remove step-fx

---

src/components/containers/seo.js
src/components/layout/besquare/footer.js
src/components/layout/footer.js

Changes:
-   Remove facebook social links

[Prod]Remove facebook links

---

.circleci/config.yml

Changes:
-   Limiting resource usage in hopes of passing circle ci builds

Adjusted docker resource usage

---

.circleci/config.yml

Changes:
-   To the Max of what Medium can offer

Reduced CPU Usage to 2

---

.circleci/config.yml
src/pages/home/_hero.js

yashim/fix: home page overlapping text

---

src/pages/payment-methods/_payment-data.js

fix: hide unused component

---

src/pages/why-choose-us/_icon-grid.js

yashim/copy: updated why choose us copy + added hyperlinks to text.

---

deriv.com.conf

Add cache policy

---

deriv.com.conf

fix cache issue

---

src/components/custom/_signup-new.js

Changes:
- fix banner box height in signup to not overflow on mobile
-   ...

Hojjat / fix banner box in signup

---

src/components/custom/_signup-new.js

Changes:
-   Fix: social button signup page text alignment

Sean/fix: social button signup alignment

---

src/components/form/input.js

Changes:
-  resize font-size for reset password input field
-   ...

arome/ resize reset password font size

---

src/pages/regulatory/index.js

Changes:
-   Update regulatory page wording to include DXTrade

Sean/update regulatory page wording to include DXTrade

---

src/pages/regulatory/index.js

Reverts binary-com/deriv-com#1575

Revert "Sean/update regulatory page wording to include DXTrade"

---

src/common/utility.js
src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer.js
src/components/localization/localized-link.js
src/pages/contact_us/_contact-ways.js
src/pages/help-centre/_community.js

Changes:
-   Fix: remove external link behaviour for blog and community links

Sean/fix: remove external link behaviour for blog and community links

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer.js
src/pages/dmt5/_margin_calculator.js
src/pages/home/_trade-types-mobile.js
src/pages/home/_trade-types.js
src/pages/trader-tools/margin-calculator/_margin-calculator.js

Changes:
- end trade card pages with a slash
-   ...

fiona/ end trading platform and trade-type pages url with a slash

---

src/components/custom/other-platforms.js
src/components/elements/card.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer.js
src/components/localization/localized-link.js
src/pages/contact_us/_contact-ways.js
src/pages/help-centre/_community.js

Changes:
-   Fix: redirects to 404 page on community and blog links for other languages

Sean/fix: redirects to 404 page on community and blog links for other languages

---

src/pages/home/_hero.js

Changes:
-   Fix: hero overlapping header for some languages

Sean/fix: hero overlapping header for some languages

---

src/pages/dmt5/_dhero.js
src/pages/dmt5/_flexibility.js
src/pages/dmt5/_what-is-trader.js
src/pages/dmt5/index.js

Nuri/Update:Update dmt5 page

---

src/common/constants.js
src/common/login.js

Changes:
-  Add check, if domain is deriv.me, use a different app_id for login

yashim/hotfix: deriv.me login deriv app id

---

src/pages/payment-methods/_expanded-list.js

fiona/ resize hover arrow

---

src/components/custom/_dnumbers.js
src/components/layout/nav.js

Changes:
-    Bug fix
-    Style only

fix partners page design

---

src/components/custom/_dnumbers.js
src/components/layout/nav.js
src/pages/partners/affiliate-ib/index.js

mahdiyeh/fix: affiliate_page_numbers

---

src/pages/trade-types/options/_options-to-trade.js

fiona/remove unused call/put spreadgrid

---

src/components/custom/platforms-dropdown.js
src/pages/home/_trade-the-way-you-like.js
src/pages/home/_trade-types-card.js
src/pages/markets/components/helper/_available-trades.js
src/pages/markets/components/sections/_other-markets.js
src/pages/payment-methods/_expanded-list.js
src/pages/payment-methods/index.js
src/pages/trader-tools/common/_style.js

Changes:
-  Updated all instances of hex code to use color variables instead

yashim/refactor: hex code to use color variables

---

.circleci/config.yml

add blue/green deployment on production

---

src/pages/markets/static/content/_margin.js

Changes:
-  Fix enclosing brackets

yashim/hotfix: fixed enclosing brackets

---

src/pages/contact_us/_offices.js
src/pages/contact_us/index.js

Changes:
-   Fix contact us typo

yashim/fix: contact us typo

---

src/common/constants.js
src/pages/trade-types/margin/_start-trading.js

Changes:
-  Added dmt5#demo links
-  Redirect user to mt5#demo link after click 'Create a demo DMT5 account' button in Margin Trading page.

Nuri/Fix : redirect user to mt5#demo link after click the button

---

src/components/layout/nav.js

 Kevin/hotfix ib page - login button

---

src/pages/story/_our-offices.js

Changes:
-   Fixed the issue of our story page been truncated on larger screens 🤞

Al-amin/33353/hotfix_our_story_page_truncated

---

src/pages/regulatory/index.js

Reverts binary-com/deriv-com#1628

Revert "Revert "Sean/update regulatory page wording to include DXTrade""

---

gatsby-node.js
src/common/constants.js
src/pages/derivx/_start-derivx.js
src/pages/dmt5/components/_side-tab.js

Sean/remove redirection & added download links for appstore and playstore

---

src/components/custom/_dhero-2.js

Sean/fix: logo alignment

---

src/pages/leadership/_leaders.js

Changes:
-   fixed cropped image and removed bottom padding in Leadership page
-   [X] Style only

Nuri/Fix: fixed cropped image and removed bottom padding

---

src/components/layout/besquare/footer.js
src/pages/besquare/static/content/_faq.js

Changes:
-   delete: 
- a)in _faq obj with dateline 
- b)in footer string with dateline

nikolai.berestevich fix: task34144 remove closing dateline besquare

---

src/components/form/input.js

Changes:
-   Fix: global form label styling

Sean/fix: global form label styling

---

src/pages/derivx/_accounts.js

Sean/fix: copywriting

---

src/components/layout/footer/bottom-social-wrapper.js
src/components/layout/footer/logo.js
src/components/layout/nav-careers.js

Kevin/ fix deriv career page social media links

---

src/components/custom/_signup-public.js

Changes:
New Deriv Banner at homepage breaks at certain px

Habib/Landing Page Signup Hotfix 

---

.github/workflows/staging.yml

Make Deriv-com repo build staging upon each merge to master branch

---

deriv.com.conf

To redirect all language routes for careers page to the default one

---

src/components/custom/_signup-public.js

Habib/landing Fullscreen background

---

gatsby-browser.js
src/common/constants.js
src/common/live-chat-redirection-checking.js
src/common/utility.js
src/components/hooks/use-open-live-chat-redirection.js
src/pages/contact_us/index.js
src/pages/index.js

Changes:
-   Added params to allow livechat box to open after redirection from email (only for en)

Nuri/fix: Live chat popup redirection from email

---

src/pages/trade-types/margin/_start-trading.js

Changes:
-   Start trading on margin with Deriv: button changed to Create free account (text and redirect)

nikolai-berestevich fix #34497 Start trading on margin with Deriv: button changed to Create free account

---

src/pages/landing/ebooks/forex.js

add forex text change

---

gatsby-browser.js

Changes:
-  Swallow any exceptions thrown by pushwoosh. Usually this is a bad idea but since it is a third-party SDK, we wont have any control to fix the error (the purpose of showing exceptions/errors)

yashim/fix: pushwoosh trackjs errors

---

gatsby-config.js
gatsby-node.js
package.json

yashim/hotfix: will test gatsby js files in root folder. fix eslint errors during built

---

src/pages/home/_what-our-clients-say.js

yashim/hotfix: testimony images

---

.eslintrc

Changes:
-   Remove annoying error when using console logs in dev mode

Change eslint no-console error to warning

---

src/pages/markets/components/sections/_hero.js

Kevin/Market page - change header video

---

gatsby-browser.js
package-lock.json
package.json

Changes:
-   Replaced current `web-push-notifications` library with `@deriv/web-push-notifications` maintained by @mustofa-binary 

amam/yashim/fix: trackjs pushwoosh errors

---

src/pages/dmt5-trading-signals/index.js

Changes:
-  styled component doesn't rerender with new props during the first loading of the page. So i added new variable to fix it

Nikolai.berestevich signal provider highlight 28666

---

src/components/elements/typography.js
src/components/hooks/use-page-loaded.js
src/pages/help-centre/_help-centre-style.js
src/pages/help-centre/account.js
src/pages/help-centre/dbot.js
src/pages/help-centre/deposits-and-withdrawals.js
src/pages/help-centre/deriv-x.js
src/pages/help-centre/dmt5.js
src/pages/help-centre/dtrader.js
src/pages/help-centre/security.js
src/pages/help-centre/trading.js

Changes:
-  styled component doesn't rerender with new props during the first loading of the page. So i added new  hook and variable to fix it 
-   change "href" to "to" in props of the ExternalLink  (as it should be - fix of  the empty pages in the /help-centre/dmt5)

nikolai.berestevich/fix/help-centre-titles-highlight 36523

---

gatsby-browser.js

Changes:
-   Getting `userId` from cookies and sending it with gtm `page_load` events

khalid/added userId to page_load gtm events

---

src/pages/dmt5-trading-signals/index.js

Sean/fix: eslint errors

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer/main-links.js
src/pages/home/_hero.js
src/pages/markets/commodities/index.js
src/pages/markets/components/sections/_nav-tab.js
src/pages/markets/cryptocurrencies/index.js
src/pages/markets/forex/index.js
src/pages/markets/index.js
src/pages/markets/stock/index.js
src/pages/trade-types/margin/_available-markets.js
src/pages/trade-types/options/_how-options-works.js
src/pages/trade-types/options/_markets-available.js

Kevin/update stock indices to stocks and indices on header, footer, and market

---

src/components/custom/_dtrading.js
src/pages/derivx/_hero.js
src/pages/derivx/_start-derivx.js
src/pages/derivx/_what-is-derivx.js
src/pages/derivx/_why-trade-derivx.js
src/pages/derivx/index.js

Changes:
-   Added SEO for Deriv X
-   [X] New feature

Nuri/Feat : Deriv x seo changes

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer/main-links.js

Changes:
-   footer, header, mobile header : blog's links changed to '/blog'

nikolai.berestevich/feat/update links to blog page

---

src/components/custom/_agreement-label.js
src/components/custom/_signup-new.js

Changes:
-   Lower the gap between label and 'Create Demo Account' button
-   [X] Style only

Nuri/fix : Fix gap on signup page

---

src/pages/careers/_model/_locations/_locations.js
src/pages/contact_us/_offices.js

Changes:
-   update links of the Minsk office

Nikolai.berestevich/fix/update minsk office link 37500

---

src/components/custom/_signup-public.js
src/pages/home/_what-our-clients-say.js

Changes:
-changes to decrease too big padding between " Testimonial" and "sign up "Banner in the bottom of the page
-fix "sing up" banner on the screen's width < 340px
-   [x ] Style only

Nikolai.berestevich/fix/homepage paddings

---

src/pages/dmt5/_flexibility.js

Mahdiyeh/Fix: compare_accounts_content_for_eu_conuntries

---

src/pages/story/_our-numbers.js

Changes:
-   numbers were updated on story page
-   [ x ] Translation to crowdin

nikolai.berestevich/text/update numbers on story page

---

src/components/layout/footer/main-links.js
src/pages/markets/components/markets/_cryptocurrencies.js
src/pages/markets/components/sections/_hero.js
src/pages/markets/index.js

Changes:
-   1) Update Market Cryptocurrency link in footer
-   2) Update Leverage and Crypto Pairs value

Nuri/update: Crypto cr and eu update

---

src/components/layout/footer/disclaimer.js
src/pages/regulatory/index.js

Changes:
-  inks update for DMX and DEL in footer and  /regulatory

nikolai.berestevich/fix/links update for DMX and DEL

---

gatsby-config.js
gatsby-node.js

Changes:
- Remove localized BeSquare pages
- Remove localized BeSquare pages from sitemap
- Combined excluded pages into a single regex

Sean/Remove BeSquare language pages

---

src/pages/landing/ebooks/components/_get-ebook.js

Changes:
-  top margin  for button was added on landing/ebooks/forex
-   [ x ] Style only

nikolai.berestevich/style/botton margin on landing/ebooks/forex

---

src/common/constants.js
src/components/custom/_agreement-label.js
src/components/localization/localized-link.js

Changes:
-   refactor code to delete '/en/' in the link 

Nikolai.berstevich/fix/update link to terms 38541

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/pages/home/_markets.js
src/pages/home/_trade-types-mobile.js
src/pages/home/_trade-types.js
src/pages/index.js

Changes:
-   alt tags for icons were changed to "" on /homepage + common components

nikolai.berestevich/fix/delete  alt tags for icons /homepage + some common components

---

src/components/elements/off-canvas-menu.js
src/components/localization/language-dropdown.js
src/pages/landing/index.js
src/pages/markets/commodities/index.js
src/pages/markets/components/helper/_available-platforms.js
src/pages/markets/components/helper/_available-trades.js
src/pages/markets/components/helper/_markets_accordion.js
src/pages/markets/components/markets/_commodities.js
src/pages/markets/components/markets/_cryptocurrencies.js
src/pages/markets/components/markets/_forex.js
src/pages/markets/components/markets/_stock-indices.js
src/pages/markets/components/markets/_synthetic-indices.js
src/pages/markets/components/sections/_other-markets.js
src/pages/markets/cryptocurrencies/index.js
src/pages/markets/forex/index.js
src/pages/markets/index.js
src/pages/markets/static/content/_commodities.js
src/pages/markets/static/content/_stock.js
src/pages/markets/static/content/_synthetic.js
src/pages/markets/stock/index.js
src/pages/markets/synthetic/index.js

Changes:
-   delete  alt tags for icons /markets 39155

nikolai.berestevich/refactor/delete  alt tags for icons /markets 39155

---

package.json

Changes:
-   Enable gatsby incremental builds

Sean/feat: enable gatsby incremental builds

---

src/pages/dmt5-trading-signals/_signal-steps.js

Kevin/DMT5 Signal change text content

---

src/pages/dmt5-trading-signals/_signal-steps.js

Reverts binary-com/deriv-com#1951

Revert "Kevin/DMT5 Signal change text content"

---

src/components/custom/_dhero-2.js
src/components/graphql/fragments.js
src/pages/landing/ebooks/forex.js
src/pages/landing/ebooks/stocks.js

Changes:
-   Forex/Stock Landing page Gatsby Image Color fix

Add Placeholder None Fragment

---

package-lock.json
package.json

Hojjat / update web push notification

---

src/pages/derivx/_why-trade-derivx.js
src/pages/landing/stocks/_whyTradeWIthUs.js
src/pages/landing/stocks/index.js

Changes:
-   alt tags were changed to empty for images 

Nikolai.berestevich/refactor/remove alt tags landing derivx 40113

---

src/pages/regulatory/index.js

Kevin/Update sentence for regulatory - vanuatu

---

README.md

Hojjat / update sonar badges links

---

.github/workflows/production.yml
.github/workflows/staging.yml
package.json

Changes:
-   Cache public and cache directories during GH actions build for Gatsby incremental builds
-   Changes made to add a new step `cache gatsby` & also removing excess lint step in `production.yml`

Sean/cache public and cache directories during GH actions build

---

src/pages/interim/faq/_faq.js

Reverts binary-com/deriv-com#1996 that was used for testing purposes

Revert "Sean/test rebuild"

---

src/pages/check-email/_icon-grid.js
src/pages/interim/_everything.js

Changes:
-   empty alt tags for check-email and interim pages

nikolai.berestevich/fix/empty alt tags check-email and interim pages

---

src/pages/p2p/components/_availability.js
src/pages/p2p/components/_exchange-steps.js
src/pages/responsible/_securing-account.js
src/pages/responsible/_trading-responsibly.js

Changes:
-   alt-tags for p2p for responsible

nikolai.berestevich/refactor/alt-tags for p2p for responsible

---

gatsby-config.js
gatsby-node.js
src/components/elements/dot-loader.js
src/pages/livechat/index.js

Changes:
-   Created a standalone page for live chat

Al-amin/39978/standalone page for live chat

---

src/common/validation.js

Changes:
-   Failed Sign up redirected add fix regex Issue fix

Habib/  Failed Sign up redirected to successful signup page  

---

src/pages/careers/_model/_locations/_contact-details.js
src/pages/contact_us/_offices.js

Changes:
-   Hotfix for paraguay address in help center and career page

Nuri/fix: hotfix for paraguay address in help center and career page

---

src/pages/help-centre/deriv-x.js

Prince/ removed real text from FAQ page

---

src/pages/help-centre/_help-articles.js
src/pages/help-centre/deriv-x.js

Changes:
-   Enable Deriv X password FAQs

Sean/show Deriv X password FAQs

---

src/pages/help-centre/_help-articles.js
src/pages/help-centre/deriv-x.js

Sean/update deriv x password FAQs

---

gatsby-config.js

update CMS endpoint

---

src/pages/blog/components/_hero.js

Carousel height fix mobile

---

src/pages/academy/_recent-featured-posts.js
src/pages/academy/blog/_article-card.js
src/pages/academy/blog/_first-article.js
src/pages/academy/blog/posts/preview/index.js
src/pages/academy/components/_side-subscription-banner.js
src/pages/academy/components/video-banner/_DBanner.js
src/pages/academy/components/video-banner/_VideoCarousel.js
src/pages/academy/components/video-banner/carousel/_carousel-style.js
src/pages/academy/videos/_video-card.js
src/templates/article.js

Changes:
-   Code cleanup for Preview, Side Subscription Banner, Dbanner, Video Carousel and Carousel styles components

Nuri/refactor :  Code cleanup for Preview, Side Subscription Banner, Dbanner, Video Carousel and Carousel styles components

---

src/pages/academy/components/_side-subscription-banner.js

Changes:
-  side subscribe banner focus

nikolai.berestevich/fix/side subscribe banner focus

---

src/pages/academy/blog/posts/_style.js

Changes:
-   Add italic styling in blog content

sean/feat: add italic styling in blog content

---

src/pages/academy/components/_subscribe.js

Changes:
-  onFocus was deleted 

nikolai.berestevich/fix/blog-subscribe-touched

---

src/pages/p2p/components/_hero.js
src/pages/p2p/index.js

Changes:
-   bug of the second hero-component  is fixed

nikolai.berestevich/fix/p2p-page-hero-2-time

---

src/pages/help-centre/_community.js
src/pages/help-centre/index.js

Reverts binary-com/deriv-com#2084

Revert "feat: visibility to crawler on help centre index"

---

src/pages/help-centre/_community.js
src/pages/help-centre/index.js

Reverts binary-com/deriv-com#2092

Revert "Revert "feat: visibility to crawler on help centre index""

---

src/pages/story/_our-offices.js

Changes:
-   Change team members 500+ to 600+

change team members

---

src/pages/story/_our-offices.js

Changes:
-   Change map location url

add map URL change

---

src/pages/landing/ebooks/components/_introduction.js
src/pages/landing/ebooks/components/_topics.js

Changes:
-  width: 16px; height: 16px;  are added  for icons
-   height="462 px" - for image near array 
-   [ x ] Improve performance

nikolai.berestevich/fix/ebooks page: image loading speed

---

documents/file-structures.md
gatsby-config.js
src/components/hooks/use-active-link-state.js
src/components/layout/nav.js
src/pages/besquare/components/sections/_why-deriv.js

Changes:
-   links to /about page were replaced to /story page
- redirection from /about page link to /story page is not removed

nikolai.berestevich/fix/about-page link => story link

---

src/pages/academy/blog/posts/_style.js
src/pages/academy/blog/posts/preview/index.js
src/pages/academy/components/_markets-news.js
src/pages/academy/index.js
src/templates/article.js

Changes:
-   Change tags from market news to market report
-   Change font-size for article title on browser width > 1680

Nuri/fix :Change tags from market news to market report

---

src/pages/academy/index.js

Changes:
-   Fix internal link warning on console

fix: internal link warning on console

---

src/pages/academy/blog/index.js
src/pages/academy/index.js
src/pages/academy/videos/index.js

Changes:
-   Update layout type for blog pages

fix: update layout type for blog pages

---

.github/workflows/lint.yml

chore: update lint yml node version to v14

---

.eslintrc
.github/workflows/lint.yml

Changes:
-   chore: update eslint config to run typescript-eslint only for ts & tsx files

Update eslint config to handle typescript-eslint

---

src/components/layout/footer/disclaimer-academy.js
src/pages/academy/blog/index.js

fiona / fix: text issues on deriv blog

---

src/pages/partners/affiliate-ib/_deriv-ib-programme.js

Mahdiyeh/ fix: forex and metals commission for financial accounts

---

src/pages/help-centre/account.js

Changes:
-  added Belarus & Rwanda to the list of restricted countries in a help centre article.

Maryia/text: added Belarus & Rwanda to help centre article

---

src/pages/home/_what-our-clients-say.js

Changes:
-  TP widget Size scale down

Habib/TP widget Size scale down

---

src/common/validation.js
src/pages/academy/components/_side-subscription-banner.js
src/pages/academy/components/_subscribe.js

Changes:
-   Side subscription banner field (name and email) validation

Nuri/fix : Side subscription banner field validation

---

src/pages/academy/blog/posts/_style.js
src/pages/academy/blog/posts/preview/index.js

fix: restrict author image size

---

src/common/utility.js
src/pages/academy/_recent-featured-posts.js
src/pages/academy/blog/_article-card.js
src/pages/academy/blog/_first-article.js
src/pages/academy/blog/posts/_style.js
src/pages/academy/common/_styles.js
src/pages/academy/components/_markets-news.js
src/pages/academy/components/recent-featured-posts/_style.js
src/pages/academy/components/video-banner/_VideoCarousel.js
src/pages/academy/components/video-banner/carousel/_carousel-style.js
src/pages/academy/videos/_video-card.js
src/templates/article.js

Changes:
-  Fixed images based on new design

NJ/Fix: New image dimension

---

src/pages/academy/_recent-featured-posts.js
src/pages/academy/components/recent-featured-posts/_style.js
src/pages/academy/components/video-banner/_DBanner.js
src/pages/academy/index.js

Changes:
-   replace vertical carousel with overflow scroll

feat: replace vertical carousel with overflow scroll

---

src/pages/landing/deriv-go/_what-is-deriv-go.js

Changes:
- top padding added to numbers wrapper in responsive mode  

fiona / update deriv go landing page

---

src/components/layout/footer/common/style.js

Changes:
-   Black space shows up when scrolling the page to the left in size of 995px

Pavel latyshou/black space 995px

---

src/pages/academy/blog/_first-article.js
src/pages/academy/blog/posts/_style.js
src/pages/academy/components/_markets-news.js
src/pages/academy/components/_side-subscription-banner.js
src/templates/article.js

fix: missing margin on market news section on mobile

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/pages/dmt5/index.js
src/pages/interim/_everything.js
src/pages/landing/dmt5/index.js
src/pages/trader-tools/margin-calculator/_margin-calculator.js
src/pages/trader-tools/pnl-for-margin/_pnl-for-margin.js
src/pages/trader-tools/swap-calculator/_swap-calculator.js

sean/fix: update all deriv metatrader 5 to deriv mt5

---

src/pages/landing/ebooks/components/_get-ebook.js
src/pages/trade-types/multiplier/_how-multiplier-works.js

Changes:
-   Update multiplier value copywriting

fix: multiplier value copywriting change

---

src/pages/dmt5/_margin_calculator.js

Kevin/ remove extra sentence

---

src/pages/academy/components/recent-featured-posts/_style.js

style: update scrollbar style

---

src/components/layout/footer/disclaimer.js

Prod: Prince/Added footer text

---

src/pages/academy/blog/posts/preview/index.js

feat: add auth token to preview link

---

src/pages/academy/blog/posts/preview/index.js

chore: add public token for preview page

---

.github/workflows/production.yml
src/components/containers/seo.js

Changes:
-   Added GATSBY_DERIV_VERSION env variable to production release workflow

khalid / version env variable

---

src/components/layout/footer/disclaimer.js

Prince/ Added footer text

---

src/components/elements/background-image.js
src/pages/academy/components/_hero.js
src/pages/academy/index.js

Changes:
-   Fixed blog carousel

NJ/fix: Fixed blog carousel

---

src/components/containers/box.js
src/components/containers/container.js
src/components/containers/flex.js
src/components/elements/typography.js

Changes:
-   add responsive style properties to container components
-   add responsive style properties to typography components

sean/feat: add responsive style properties to frequently used components

---

src/pages/academy/index.js

style: update inactive carousel dot colour

---

src/pages/careers/_besquare_bannner.js

Changes:
-   Recreate beSquare banner for Career Page

Nuri/fix:Recreate beSquare banner for Career Page

---

src/pages/academy/blog/posts/_style.js

Changes:
-   fix truncated tables for mobile devices

fix: truncated tables for mobile devices

---

src/pages/responsible/_securing-account.js

Changes:
-   Update secure account on responsible page

Nuri/Update: Update secure account on responsible page

---

src/pages/academy/components/_side-subscription-banner.js
src/pages/academy/components/_subscribe.js

Changes:
-   åçadd customerion type segment

add customerio type segment

---

src/templates/article.js

Changes:
-   fix is  made not to show external link pop-up for side and bottom banners ( in academy article template)

nikolai.berestevich/fix/academy-article-template banner fix

---

src/pages/academy/blog/index.js
src/pages/academy/components/_banner.js
src/pages/academy/index.js
src/templates/article.js

Changes:
-   Filter out test data blog posts from UI & set to no index

feat: filter out test data blog posts from UI & set to no index

---

src/pages/markets/commodities/index.js
src/pages/markets/cryptocurrencies/index.js

Changes:
-   Fixed Commodities tab cutoff
-   Fixed Cryptocurrencies tab cutoff

fixed mobile cutoff on market page

---

src/pages/academy/blog/posts/preview/index.js

Changes:
-   Hero banner issue on preview post

Nuri/Fix: Hero banner issue on preview post

---

src/pages/academy/blog/index.js
src/pages/academy/videos/index.js

Changes:
-  OG information for academy pages added to /academy/blog/ and /academy/videos/ pages

nikolai.berestevich/feat/OG information for academy pages

---

src/pages/regulatory/index.js

Prince/Update Deriv Limited's address

---

gatsby-node.js

Changes:
-   deriv.com/landing/ebooks/ doesn't have own page and user should be routed to our 404 page

nikolai.berestevich/fix/ redirect landing/ebooks to 404

---

src/pages/dmt5/_interest_free_trading.js

fiona /  redirect url to dmt5 real account

---

deriv.com.conf

Pavel-Latyshov/403 error message is displayed

---

src/pages/markets/components/markets/_forex.js
src/pages/markets/components/sections/_why-trade.js
src/pages/markets/static/content/_forex.js

Changes:
-   Fix missing icons on markets page

fix: missing icons

---

deriv.com.conf

Changes:
-   redirect old besquare link

chore: redirect old besquare link

---

src/pages/dmt5/_start-trader.js

Changes:
-   DMT5 - fixed alignment issue for real money tab

NJ/Fix : Fixed real money tab alignment

---

.github/workflows/production.yml

chore: remove repo dispatch trigger

---

src/components/localization/localized-link.js

Changes:
-   fix: white page error on blog

fix: white page error on blog

---

src/components/layout/footer/disclaimer-academy.js
src/components/layout/footer/disclaimer.js

add deriv mention in footer

---

src/components/containers/seo.js

yashim/fix: lang attrbute

---

src/components/layout/footer/disclaimer.js

fiona / remove reference of ireland from footer section

---

src/pages/regulatory/index.js

Changes:
-   ...
-   [x ] Documentation update

Pavel-Latyshou/DEL/MLT - remove references to Ireland from Regulatory page - Deriv 

---

src/pages/landing/forex-trading/components/_hero.js
src/pages/landing/trade-forex/components/_hero.js

behnaz / Fix fx spread lp

---

.github/workflows/content.yml

Changes:
added print statement to easily debug

print chosen git tag name for deployment

---

.github/workflows/content.yml

echo git tag

---

src/components/localization/localized-link.js

fiona / remove trailing slash on url

---

src/pages/payment-methods/index.js

Deriv P2P is appearing as the payment method for EU countries

---

src/pages/about-us/index.js

Changes:
-  1st section added 
-   [ x ] New feature

nikolai.berestevich/feat: add 1st section about-us

---

.github/workflows/content.yml

workflow change to deploy a latest production tag when submitted in cms system

Vijay content workflow

---

src/pages/home/_what-our-clients-say.js

Changes:
-   Remove the space between the content and Trustpilot

Al-amin/44981/remove the space between the content and trustpilot

---

src/pages/academy/components/_side-subscription-banner.js
src/pages/academy/components/_subscribe.js
src/store/index.tsx

Changes:
-   Add user country to subscribe form

Add user country to subscribe form

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer/main-links.js

Kevin/ fix  Binary Bot typos

---

src/pages/payment-methods/index.js

fiona / Style notice center for eu

---

src/components/elements/query-image.tsx
src/components/layout/nav.js
src/pages/security/_submit_a_bug_report.tsx
src/pages/security/vulnerabilities-types/index.tsx

Changes:
-   fixed bugs raised by qa (responsive layout, pop up modal, send email on new window)

fixed qa bugs

---

.github/CODEOWNERS

Changes:
-  Update list of codeowners

yashim/chore: update codeowners

---

README.md

Changes:
-   Added guideline on how to add env variables

Al-amin/Added guideline on how to add env variables

---

src/components/custom/_signup-new.js

Changes:
-   [Mobile responsive] Not able to scroll down to login with existing account in EU

Al-amin/[Mobile responsive] Not able to scroll down to login with existing account in EU

---

src/pages/why-choose-us/_icon-grid.tsx
src/pages/why-choose-us/index.tsx

Changes:
-   https://redmine.deriv.cloud/issues/51934#Mitra_/_Refactor_-_Convert_why_choose_us_page_to_TS

Mitra/Refactor: Convert why choose us page to TS

---

src/components/form/button.js
src/pages/academy/components/video-banner/_DBanner.js
src/pages/academy/components/video-banner/_VideoCarousel.js

- Add "See all videos" button to Desktop and Mobile layout in /academy page.
- Remove previous "See all videos" in Mobile layout to avoid duplicate buttons.

Mohammad/ Add "See all videos" button

---

src/components/form/button.js
src/pages/academy/blog/posts/_style.js
src/pages/academy/components/_hero.js
src/pages/academy/index.js

Changes:
-  New button type for Hero
-  Cta fixes for Hero - Deriv Academy

NJ/update: Added new button type

---

src/pages/about-us/_OurOffices.tsx

Kevin/Fix safari - office numbers bug

---

src/pages/about-us/_OurValues.tsx
src/pages/our-principles/index.tsx

Changes:
-   ColoredHeader media query changed
-  order of items changed

nikolai.berestevich/fix: order and text

---

src/pages/about-us/_MakeTrading.tsx
src/pages/about-us/_OurOffices.tsx
src/pages/about-us/_OurValues.tsx
src/pages/about-us/_data.ts

Kevin/fix: description, font styling on mobile

---

src/components/elements/off-canvas-menu.js
src/pages/about-us/_AboutUsBanner.tsx
src/pages/about-us/_OurLeadership.tsx
src/pages/about-us/_data.ts
src/pages/about-us/index.tsx

Changes:
-   tom fix 
- refactoring
-   [ x] Update feature
-   [ x] Refactor code

Nikolai.berestevich/fix/about us tom fix +refactoring

---

src/pages/about-us/_OurOffices.tsx

Pavel-Latyshov/Redirect page when clicking the office location is incorrect in languages other than EN

---

src/pages/careers/besquare/static/style/_card.ts
src/pages/careers/besquare/static/style/_hero.ts

fix: besquare tick icons margin

---

src/pages/about-us/_OurOffices.tsx
src/pages/careers/_model/_locations/_locations.ts

update guernsey office info

---

src/pages/about-us/_OurLeadership.tsx

Changes:
-   Tom's linkedin icon was removed

nikolai.berestevich/fix/tom2

---

src/pages/partners/_hero.js

Pavel-Latyshou/Design Difference: Deriv partners page

---

src/components/localization/language-dropdown.js

Pavel-Latyshou/On expanding language icon, few languages get hidden

---

src/pages/security/vulnerabilities-types/index.tsx

fix SEO title and description

---

src/components/layout/nav.js

Niloofar / add home page link to deriv logo in security page

---

src/components/layout/nav-careers.js
src/pages/academy/blog/_first-article.js
src/pages/contact_us/_contact-ways.js
src/pages/interim/affiliate/_hero.js
src/pages/interim/dbot/_hero.js
src/pages/landing/deriv-go/_banner.js
src/pages/landing/stocks/_headerSection.js
src/pages/leadership/index.js
src/pages/trader-tools/_tools.js

Changes:
Load Hero Images in first fold of various pages eagerly

Ako/ Load hero items images eagerly

---

src/pages/security/vulnerabilities-types/index.tsx

Pavel-Latyshov/Difference in box size under vulnerabilities-types page

---

src/pages/derivx/_accounts.js

fiona / update financial account with basket indices

---

.lintstagedrc

Changes:
-   Update lintstaged file extensions

chore: update lintstaged file extensions

---

src/components/hooks/use-livechat.js
src/components/layout/livechat.js
src/pages/livechat/index.js

Niloofar Sadeghi / Improve live chat performance

---

src/index.d.ts
src/pages/help-centre/_article.tsx
src/pages/help-centre/account.tsx
src/pages/help-centre/dbot.tsx
src/pages/help-centre/deposits-and-withdrawals.tsx
src/pages/help-centre/deriv-p2p.tsx
src/pages/help-centre/deriv-x.tsx
src/pages/help-centre/dmt5.tsx
src/pages/help-centre/dtrader.tsx
src/pages/help-centre/security.tsx
src/pages/help-centre/trading.tsx

Changes:
-   Help centre files with answers convert to TS 

 NikitaK/Help centre files with answers convert to TS

---

src/common/constants.js
src/components/layout/footer/disclaimer-academy.js
src/components/layout/footer/disclaimer.js
src/components/layout/layout.js

Mitra/Update CFD retail percentage

---

src/common/constants.js
src/components/layout/footer/disclaimer-academy.js
src/components/layout/footer/disclaimer.js
src/components/layout/layout.js

Reverts binary-com/deriv-com#2484

Revert "Mitra/Update CFD retail percentage"

---

src/components/containers/index.js
src/components/containers/visibility.tsx

Prince/ New show component

---

src/components/elements/query-image.tsx

fix: failed build

---

.eslintrc
.stylelintrc

Fix eslint rules

---

src/components/form/button.js
src/pages/careers/locations/_location-layout-new-offices.tsx
src/pages/careers/locations/_location-layout.tsx

Pavel-Latyshov/fixes to locations

---

README.md
documents/typescript-guidelines.md

Changes:
-   Add TS guidelines to Readme

Mohammad/ Add TS guidelines to Readme

---

src/components/localization/localized-link.js

fiona / fix SEO 404 errors

---

src/pages/landing/signup/index.tsx
src/pages/signup/index.tsx

Changes:
-   Convert signup and landing-signup pages to TS

Mohammad/ Convert signup and landing-signup to TS

---

gatsby-browser.js
src/common/constants.js
src/common/websocket/config.js

Changes:
-   Added deriv.be to the list of supported domains
- Added an app ID for deriv.be

khalid/add deriv.be domain

---

src/components/layout/nav.js
src/pages/landing/deriv-go/_why-trade-deriv-go.js
src/pages/landing/trade-forex/components/_icon-text-row.js
src/pages/markets/components/helper/_markets_accordion.js

Changes:
Remove px from width and height attributes of img tags due to preact code style

Ako/ Fix img attributes size bug

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer/main-links.js

Mitra/Replace `Deriv Go` with `Deriv GO`

---

gatsby-browser.js
src/common/constants.js
src/common/websocket/config.js

Reverts binary-com/deriv-com#2368

Revert "khalid/add deriv.be domain"

---

src/components/layout/nav.js

Changes:
Move width of hamburger menu element inside it's styled-component

Ako/ fix hamburger menu width

---

src/pages/p2p/components/_p2pbanner.js

nikolai.berestevich/fix/p2p-route

---

src/common/utility.js
src/components/layout/nav.js

Changes:
This is intended to handle the preact problem on getting element api s from passed ref to the element

ako/ add method to get base ref of passed element

---

src/pages/dmt5/_margin_calculator.tsx

Dmt5 copywriting change

---

gatsby-node.js

Changes:
-   redirection upd
-   [x ] Update feature

nikolai.berestevich/fixredirection

---

package-lock.json
package.json

Changes:
-   Bump pushwoosh version

yashim/chore: bump pushwoosh version

---

src/common/utility.js
src/pages/academy/components/_search-banner.tsx
src/pages/academy/search/index.tsx

fix: unencoded url for categories

---

src/components/graphql/academy-fragments.js
src/templates/article.js

chore: decrease image quality

---

src/pages/academy/common/_constants.ts
src/pages/academy/components/_social-sharing.js
src/pages/academy/search/index.tsx
src/pages/careers/_employee-testimonial-carousel.tsx

fix: preact missing images

---

src/types/generics.ts

Prince/ Added generic types

---

src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer/main-links.js
src/pages/partners/_deriv-numbers.js
src/pages/partners/_why-choose-us.js
src/pages/why-choose-us/index.tsx

Changes:
-   /who-we-are page title changed. 
-   who-we-are without "?" in the project

nikolai.berestevich/fix/why-choose-us

---

.lintstagedrc
package-lock.json
package.json
src/pages/dmt5-trading-signals/_how-to.tsx
src/pages/p2p/components/_dp2p.tsx

Changes:
-   Add svgo precommit step

Add svgo precommit step

---

src/components/hooks/use-debounced-effect.tsx
src/components/localization/config.js
src/pages/dmt5/_why-trader.tsx
src/pages/interim/_love-trading.tsx
src/pages/p2p/components/_hero.tsx
src/store/index.tsx

Changes:
- Fix ESLint warnings
- Help Centre warnings will be done in another PR as it requires a significant change in flow

yashim/fix: ts-eslint warnings

---

src/pages/landing/stocks/_dtrading.tsx
src/pages/landing/stocks/_footerBanner.tsx
src/pages/landing/stocks/_headerSection.tsx
src/pages/landing/stocks/_lazy-load.js
src/pages/landing/stocks/_lazy-load.ts
src/pages/landing/stocks/_parallelogram.tsx
src/pages/landing/stocks/_whyTradeWIthUs.tsx
src/pages/landing/stocks/index.tsx

Niloofar Sadeghi / convert stocks to ts

---

src/components/layout/footer/main-links.js

Mitra/Make Apps list in footer same as Trade list for EU

---

src/components/custom/other-platforms.js

Mitra/ Rename `Discover DMT5 now` to `Discover Deriv MT5 now`

---

src/components/layout/footer/disclaimer.js

Changes:
-   Added missing text

fiona / add missing text on footer

---

src/pages/home/_markets_fold.tsx

Changes:
-   Fix hidden card images in mobile version

Mohammad/ Fix HomePage Images

---

src/pages/home/_our_platforms.tsx
src/pages/home/platform-carousel/_mobile-platform-carousel.tsx

Mitra/Improve responsive UI for platform carousel on mobile

---

deriv.com.conf

Edit: added 5m cache expiry for pdf contents

---

src/components/layout/besquare/footer.js
src/components/layout/besquare/style/footer.js
src/pages/interim/_love-trading.tsx

Changes:
-   Added margin bottom for the footer for EU clients -besquare,dmt5 and dbot

Aswathy/Footer padding changed in EU clients

---

src/components/containers/visibility.tsx

Vijayasree/refactor: visibility component

---

src/pages/who-we-are/_data.tsx
src/pages/who-we-are/components/_hero.tsx

Changes:
-   Fix hero styles to dynamically fit various languages

Hero hotfix

---

src/pages/who-we-are/_AboutUsBanner.tsx
src/pages/who-we-are/_OurPrinciples.tsx
src/translations/es.json
src/translations/vi.json

Kevin/ hotfix who we are page

---

gatsby-config.js
package.json
src/components/graphql/academy-fragments.js
src/components/hooks/use-academy-data.tsx
src/pages/academy/index.js

Migration prep

---

src/pages/bug-bounty/_submit_a_bug_report.tsx
src/pages/bug-bounty/rewards.tsx

Kevin/ fix bugs

---

src/components/layout/nav.js

Niloofar Sadeghi / Fix hamburger-menu bug in partner nav

---

src/pages/responsible/_need-help.tsx

Vijayasree/ refactor: update responsible page to new Show component

---

src/pages/who-we-are/_OurOffices.tsx

Vijayasree/ refactor: update who-we-are to new-show-component

---

src/components/layout/layout.js
src/pages/academy/blog/index.tsx

Changes:
-
-   [X] New feature

Nuri/feat: added new prop for layout component to detect no scroll top

---

src/common/constants.ts

Changes:
-   add deriv be to domain list for redirection links

refactor: add deriv be to domain list

---

src/components/containers/visibility.tsx

Vijayasree/ adding className to desktop and mobile components

---

src/common/utility.js

Al-amin/fixed the redirection issue on staging

---

src/pages/home/_testimonial-carousel.js
src/pages/home/_what-our-clients-say.js

Changes:
-   increased margin-bottom in _ClientTestimonial_ to display date in responsive mode

fiona / add margin bottom in responsive mode

---

src/components/containers/seo.js
src/pages/trade-types/cfds/_mind-when-trading.tsx
src/pages/trade-types/cfds/_trading-cfd-increases.tsx
src/pages/trade-types/cfds/index.tsx

Changes:
-  SEO component update (to use keywords)
- /trade-types/cfds/ seo updates

nikolai.berestevich/fix/sfds-seo

---

src/pages/regulatory/index.tsx

Changes:
-   Updated the deriv investment (Europe) details missing line in the regulatory

Aswathy/Updated the Deriv Investments (Europe) Details

---

src/components/containers/section-container.js
src/components/elements/carousel/carousel-style.js
src/components/elements/divider.js
src/components/elements/link.js
src/components/elements/typography.js
src/components/form/input.js
src/pages/academy/components/video-banner/carousel/_carousel-style.js

chore: fix lint errors

---

src/pages/careers/besquare/index.tsx

Changes:
-   Fix wrong layout used for besquare page

fix: wrong besquare layout

---

src/common/constants.ts
src/common/utility.js
src/components/localization/localized-link.js

Niloofar Sadeghi / Fix broken terms and condition link for "zh-tw" and "zh-cn" language

---

src/common/constants.ts
src/components/layout/footer/main-links.js
src/components/localization/localized-link.js
src/pages/home/_markets_fold.tsx
src/pages/home/_platform-slideshow.tsx
src/pages/home/platform-carousel/_details.tsx
src/pages/home/platform-carousel/_mobile-platform-carousel.tsx
src/pages/home/platform-carousel/_utils.tsx

Fix platform external links

---

package-lock.json
src/pages/trade-types/multiplier/_synthetic-indices.tsx

Mohammad/ Remove boom/crash300 and add jump and step indices

---

src/components/hooks/use-window-size.tsx
src/pages/home/_markets_fold.tsx

fix: change row to uk check

---

package-lock.json
src/components/layout/footer/bottom-social-wrapper.js
src/components/layout/footer/disclaimer.js
src/components/layout/footer/logo.js

Changes:
-   Make UK footer description similar to EU description

MohammadH/ UK footer description similar to EU

---

src/components/custom/_signup-new.js

Changes:
-   Updated email consent text on signup form

Matin/Chore: Updated email consent text on signup form

---

.github/workflows/staging.yml

Changes:
-   add concurrency to avoid unnecessary builds

script: add concurrency to avoid unnecessary builds

---

src/pages/academy/blog/posts/preview/index.tsx

fix: missing previews

---

gatsby-config.js

New directus endpoint

---

gatsby-config.js
src/pages/academy/blog/posts/preview/index.tsx
src/templates/article.tsx

Changes:
-   add new share button in preview in Deriv Academy

NikitaK/Add new share buttons on preview page 

---

src/pages/trade-types/multiplier/_cfds.tsx
src/pages/trade-types/multiplier/_synthetic-indices.tsx

Reverts binary-com/deriv-com#2722

Revert "mehrzad / add dbot to multiplier"

---

src/components/custom/other-platforms.js

Update deriv x copywriting

---

src/common/utility.js
src/components/layout/layout.js

Al-amin/removed UK/EU redirection flag

---

src/components/hooks/use-website-status.js

Prince/Refactor Redirection changes build issue

---

src/pages/academy/blog/posts/_style.js

Changes:
-   Add styles for ordered list for HTML content

Add styles for ordered list

---

src/components/containers/visibility.tsx
src/pages/home/platform-carousel/_mobile-platform-carousel.tsx

MohammadH/ Use if else function instead of 'or' before map

---

src/components/layout/layout.js

MohammadH/ Remove redirecting from layout.js

---

src/components/containers/visibility.tsx
src/components/hooks/use-website-status.js
src/pages/home/platform-carousel/_desktop-platform-carousel.tsx
src/pages/home/platform-carousel/_details.tsx
src/pages/home/platform-carousel/_platform-slider.tsx
src/pages/home/platform-carousel/_utils.tsx

Prince/ Fixed undefined objects

---

src/pages/markets/components/sections/_nav-tab.js
src/pages/trade-types/options/index.tsx

Al-amin/fixed broken content if connect to EU/UK vpn

---

src/pages/home/_platform-slideshow.tsx

MohammadH/ Fix deriv-go suddenly showing in eu hero

---

src/components/containers/visibility.tsx
src/pages/derivx/index.tsx
src/pages/landing/deriv-go/_other-apps.js
src/pages/landing/deriv-go/index.js
src/pages/markets/components/markets/_forex.js
src/pages/trade-types/options/index.tsx

Prince/ Country based contents fix

---

src/pages/trade-types/multiplier/_cfds.tsx
src/pages/trade-types/multiplier/_synthetic-indices.tsx

Reverts binary-com/deriv-com#2743

mehrzad / add dbot to multiplier

---

src/pages/dtrader/index.tsx

Vijayasree/refactor: update dtrader with new show component

---

src/pages/home/platform-carousel/_platform-slider.tsx

Niloofar Sadeghi / Add Space between Our platforms and what our clients say about Deriv in new home page

---

src/pages/landing/forex-trading/components/_hero.tsx
src/pages/landing/forex-trading/components/_image-text-switching.tsx

Vijayasree/refactor:landing-forextrading to the new show component

---

src/pages/livechat/index.tsx

Vijayasree/refactor:convert Livechat to new Show component

---

src/pages/regulatory/index.tsx

Vijayasree/refactor: update regulatory page to new Show component

---

deriv.com.conf
gatsby-ssr.js

Proxy pass facebook pixel

---

deriv.com.conf
gatsby-ssr.js

Reverts binary-com/deriv-com#2821

Revert "Proxy pass facebook pixel"

---

src/common/constants.ts
src/components/custom/_agreement-label.js

Vijayasree/fix: terms and conditions link in staging redirecting to production page

---

src/common/utility.js

refactor: enable other eu countries not just nl

---

gatsby-config.js
src/common/constants.ts
src/pages/academy/blog/posts/preview/index.tsx
src/pages/academy/search/index.tsx
src/pages/academy/videos/_all-videos.tsx

Changes:
-   update cms endpoint for crowdin

Update cms endpoint for crowdin

---

src/pages/markets/components/markets/_cryptocurrencies.js

…pected redirecting to 404
Changes:
-   ...

MohammadH/ Fix crypto redirecting to 404

---

src/components/layout/academy/nav-academy.tsx

Changes:
-    scrolling down and up sometimes make empty header below navbar

NikitaK/Bug Scrolling the page up and down and sometimes empty white blank header is observed

---

src/pages/landing/stocks/_headerSection.tsx
src/pages/landing/stocks/index.tsx

Vijayasree/refactor: convert landing-stocks to new show component

---

src/pages/dmt5-trading-signals/_signal-steps.tsx

Vijayasree/refactor: dmt5 trading signals  page with new show component

---

src/pages/home/_markets_fold.tsx

style: Improvement for new homepage designs

---

src/pages/landing/trade-forex/components/_hero.tsx
src/pages/landing/trade-forex/components/_image-text-switching.tsx

Vijayasree/refactor: convert landing-trade-forex to new show component

---

src/components/elements/off-canvas-menu.js

Mitra/Add space for binarybot text in mobile menu 

---

src/pages/landing/ebooks/components/_get-ebook.tsx

behnaz / new msg added

---

src/components/layout/nav/nav-careers.tsx

habib.career page nav url fix

---

src/components/layout/footer.js
src/components/layout/footer/logo.js

Changes:
-   fix: sharing icons visible for non-eu countries

NikitaK/ Social Network Icons for Non - EU clients is moved above the footer.

---

src/pages/landing/ebooks/components/_get-ebook.tsx

Changes:
-   Add disclaimer for ebooks download

Add disclaimer for ebooks download

---

src/components/layout/footer.js

Changes:
-   fix: plecement of non-eu share iconsin footer

NikitaK/  Social network icons for Non -eu clients are shown above footer in mobile

---

src/components/layout/footer.js
src/components/layout/footer/disclaimer.js
src/components/layout/footer/logo.js
src/components/layout/footer/main-links.js

Changes:
-   change placement and behavior of sharing buttons

NikitaK/ Difference in header title and footer content 

---

src/components/elements/off-canvas-menu.js
src/components/layout/footer/main-links.js
src/components/layout/nav/components/partner/nav-partner-desktop.tsx

Aswathy/Renamed the affiliates and IBs

---

src/components/layout/footer/logo.js

Vijayasree/fix: wrong Social Icon URLs

---

src/common/utility.js

Redirection for eu only matching eu and staging-eu subdomain

---

.github/workflows/production.yml
.github/workflows/staging.yml

Changes:
-   Nginx image will be validated after build. If the validation won't get successful it will abort the build before image push.

nginx image validation

---

src/components/elements/off-canvas-menu.js

Mitra/fix: remove basket indices for eu and uk in mobile menu

---

src/pages/markets/components/sections/_other-markets.tsx

Mitra/fix: make carousel to auto scroll in other markets section

---

src/pages/bug-bounty/static/_scope_content.tsx
types/graphql.types.ts

 hotfix translation

---

src/pages/bug-bounty/static/_scope_content.tsx
src/pages/bug-bounty/static/_vulnerabilities-types-content.tsx

chore: string translation

---

src/pages/markets/components/sections/_hero.tsx

Vijayasree/fix: wrong market description for EU & UK

---

src/components/hooks/use-livechat.js
src/components/layout/livechat.tsx
src/pages/help-centre/_didnt-find-answer.tsx
src/pages/livechat/index.tsx
src/pages/partners/payment-agent/_faq-data.tsx
src/pages/regulatory/_financial_commission.tsx
src/store/index.tsx

Mitra/fix: live Chat re-enable pre-loading for all pages

---

src/components/layout/layout.js

MohammadH/ Fix new connection created when page load until hitting rate limit

---

src/pages/dmt5/_flexibility.tsx
src/pages/dmt5/_interest_free_trading.tsx
src/pages/dmt5/_what-is-trader.tsx
src/pages/dmt5/_why-trader.tsx

* fix: content changes on mt5 page for eu and uk
* fix: small content change
Changes:
-   ...

Mitra/Fix mt5 page content for eu and uk (#2915)

---

src/pages/academy/common/_constants.ts
src/pages/academy/components/_search-banner.tsx

Changes:
-   Filter out restricted categories from category dropdown based on geolocation

Filter out restricted categories based on geolocation

---

src/components/elements/off-canvas-menu.js
src/components/layout/footer/main-links.js
src/components/layout/nav/components/nav-desktop.tsx
src/components/layout/nav/components/partner/main-nav.tsx

chore: fix header issue

---

.github/workflows/lighthouse.yml

Changes:
-   Fix our lighthouse runner

yashim/fix: vercel preview link fetching

---

src/common/constants.ts
src/components/custom/other-platforms.js
src/components/elements/off-canvas-menu.js
src/components/layout/footer/main-links.js
src/components/localization/localized-link.js

Changes:
-   fix: hyperlinks for derivlife in different languages in several parts
of the app

Mohsen/ fix: fix hyperlinks for derivlife in different languages

---

gatsby-config.js
package.json

build: seo canonical gatsby plugin added

---

src/components/layout/nav/nav-interim.tsx

Mitra/fix: make the trade forex landing page navbar same as production

---

src/components/elements/off-canvas-menu.js

Changes:
-   Added the redirect link arrow for mobile view for derivlife

Aswathy/ fix: Added the Redirect arrow for derivlife

---

src/pages/help-centre/account.tsx

Changes:
-   updated the content of "why can't I create account? " question in help centre.

Mohsen/ updated content of help centre

---

package-lock.json

Prince/ updated package-lock.json

---

src/pages/markets/components/sections/_other-markets.tsx

Changes:
-  "other markets" block by eu & uk domain in mobile version

NikitK/ For EU & UK incorrect markets is displayed under "other markets you might be interested in" - For Android & IOS 

---

gatsby-config.js

Changes:
-   change path in gatsby config

 NikitaK/ 404 console error when load video in Deriv academy 

---

src/pages/academy/search/_article-card.tsx

Vijayasree/feat: removing tags from search results in academy

---

gatsby-config.js

Aswathy/ fix: Scroll bar in safari browser color issue

---

src/common/utility.js
src/components/containers/visibility.tsx
src/pages/endpoint/index.tsx

…dpoint page for testlinks
Changes:
-   ...

MohammadH/ Disable auto redirection in testlink

---

src/pages/home/_markets_fold.tsx

Al-amin/fixed Basket indices typo

---

src/pages/markets/components/sections/_other-markets.tsx

Aswathy/fix: Overlap between the text and CTA in the Markets page

---

src/pages/home/_markets_fold.tsx

Reverts binary-com/deriv-com#2960

Prince/ Revert "Al-amin/fixed Basket indices typo"

---

src/common/constants.ts

Changes:
-   ...
-   [x ] Documentation update

Pavel/Update the % of CFD Retail clients losing money (Deriv.com) 

---

src/pages/partners/payment-agent/_p2p_banner.tsx

Changes:
-   fix styles which looks badly in zoom 75%

NikitaK/ On Payments Agent page P2P Banner doesn't have enough margin on zooming 

---

src/components/elements/off-canvas-menu.js

Vijayasree/fix: spacing issue after basket indices in mobile navigation

---

src/pages/markets/components/sub-markets/_cfds.tsx

chore: remove unused import

---

src/components/containers/visibility.tsx
src/pages/academy/blog/posts/preview/index.tsx
src/templates/article.tsx

Vijayasree/refactor: academy and template page with new show component

---

src/pages/home/_markets_fold.tsx

MohammadH/ Fix: rename basket indicies to basket indices

---

src/components/layout/nav/nav-interim.tsx
src/components/layout/nav/styles/nav-styles.ts

behnaz / fix: mobile-derivlogo

---

src/components/elements/off-canvas-menu.js

Changes:
-   Removed the arrow for non external links

Aswathy/ fix: removed the arrow 

---

src/pages/academy/blog/_article-card.tsx
src/pages/academy/common/_styles.ts
src/pages/academy/components/video-banner/_VideoCarousel.tsx
src/pages/academy/videos/_video-card.tsx

Changes:
-   change size of video thumbnails in Deriv Academy

NikitK / Task - Placeholder for videos is not 5:3 - Deriv Academy 

---

src/components/hooks/use-academy-data.tsx
src/pages/academy/search/_use-academy-blog-data.tsx
src/pages/academy/search/index.tsx

MohammadH/ Fix academy deploy error

---

src/components/layout/binary-to-deriv/_disclaimer.js

fix: update the cfd retial percentage in move to deriv landing page

---

src/components/hooks/use-academy-data.tsx
src/pages/academy/blog/index.tsx
src/pages/academy/videos/index.tsx

fix: deploy error by changing image aspect ratio

---

src/components/hooks/use-academy-data.tsx
src/components/layout/footer/disclaimer.js

Mitra/fix:New footer changes

---

src/pages/regulatory/index.tsx

Changes:
-  update text and design in regulatory page

NikitK/ Changes in the regulatory information document is not reflected in staging

---

src/pages/academy/components/video-banner/_DBanner.tsx

Changes:
-   fix a bug with header while video playing in Deriv Academy

 NikitK/ Bug Fix - Academy Videos View

---

src/components/containers/visibility.tsx
src/pages/trade-types/multiplier/index.tsx

Changes:
-   fix: multipluer page show info for non_eu countries while domain is uk

NikitK/ Multiplier content discrepancies in Deriv.com

---

src/common/utility.js
src/components/containers/visibility.tsx

MohammadH/ Disable redirection in localhost

---

src/pages/home/_hero.tsx

Vijayasreee/fix: add basket indices to homepage (translations required)

---

src/components/form/input.tsx
src/components/hooks/use-browser-resize.tsx
src/components/layout/nav/nav-interim.tsx
src/pages/landing/ebooks/components/_get-ebook.tsx

Changes:
-   Fix page-data.json 404 error in landing pages by changing navbar logo url. Some TS refactors has been done in this PR as well.

MohammadH/ Fix page-data.json 404 error in landing pages

---

src/pages/academy/components/_search-banner.tsx

MohammadH/ Fix academy search banner overlap

---

src/components/elements/carousel/carousel-style.js
src/pages/academy/components/_hero.tsx

Changes:
-Changed the home page banner in academy

Aswathy/fix: changed the home banner academy

---

src/components/custom/signup.js

Prince/ revert back affiliate signup flow

---

src/pages/p2p/components/_dp2p.tsx

Reverts binary-com/deriv-com#3000

Revert "Adrienne / Replaced youtube video in P2P landing page"

---

src/pages/help-centre/_article-component.tsx
src/pages/help-centre/account.tsx
src/pages/help-centre/affiliate-programme.tsx
src/pages/help-centre/deposits-and-withdrawals.tsx
src/pages/help-centre/deriv-p2p.tsx
src/pages/help-centre/deriv-x.tsx
src/pages/help-centre/dmt5.tsx

MohammadH/ Fix iphone not showing number lists

---

src/pages/index.tsx
src/pages/who-we-are/index.tsx

Update  Meta Desc

---

src/components/elements/typography.js

Vijayasree/fix: semantic html rules

---

src/pages/partners/payment-agent/index.tsx

p2p banner removal for eu/uk clients

---

src/pages/partners/payment-agent/_faq-data.tsx
src/pages/partners/payment-agent/_faq.tsx
src/pages/partners/payment-agent/_tap-into.tsx
src/pages/partners/payment-agent/_who-can-apply.tsx
src/pages/partners/payment-agent/_your-control.tsx

Changes:
- updated PA page content
- because there was a runtime error on Mobile and Desktop rendering, affecting the GatsbyImage, I removed the conditional rendering and applied the needed changes with styles ( the main goal is the height of the image I guess ). but then if this is ok with the current implementation of conditional rendering I can revert my changes. 

Mohsen / updated PA page content

---

src/components/containers/seo.js
src/pages/bug-bounty/_about-deriv.tsx
src/pages/bug-bounty/_submit_a_bug_report.tsx
src/pages/bug-bounty/components/_hero_component.tsx
src/pages/bug-bounty/index.tsx

Changes:
Added SEO Title, meta description, 
changed h3 to p tag, 
changed alt tag description for images
-   ...

Meenu/refactor: seo implementation for bug bounty

---

src/pages/partners/payment-agent/_faq-data.tsx
src/pages/partners/payment-agent/_faq.tsx
src/pages/partners/payment-agent/_tap-into.tsx
src/pages/partners/payment-agent/_who-can-apply.tsx
src/pages/partners/payment-agent/_your-control.tsx

Reverts binary-com/deriv-com#3105

Revert "Mohsen / updated PA page content"

---

deriv.com.conf

Changes:
-   added 301 http code for the  [markets link](https://deriv.com/markets/forex/)

fiona / add 301 request to markets/forex page

---

deriv.com.conf

Reverts binary-com/deriv-com#2656

Revert "fiona / add 301 request to markets/forex page"

---

.github/workflows/translation-push.yml

Prince/ Update translation-push.yml

---

.github/workflows/translation-push.yml

Prince/Update translation-push.yml

---

i18n-config.js
src/components/localization/language-dropdown.js

Meenu/fix: turkey flag fix in dropdown

---

.github/workflows/translation-push.yml

Prince/ Update Translation Slack Webhook

---

src/pages/academy/components/_hero.tsx

MohammadH/ Academy hero banner issue

---

src/components/localization/language-dropdown.js

Pavel/ Align language flags

---

src/components/layout/footer/main-links.js

Mitra/fix: add space for deriv x in footer

---

src/pages/careers/_model/_locations/_locations.ts
src/pages/careers/_model/_locations/_locations.types.ts
src/pages/careers/locations/index.tsx

Changes:
Organized locations under deriv/careers.
Filter countries based on continent.
-   ...

Meenu/feat: created tabs and organised location

---

src/pages/academy/components/_hero.tsx

Mitra/fix: fix overflow in safari

---

src/pages/academy/common/_styles.ts
src/pages/academy/components/recent-featured-posts/_style.ts

Mitra/fix: fix the border radius issues for images in safari

---

scripts/translation-pre-commit.js

…cted properly
Changes:
-   ...

Prince/ Extract strings all the time

---

.gitignore
gatsby-config.js
package-lock.json
package.json

Changes:
- added webpack bundle analyzer gatsby plugin
- added analyze-bundle to generate report in webpack-bundle-report
- this won't affect the build process and only generates the report on running the script.
- added this new folder to .gitignore.

Mohsen / added webpack bundle analyzer

---

src/pages/academy/components/_search-banner.tsx

Changes:
Enabled search with search icon in deriv academy page.
-   ...

Meenu/fix: enable search with search icon

---

.github/workflows/production.yml
.github/workflows/staging.yml

Prerequisites:
Changes:
-   Publish website to Cloudflare pages: [cf-pages.deriv.com](https://cf-pages.deriv.com/) and [staging.cf-pages.deriv.com](https://staging.cf-pages.deriv.com)

empty: publish to Cloudflare (on push on master, on tag production)

---

.github/workflows/staging.yml

Changes:
-   fix npm dependency caching

yashim/chore: dependency caching

---

.github/workflows/staging.yml
src/pages/careers/besquare/components/sections/_highlights.tsx

Changes:
-  Remove cache key for Gatsby build folder

yashim/chore: remove Gatsby build folder caching

---

src/pages/markets/instruments/_cryptocurrencies-cfds.tsx
src/pages/markets/instruments/_market-symbols.tsx
src/pages/markets/instruments/_markets.tsx
src/pages/markets/static/content/_market-symbols.tsx

Konstantinos / Removal of TER/USD, BTC/XAU & BTC/XAG - ROW domain

---

src/common/utility.js
src/components/layout/layout.js

MohammadH/ Disable redirection from eu.deriv.com to deriv.com

---

src/components/custom/signup.js

Vijayasree/ Authorize api

---

src/common/utility.js

Prince/ missing import

---

src/common/utility.js
src/pages/academy/videos/index.tsx

Prince/ added utility redirection using a specific parameter

---

src/pages/trader-tools/common/_validation.tsx
src/pages/trader-tools/pnl-for-multipliers/_pnl_multipliers_calculator.tsx

Konstantinos / Any field that involves price shouldn't have character limit in PnL for multipliers

---

src/components/custom/platforms-dropdown.js
src/components/layout/nav/components/nav-desktop.tsx
src/components/layout/nav/styles/nav-styles.ts

Changes:
-  fixed arrow in menu drop down navigation bar 

Mohsen / fixed menu drop down arrows

---

src/components/hooks/use-website-status.tsx
src/pages/payment-methods/_mobile-accordian-item.js
src/pages/payment-methods/_mobile-expanded-list.js
src/pages/payment-methods/index.js
src/store/index.tsx

Vijayasree/chore: remove crypto_config dependency from website_status

---

src/pages/p2p/components/_exchange-steps.tsx
src/pages/payment-methods/_payment-data.js

Changes:
-   ...
-   [ x] Documentation update

Pavel/fix: expiry time

---

src/components/layout/footer/common/style.js

Changes:
- Fixed Footer Logo Alignment

Mohsen / fixed deriv footer logo alignment

---

src/pages/deriv-go/index.js

fix: lint issue

---

.github/workflows/content.yml
.github/workflows/production.yml
.github/workflows/staging.yml

- Also deploy to Cloudflare on "Release Academy Content" 
- Cloudflare new website url

Publish to cloudflare when releasing academy content

---

src/templates/video.tsx

MohammadH/ Fix video title jump in academy individual video page in desktop

---

src/pages/landing/ebooks/components/_hero.tsx
src/pages/landing/ebooks/crypto.tsx

behnaz / fix: ebook color

---

src/components/elements/carousel/carousel.js
src/pages/home/_markets_fold.tsx

MohammadH/ Disable markets fold auto scroll on uk ip

---

crowdin/messages.json
src/pages/help-centre/affiliate-programme.tsx

Vijayasree/ fix: unextracted string from help center

---

.github/workflows/content.yml

Changes:
-   Caching is failing, remove cache step. We had a similar problem with other workflows (see [2507185066](https://github.com/binary-com/deriv-com/actions/runs/2507185066)) and applied the same kind of fix (see [55f96af3255d340a003fd8ce56e446ee11ea511c](https://github.com/binary-com/deriv-com/commit/55f96af3255d340a003fd8ce56e446ee11ea511c))

Remove failing caching

---

src/common/constants.ts

Vijayasree/text: update cfd %

---

.github/CODEOWNERS

Changes:
-   Add michio as codeowners

chore: add michio to codeowners

---

gatsby-node.js

MohammadH/ Fix weekly post not showing up in academy

---

crowdin/messages.json
src/pages/who-we-are/components/leaders.tsx

Konstantinos / [FE Deriv.com squad] Remove Antony from Who we are page

---

src/components/layout/footer/common/style.js
src/components/layout/livechat.tsx
src/pages/trade-types/cfds/_available-markets.tsx
src/pages/trade-types/multiplier/_markets-available.tsx

Changes:
Fixed localization issue in the "Market Available" section of CFD and option trade types.
-   ...

Meenu/ fix: fixed language changes on cfd and multiplier pages

---

src/pages/home/_p2p_home_banner.tsx

removed all unused variables

---

scripts/handle-translations.js

refactor: remove condition on pulling translations

---

src/components/elements/carousel/carousel.js

Vijayasree/ fix: auto scroll when clicked

---

src/pages/academy/components/_search-banner.tsx

Vijayasree / fix: close search bar when clicked outside

---

gatsby-node.js
src/components/hooks/use-academy-data.tsx
src/pages/academy/blog/index.tsx

MohammadH/ Remove limitation of fetching only 100 posts in academy

---

src/pages/careers/_dept-layout-components/_dept-description.tsx

MohammadH/ Fix not showing careers image in mobile

---

gatsby-node.js
src/common/utility.js
src/components/hooks/use-academy-data.tsx
src/pages/academy/search/_video-parent-wrapper.tsx
src/pages/academy/search/index.tsx
src/pages/academy/videos/_all-videos.tsx
src/pages/academy/videos/index.tsx
src/templates/video.tsx

MohammadH/ Remove fetching academy videos

---

.github/workflows/translation-push.yml
commitlint.config.js

Prince/ POC Translation pull 

---

.github/workflows/translation-push.yml

Prince/ Pull automation: API key fix

---

.github/workflows/translation-push.yml

Prince/ POC Translation pull automation

---

.github/workflows/translation-push.yml

Prince/ Update translation pull workflow create git identity 

---

src/pages/dmt5/_download-app.tsx

Mitra/fix: update font size

---

src/pages/p2p/components/_availability.tsx

Konstantinos / there is a separator line on top of "On your mobile" in p2p page mobile view

---

src/pages/p2p/components/_dp2p.tsx

Konstantinos / [FE Deriv.com squad] [P2P] Replace the video on p2p page

---

src/pages/terms-and-conditions/_clients-grid.tsx

Konstantinos / [FE Deriv.com squad] [EU] Remove DBVI and DFX Additional Terms from Terms and conditions page   

---

src/components/hooks/use-active-link-state.tsx

Changes:
-   Updated active link state to fix missing red line under nav

Meenu/fix: missing red line in nav fixed

---

.github/workflows/translation-push.yml

Prince/ Displaying last commit as part of workflow trigger

---

.github/workflows/translation-push.yml

Prince/ Display last commit message for translation pull automation

---

src/components/form/button.ts
src/themes/function.ts

MohammadH/ Fix button component typescript errors
